### ISSUE TITLE
My Laptop Processor manufacturer says on their website that it supports vulkan but xenia does not recognise it 

### ISSUE THREAD

**Issue by Bobrow** [benvanik/xenia#1056]
I have a HP Envy 15 ah-100na Laptop that has a AMD A10-8700P CPU with Radeon™ R6 Graphics, I ahve checked on the website that it supports Vulkan API and it says it does but xenia does not see it.

I could try to update the driver but it would take ages.

this is the log file:
[xenia.log](https://github.com/benvanik/xenia/files/1536663/xenia.log)

**Comment by raynebc** [comment]
You probably have no choice but to try a newer video driver.  I couldn't find any immediate answer on whether this integrated graphics driver supports a new enough version of Vulkan.

**Comment by Bobrow** [comment]
I'm just in the process of getting the new driver. Due to what it says whilst extracting ( Extract: VulkanRT.exe) I am hopeful 👍

**Comment by Bobrow** [comment]
It's now working 👍 👍 👍 👍 👍
