### ISSUE TITLE
[VK] Vulkan Initialization failed.

### ISSUE THREAD

**Issue by Sleepy93** [benvanik/xenia#1060]
After the build of "[Vulkan] Propagate swap chain initialization errors" 
Xenia crashes on any games.

[#4ca8cafc](https://github.com/benvanik/xenia/commit/4ca8cafc1ba2ddf279bd846002f6c7c71b565125)

Vulkan check: vkCreateImage returned VK_ERROR_INITIALIZATION_FAILED

**Comment by Sleepy93** [comment]
Still crash with 
https://github.com/benvanik/xenia/commit/45846f25acc392fe02b40b9925fa891bd335cc77

**Comment by DrChat** [comment]
Can you post your log?

**Comment by DrChat** [comment]
Related to #756
