### ISSUE TITLE
Linux Build Errors Antergos Arch Linux

### ISSUE THREAD

**Issue by Gamedev1909** [benvanik/xenia#1062]
- building (all):debug...
make: Entering directory '/home/wardoc/xenia/build'
==== Building imgui (debug_linux) ====
==== Building capstone (debug_linux) ====
==== Building glew (debug_linux) ====
==== Building gflags (debug_linux) ====
==== Building glslang-spirv (debug_linux) ====
==== Building libavutil (debug_linux) ====
==== Building snappy (debug_linux) ====
gflags.cc
gflags_completions.cc
gflags_reporting.cc
imgui.cpp
snappy-sinksource.cc
glew.c
InReadableOrder.cpp
snappy-stubs-internal.cc
SPVRemapper.cpp
==== Building spirv-tools (debug_linux) ====
MCInst.c
imgui_demo.cpp
==== Building vulkan-loader (debug_linux) ====
imgui_draw.cpp
/bin/sh: clang++-3.8: command not found
make[1]: *** [snappy.make:181: obj/Linux/Debug/Linux/Debug/snappy/snappy-sinksource.o] Error 127
make[1]: *** Waiting for unfinished jobs....
MCInstrDesc.c
/bin/sh: clang++-3.8: command not found
make[1]: *** [imgui.make:181: obj/Linux/Debug/Linux/Debug/imgui/imgui.o] Error 127
make[1]: *** Waiting for unfinished jobs....
/bin/sh: clang++-3.8: command not found
make[1]: *** [gflags.make:187: obj/Linux/Debug/Linux/Debug/gflags/gflags_reporting.o] Error 127
make[1]: *** Waiting for unfinished jobs....
/bin/sh: clang++-3.8: command not found
make[1]: *** [gflags.make:181: obj/Linux/Debug/Linux/Debug/gflags/gflags.o] Error 127
/bin/sh: clang++-3.8: command not found
/bin/sh: clang++-3.8: command not found
make[1]: *** [snappy.make:184: obj/Linux/Debug/Linux/Debug/snappy/snappy-stubs-internal.o] Error 127
make[1]: *** [glslang-spirv.make:183: obj/Linux/Debug/Linux/Debug/glslang-spirv/InReadableOrder.o] Error 127
make[1]: *** Waiting for unfinished jobs....
SpvBuilder.cpp
adler32.c
/bin/sh: clang++-3.8: command not found
aes.c
make[1]: *** [glslang-spirv.make:186: obj/Linux/Debug/Linux/Debug/glslang-spirv/SPVRemapper.o] Error 127
make: *** [Makefile:203: snappy] Error 2
make: *** Waiting for unfinished jobs....
/bin/sh: clang++-3.8: command not found
make[1]: *** [gflags.make:184: obj/Linux/Debug/Linux/Debug/gflags/gflags_completions.o] Error 127
MCRegisterInfo.c
make: *** [Makefile:167: gflags] Error 2
SStream.c
/bin/sh: clang++-3.8: command not found
make[1]: *** [imgui.make:184: obj/Linux/Debug/Linux/Debug/imgui/imgui_demo.o] Error 127
X86ATTInstPrinter.c
/bin/sh: clang-3.8: command not found
cJSON.c
make[1]: *** [glew.make:179: obj/Linux/Debug/Linux/Debug/glew/glew.o] Error 127
make: *** [Makefile:173: glew] Error 2
/bin/sh: clang-3.8: command not found
make[1]: *** [capstone.make:193: obj/Linux/Debug/Linux/Debug/capstone/MCInstrDesc.o] Error 127
X86Disassembler.c
X86DisassemblerDecoder.c
/bin/sh: clang-3.8: command not found
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [capstone.make:190: obj/Linux/Debug/Linux/Debug/capstone/MCInst.o] Error 127
assembly_grammar.cpp
/bin/sh: clang++-3.8: command not found
binary.cpp
make[1]: *** [glslang-spirv.make:189: obj/Linux/Debug/Linux/Debug/glslang-spirv/SpvBuilder.o] Error 127
make: *** [Makefile:179: glslang-spirv] Error 2
diagnostic.cpp
atomic.c
/bin/sh: clang-3.8: command not found
make[1]: *** [capstone.make:199: obj/Linux/Debug/Linux/Debug/capstone/SStream.o] Error 127
/bin/sh: clang-3.8: command not found
make[1]: *** [capstone.make:196: obj/Linux/Debug/Linux/Debug/capstone/MCRegisterInfo.o] Error 127
audio_fifo.c
/bin/sh: clang++-3.8: command not found
make[1]: *** [imgui.make:187: obj/Linux/Debug/Linux/Debug/imgui/imgui_draw.o] Error 127
make: *** [Makefile:185: imgui] Error 2
/bin/sh: clang-3.8: command not found
/bin/sh: clang-3.8: command not found
make[1]: *** [capstone.make:202: obj/Linux/Debug/Linux/Debug/capstone/X86ATTInstPrinter.o] Error 127
disassemble.cpp
make[1]: *** [libavutil.make:227: obj/Linux/Debug/Linux/Debug/libavutil/adler32.o] Error 127
make[1]: *** Waiting for unfinished jobs....
ext_inst.cpp
debug_report.c
/bin/sh: clang-3.8: command not found
make[1]: *** [capstone.make:208: obj/Linux/Debug/Linux/Debug/capstone/X86DisassemblerDecoder.o] Error 127
/bin/sh: clang-3.8: command not found
make[1]: *** [libavutil.make:230: obj/Linux/Debug/Linux/Debug/libavutil/aes.o] Error 127
dev_ext_trampoline.c
/bin/sh: clang-3.8: command not found
/bin/sh: clang++-3.8: command not found
/bin/sh: clang-3.8: command not found
make[1]: *** [libavutil.make:233: obj/Linux/Debug/Linux/Debug/libavutil/atomic.o] Error 127
make[1]: *** [vulkan-loader.make:188: obj/Linux/Debug/Linux/Debug/vulkan-loader/cJSON.o] Error 127
make[1]: *** [spirv-tools.make:202: obj/Linux/Debug/Linux/Debug/spirv-tools/assembly_grammar.o] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: *** Waiting for unfinished jobs....
extension_manual.c
/bin/sh: clang-3.8: command not found
make[1]: *** [capstone.make:205: obj/Linux/Debug/Linux/Debug/capstone/X86Disassembler.o] Error 127
make: *** [Makefile:161: capstone] Error 2
/bin/sh: clang++-3.8: command not found
make[1]: *** [spirv-tools.make:208: obj/Linux/Debug/Linux/Debug/spirv-tools/diagnostic.o] Error 127
/bin/sh: clang++-3.8: command not found
make[1]: *** [spirv-tools.make:211: obj/Linux/Debug/Linux/Debug/spirv-tools/disassemble.o] Error 127
/bin/sh: clang-3.8: command not found
make[1]: *** [libavutil.make:236: obj/Linux/Debug/Linux/Debug/libavutil/audio_fifo.o] Error 127
make: *** [Makefile:197: libavutil] Error 2
/bin/sh: clang-3.8: command not found
/bin/sh: clang++-3.8: command not found
make[1]: *** [vulkan-loader.make:191: obj/Linux/Debug/Linux/Debug/vulkan-loader/debug_report.o] Error 127
make[1]: *** [spirv-tools.make:205: obj/Linux/Debug/Linux/Debug/spirv-tools/binary.o] Error 127
/bin/sh: clang++-3.8: command not found
/bin/sh: clang-3.8: command not found
make[1]: *** [spirv-tools.make:214: obj/Linux/Debug/Linux/Debug/spirv-tools/ext_inst.o] Error 127
make[1]: *** [vulkan-loader.make:194: obj/Linux/Debug/Linux/Debug/vulkan-loader/dev_ext_trampoline.o] Error 127
make: *** [Makefile:209: spirv-tools] Error 2
/bin/sh: clang-3.8: command not found
make[1]: *** [vulkan-loader.make:197: obj/Linux/Debug/Linux/Debug/vulkan-loader/extension_manual.o] Error 127
make: *** [Makefile:215: vulkan-loader] Error 2
make: Leaving directory '/home/wardoc/xenia/build'

ERROR: build failed with one or more errors.

**Comment by gibbed** [comment]
Please post more information about your problem. Posting the compilation log of a failed build that outright says "I don't have clang-3.8 installed" and saying nothing else isn't very helpful.

**Comment by Gamedev1909** [comment]
Why such a old version of clang ... even with clang 3.8 installed same error forget it I will figure it out instead

**Comment by mrcmunir** [comment]
Compile fine for me in antergos
You need libc++abi from aur https://aur.archlinux.org/packages/libc%2B%2Babi/

**Comment by Gamedev1909** [comment]
Good to get some help instead of snippyness you rock for being kind

**Comment by DrChat** [comment]
Should be fixed. Keep an eye on travis.
