### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by 7oxicshadow** [benvanik/xenia#1066]
I noticed some Linux commits had gone through so I decided to see how far building has progressed.

I called the "./xb build" command and got the following error when using clang4.0:

```
../src/xenia/gpu/spirv_shader_translator.cc:1376:5: error: cannot jump from
      switch statement to this case label
    case VertexFormat::kUndefined:
    ^
../src/xenia/gpu/spirv_shader_translator.cc:1282:12: note: jump bypasses
      variable initialization
      auto vertex_ptr = vertex_binding_map_[instr.operands[1].storage_index]
           ^
../src/xenia/gpu/spirv_shader_translator.cc:1333:5: error: cannot jump from
      switch statement to this case label
    case VertexFormat::k_11_11_10: {
    ^
../src/xenia/gpu/spirv_shader_translator.cc:1282:12: note: jump bypasses
      variable initialization
      auto vertex_ptr = vertex_binding_map_[instr.operands[1].storage_index]
           ^
../src/xenia/gpu/spirv_shader_translator.cc:1288:5: error: cannot jump from
      switch statement to this case label
    case VertexFormat::k_10_11_11: {
    ^
../src/xenia/gpu/spirv_shader_translator.cc:1282:12: note: jump bypasses
      variable initialization
      auto vertex_ptr = vertex_binding_map_[instr.operands[1].storage_index]
           ^
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [xenia-base-tests.make:136: bin/Linux/Debug/xenia-base-tests] Error 1
make: *** [Makefile:263: xenia-base-tests] Error 2
make: *** Waiting for unfinished jobs....
3 errors generated.
```

The building.md file mentions using clang3.8 but the example commands to install it use clang4.0. Is clang4.0 supported? I am not building on Ubuntu, I am using Fedora.

Thanks.

**Comment by Razzile** [comment]
i'm guessing clang doesn't like the use (or lack) of braces for each switch case at that part.

**Comment by Razzile** [comment]
this should be fixed in https://github.com/benvanik/xenia/commit/d512d4127fa12a710e5d1d6d8067fe050b3445e7

**Comment by 7oxicshadow** [comment]
Thanks for this, it builds fine now.

Should the xenia-ui-window-gl-demo do anything? At the moment it opens and instantly closes with:

`Gtk-WARNING **: Attempting to add a widget with type GtkDrawingArea to a GtkWindow, but as a GtkBin subclass a GtkWindow can only contain one widget at a time; it already contains a widget of type GtkBox`

I appreciate that it is early days yet and there is further commits pending for Linux so it just curiosity at this point.

**Comment by dougvj** [comment]
xenia-ui-window-gl-demo is broken still, but vulkan works with my latest pull request
