### ISSUE TITLE
Why does Xenia need Vulkan?

### ISSUE THREAD

**Issue by fancymelonub** [benvanik/xenia#1068]
For some reason, the Vulkan builds of Xenia are now the main builds. The Xbox 360 didn't use Vulkan. Actually, Vulkan didn't even exist before 2016. Yet, I need it for Xenia, by my system doesn't even support Vulkan. Is there any buils that doesn't require Vulkan?

**Comment by tetration** [comment]
> For some reason, the Vulkan builds of Xenia are now the main builds. The Xbox 360 didn't use Vulkan. Actually, Vulkan didn't even exist before 2016. Yet, I need it for Xenia, by my system doesn't even support Vulkan. Is there any buils that doesn't require Vulkan?

Why you dont like Vulkan? Vulkan is one of the best graphics sdk platform ever made. Its currently giving a big performance boost in several games. It will probably leave DirectX and Open Gl eating dust in some year from now on. And the main advantage about it is that its multiplatform unlike Direct X and several developers are adopting it. Thus it will help open the path for more games to be released on Linux as well.

**Comment by Margen67** [comment]
If your GPU doesn't have Vulkan I doubt it would run xenia very well.

**Comment by jobs-git** [comment]
Cause there are many ways to kill a cat, once you have tried programming, you will notice that there are many ways to implement the same thing. Similar thing with xenia and vulkan.

**Comment by JXPZ** [comment]
Vulka fast ah OpenGL feet kkkkkkkkkkkkkk

**Comment by shadowbrony33** [comment]
@DrChat Close

**Comment by DrChat** [comment]
Vulkan gives us an edge in emulation that OpenGL cannot, and that's why we use it. If you want to see support for another backend, you are definitely welcome to start contributing!

For now, Xenia has an OpenGL backend that is deprecated and will be removed eventually.
