### ISSUE TITLE
Vulkan support broken - NVIDIA GTX 980 Driver Version 390.65

### ISSUE THREAD

**Issue by psychic2ombie** [benvanik/xenia#1071]
So I've been trying to use Xenia recently and I get an error that Xenia was unable to initialize Vulkan even though my GPU is compatible with Vulkan and on the compatibility list. I have already tried doing a clean install of my drivers to no avail. This happens on old and new versions if Xenia

Log file https://pastebin.com/JwSbjTHG

**Comment by maxton** [comment]
What is the model of your GPU? What is your driver version?

**Comment by psychic2ombie** [comment]
GPU:GTX 980
Version:390.65

**Comment by JXPZ** [comment]
Same thing aki 1050 ti oc edition 4gb gigabyte xenia rpcs3 same problem Vulkan

**Comment by JXPZ** [comment]
1050 TI OC EDITION 4GB of support Vulkan more problem this in drive or emulators?

**Comment by JXPZ** [comment]
Drive 390.65 downgrade 388.71

**Comment by JXPZ** [comment]
problem is in this geforce 390.65 drive can downgrade to 388.71 and wait for nvidia si to pronounce ah respect of that with beta or stable update.

**Comment by Margen67** [comment]
This driver update broke RPCS3 as well. https://github.com/RPCS3/rpcs3/issues/4036

**Comment by JXPZ** [comment]
Yes friend problem Geforce drive expecting fix or beta fix drive Nvidia Geforce

**Comment by JXPZ** [comment]
https://www.reddit.com/r/rpcs3/comments/7p33t1/rpcs3_broken_with_latest_nvidia_driver_39065/

**Comment by JXPZ** [comment]
FIX FIX testing aki to see if it will catch

**Comment by JXPZ** [comment]
https://www.reddit.com/r/rpcs3/comments/7p33t1/rpcs3_broken_with_latest_nvidia_driver_39065/

**Comment by DrChat** [comment]
This issue is unrelated to Xenia - but so others don't make more issues, I'm leaving it open until NVIDIA fixes it.

**Comment by shadowninja108** [comment]
If you guys need a fix in the meantime, a redditor found a workaround to enable Vulkan. It requires regedit, but it's just adding one value. This worked great for me. [Here it is.](https://www.reddit.com/r/rpcs3/comments/7p33t1/rpcs3_broken_with_latest_nvidia_driver_39065/dsewfbr/)

**Comment by yxmline** [comment]
390.77 not fix this issue

**Comment by DrChat** [comment]
Fixed in abd21e5034f931ad6bdc58e8b58202bc2995995f
