### ISSUE TITLE
Xenia crashes after Main Window

### ISSUE THREAD

**Issue by aevans0001** [benvanik/xenia#1080]
[//]: # (Describe what's going wrong:)
When I load Xenia, it loads get to the white screen with the menus, but does not give me access to the menus before it crashes
[//]: # (Describe what should happen:)
It should give me access to load iso 
[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)
Here is my log
i> 0000454C Build: detached / 5477b1e40fcbce42024e6080d87917df60c8ec48 on Jan 22 2018
i> 0000454C Initializing Vulkan 1.0.0...
i> 0000454C Found 3 global layers:
i> 0000454C - VK_LAYER_VALVE_steam_overlay (spec: 1.0.3, impl: 0.0.1)
i> 0000454C   Steam Overlay Layer
i> 0000454C - VK_LAYER_NV_optimus (spec: 1.0.56, impl: 0.0.1)
i> 0000454C   NVIDIA Optimus layer
i> 0000454C - VK_LAYER_LUNARG_standard_validation (spec: 1.0.54, impl: 0.0.1)
i> 0000454C   LunarG Standard Validation Layer
i> 0000454C Found 11 global extensions:
i> 0000454C - VK_KHR_surface (0.0.25)
i> 0000454C - VK_KHR_win32_surface (0.0.5)
i> 0000454C - VK_KHR_get_physical_device_properties2 (0.0.1)
i> 0000454C - VK_EXT_debug_report (0.0.8)
i> 0000454C - VK_EXT_display_surface_counter (0.0.1)
i> 0000454C - VK_KHR_get_surface_capabilities2 (0.0.1)
i> 0000454C - VK_KHX_device_group_creation (0.0.1)
i> 0000454C - VK_KHR_external_fence_capabilities (0.0.1)
i> 0000454C - VK_KHR_external_memory_capabilities (0.0.1)
i> 0000454C - VK_KHR_external_semaphore_capabilities (0.0.1)
i> 0000454C - VK_NV_external_memory_capabilities (0.0.1)
i> 0000454C Verifying layers and extensions...
i> 0000454C - optional extension VK_EXT_debug_marker not found
i> 0000454C - enabling extension VK_KHR_surface (0.0.25)
i> 0000454C - enabling extension VK_KHR_win32_surface (0.0.5)
i> 0000454C Initializing application instance...
i> 0000454C Debug validation layer not installed; ignoring

**Comment by DrChat** [comment]
Most likely related to #798. Download [HWInfo64](https://www.fosshub.com/HWiNFO.html) portable and then check if your CPU supports AVX. If it does, post another comment here and I'll reopen the issue.
