### ISSUE TITLE
Will codes from RPCS3 project be helpful to Xenia?

### ISSUE THREAD

**Issue by jackchentwkh** [benvanik/xenia#1087]
the PS3 emulator RPCS3 is progressing very quickly in past year. Currently there are 1/4 titles playable, and 2/3 titles are within playable or ingame. the speed is also quick. 
Since the CPU/SPU/GPU are very similar between PS3 and Xbox360, will the codes from RPCS3 be helpful to Xenia?

**Comment by shadowbrony33** [comment]
@jackchentwkh The PS3 has very little in common with the Xbox 360, even though the CELL CPU in the PS3 is based on PPC it works very differently. Also note the the GPUs are completely different and same goes for pretty much ALL of the APIs that the systems use.

**Comment by jackchentwkh** [comment]
thanks for your explain. But in LLE, RPCS3 did a good job at SPU emulation both at speed and accuracy, won't that be a good reference?

**Comment by gibbed** [comment]
360 doesn't have SPUs.

**Comment by jackchentwkh** [comment]
wow, that's new to me. thanks a lot for telling me that.

**Comment by jackchentwkh** [comment]
I think this issue can be closed.
