### ISSUE TITLE
No textures .. just black {sonic 06} 

### ISSUE THREAD

**Issue by AmrSaadMEGA** [benvanik/xenia#1091]
[Screenshoot 1](http://www.m5zn.com/newuploads/2018/03/01/jpg//1f29707b2c5e375.jpg)
[Screenshoot 2](http://www.m5zn.com/newuploads/2018/03/01/jpg//1f29707b2c5e375.jpg)
vulkan - amd r7 m265 - intel core i7 4500u - 4gb ram

**Comment by Parovozik** [comment]
check there https://github.com/xenia-project/game-compatibility/issues/285
 3 ways: or you used clear master build, or not used fixed cache, or this specific AMD trouble

**Comment by DrChat** [comment]
Most likely related to #756. Gonna close this, reopen it if it isn't related.
