### ISSUE TITLE
Crashing on AMD GPUs whenever most games attempt to render a 3D object

### ISSUE THREAD

**Issue by shadowbrony33** [benvanik/xenia#1093]
I've brought this issue up before but I couldn't find a fix for it.
This has been an issue since commit 28ebb4b, removing the commit via github fixes the issue but when manually reverting it in the code doesn't fix it and I have no idea why this is.

Most games crash when trying to render a 3D object.
However Minecraft isn't effected for some reason but crashes a few moments into gameplay.

Side Note: D24 is working on AMD cards but some rendering is broken, easily fixed by switching to D32 but doesn't appear to be the cause of the crashes.

(Don't know how to get the call stack)

Minecraft:
[minecraft.log](https://github.com/benvanik/xenia/files/1777697/minecraft.log)

CoD 4:
[CoD4.log](https://github.com/benvanik/xenia/files/1777709/CoD4.log)

CoD Ghosts:
[CoDGhosts.log](https://github.com/benvanik/xenia/files/1777702/CoDGhosts.log)

Halo Reach: 
[HaloReach.log](https://github.com/benvanik/xenia/files/1777704/HaloReach.log)

Sonic 06:
[Sonic06.log](https://github.com/benvanik/xenia/files/1777707/Sonic06.log)

**Comment by RandomAnimeGamer** [comment]
Same. This is really annoying, and it seems that any effort I made to bring it up was to no avail as well. I'm using an AMD RX460, which is supported by Vulkan. Using the link given on Xenia's website indicates that many driver versions of AMD RX460 on Windows 10 are supported.

**Comment by shadowbrony33** [comment]
@DrChat 
![image](https://user-images.githubusercontent.com/14355117/38770501-292814d6-3fd1-11e8-9bf2-a0f28f50806e.png)

It appears that Xenia crashes when attempting to create a shader / an invalid shader is created?

**Comment by Irixion** [comment]
I believe this is related to AMD cards not supporting a texture format. There's already other issues open.

**Comment by shadowbrony33** [comment]
@Irixion Not the case anymore, some new commits for the shader translator fixed this issue.
