### ISSUE TITLE
Xenia Error Graphis

### ISSUE THREAD

**Issue by KDZL** [benvanik/xenia#1096]
![esboco 2](https://user-images.githubusercontent.com/35670762/36940785-85b05fb0-1f29-11e8-9055-30f24f5cd98d.png)

**Comment by KDZL** [comment]
https://ci.appveyor.com/project/benvanik/xenia/build/1.0.1211-master/job/eyqxq8h08o0bt67a

**Comment by gibbed** [comment]
Follow the New Issue guide next time.

**Comment by DiamondMaster07** [comment]
I know this is a closed issue, but I recently got this error message a lot completely randomly
