### ISSUE TITLE
xenia website review

### ISSUE THREAD

**Issue by YeimiK** [benvanik/xenia#1116]
Xenia emulation project should have a new website interface. More accurate, good looking and with and enhanced compat database.
I'm thinking of creating something like that. You can contact me at yeimik101@outlook.com

**Comment by shadowbrony33** [comment]
It meets all those requirement IMO.

Are you just soliciting a service to make a new site?

**Comment by YeimiK** [comment]
Shure, why not. But my goal is tho make people know about what we are doing here, the hard work thats being made. And what a better way to do it than showing them. I just feel the current website isn't the best we can do.

**Comment by YeimiK** [comment]
I'm not saying the current website isbad in any form, i'm just saying that we need to improve things up.

**Comment by maxton** [comment]
If you want to improve the website, make a PR to the gh-pages branch.

**Comment by DrChat** [comment]
Yep, as @maxton said, if you have any changes in mind - feel free to create a PR!
