### ISSUE TITLE
Error trying to launch custom built executable for Xenia

### ISSUE THREAD

**Issue by 4digitmen** [benvanik/xenia#1119]
So, whenever i try to launch up this built executable (https://drive.google.com/file/d/0B_9vQUilzHlNYjVLRXlZYWlQbjA/view), i get an error saying "Unable to initialize Vulkan graphics subsystem", but the master build on the Xenia website works and launches without any errors. Help?

Specs: I5-4690K 
GTX 1060 
16 GB DDR3 RAM

[xenia.log](https://github.com/benvanik/xenia/files/1845696/xenia.log)
If it helps, this is the branch (https://github.com/allancat/xenia)

**Comment by maxton** [comment]
You should close this issue and open a new one on the branch you are actually using.

**Comment by 4digitmen** [comment]
@maxton I either cant or don't know how to.

**Comment by maxton** [comment]
It seems allancat has disabled issues. Regardless, this repo is not responsible for bugs in other people's forks.

**Comment by 4digitmen** [comment]
@maxton Can't this be a bug on my end though?

**Comment by Razzile** [comment]
it's possible you don't have a graphics driver that supports vulkan. try updating your gpu driver. Also as others have said, only issues pertaining to the main branch of xenia should be posted here

**Comment by 4digitmen** [comment]
@Razzile I have updated to latest drivers (391.24 Game Ready Driver) and I'm pretty sure that it supports Vulkan, as the main branch of Xenia doesn't have an error and plays games just fine (except the one I'm trying to play obviously). Anyway thanks for the help(?), i didn't really have anywhere to post this so i though i would post here.
