### ISSUE TITLE
Regression in texture sampling with LOD

### ISSUE THREAD

**Issue by parkerlamb** [benvanik/xenia#1124]
This error has cropped up for me recently. I haven't properly bisected it but it's definitely one of the recent commits which changed this behavior in the shader translation. This is happening on a GTX 1050.

Seems pretty self-explanatory, though I'm not sure of the correct fix.

Log excerpt (with shader validation turned on):
`!> 00000004 Failed to validate spv: -14`
`!> 00000004 SPIR-V Shader Validation failed! Error: Expected Coordinate to have at least 2 components, but given only 1: ImageSampleImplicitLod`
`!> 00000004 vkCreateGraphicsPipelines failed with code -1000012000`

I'm happy to provide any other info if need be.

**Comment by DrChat** [comment]
Thanks for the report - I've spotted where it's happening. What games did you encounter this on?
