### ISSUE TITLE
Issue compiling libxenia

### ISSUE THREAD

**Issue by xESWxDEATH** [benvanik/xenia#122]
The issue is the thread_local varible is undefined. Here is the full errors
1>..\..\src\xenia\gpu\gl4\gl4_shader.cc(23): error C2146: syntax error : missing ';' before identifier 'GL4ShaderTranslator'
1>..\..\src\xenia\gpu\gl4\gl4_shader.cc(23): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>..\..\src\xenia\gpu\gl4\gl_context.cc(24): error C2146: syntax error : missing ';' before identifier 'GLEWContext'
1>..\..\src\xenia\gpu\gl4\gl_context.cc(24): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>..\..\src\xenia\gpu\gl4\gl_context.cc(25): error C2146: syntax error : missing ';' before identifier 'WGLEWContext'
1>..\..\src\xenia\gpu\gl4\gl_context.cc(25): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>..\..\src\xenia\gpu\gl4\gl_context.cc(25): error C2086: 'int xe::gpu::gl4::thread_local' : redefinition

**Comment by benvanik** [comment]
Ah, I'm building with VS2015 now so I didn't notice this. Checking in fix (though there may be other issues).
