### ISSUE TITLE
VS2013 no longer builds, thread_local

### ISSUE THREAD

**Issue by Sinoxan** [benvanik/xenia#126]
..\..\src\xenia\gpu\gl4\gl4_shader.cc(27): error C2483: 'shader_translator_' : object with constructor or destructor cannot be declared 'thread'

https://github.com/benvanik/xenia/blob/c33613b2f89a9f2c9b37d4a0b0df1865c88c8ad2/src/xenia/gpu/gl4/gl4_shader.cc#L27

**Comment by x1nixmzeng** [comment]
It's unfortunately a C++11 feature only partially supported with VS2013 ([MSDN])

The [suggested workaround][KB] is to have all member functions public - so perhaps bump the required version to 2015?

[MSDN]: http://blogs.msdn.com/b/vcblog/archive/2014/11/17/c-11-14-17-features-in-vs-2015-preview.aspx
[KB]: http://support.microsoft.com/kb/117383/EN-US

**Comment by Sinoxan** [comment]
I forgot to mention that, it was indeed more of a heads up that 2013 is no longer supported.

**Comment by benvanik** [comment]
Ah yeah, darn. I've been using 2015 and this was bound to happen (and will likely happen again). I'll update the readme - thanks for pointing it out!
