### ISSUE TITLE
Fix WMV decoding/playback.

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#137]
Output is corrupt (blocky rainbows), and playback ends early. Conveni intro video should be 30+sec, but it stops at 5.

**Comment by vgturtle127** [comment]
Is WMV handled with the CPU/GPU? I figured that would be a software thing on the Xbox?

**Comment by benvanik** [comment]
It's almost entirely on the CPU. GPU does final YUV->RGB. There's likely a broken altivec instruction that is causing the block decoding errors, but I'm not sure what the duration issue is.

**Comment by vgturtle127** [comment]
Huh. You learn something new every day, I guess!

Is the audio supported yet?

**Comment by benvanik** [comment]
yes

**Comment by DrChat** [comment]
Some games that play WMV movies hang while decoding them (See: xenia-project/game-compatibility#49).

**Comment by DrChat** [comment]
Fixed in 3ebd53ba11b0e4dca6afda2f068614652686a7ff.

**Comment by vgturtle127** [comment]
I forgot about this. :blush: 

So is the audio in the WMV container have WMA audio?
