### ISSUE TITLE
Cannot press left in Puzzle Fighter.

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#138]
I have no idea why not. Other directions work. Confirmed XInput is delivering left dpad bit set.

**Comment by benvanik** [comment]
May be timing related, or uninitialized memory. Every few launches I can press left.

**Comment by benvanik** [comment]
Possibly related: Sonic moves left when no buttons pressed.

**Comment by x1nixmzeng** [comment]
This is playable for me, although I lose all input after a minute or so.

**Comment by benvanik** [comment]
Odd - so you can press left/etc? On character selection I can only go right/down, and when playing the game I cannot shift pieces to the left.

**Comment by x1nixmzeng** [comment]
The highlight at the character select screen is utterly broken - moving any direction moves it off-screen and my character is random. But I was able to move left in-game. I'll see if I can reproduce it.

**Comment by benvanik** [comment]
I briefly traced through it - I was definitely seeing the correct button
data getting returned on the XamInput calls, so there must be something
weird after that in the game code.

**Comment by raven02** [comment]
Another button pressing issue in Raiden IV. When in-game , pause button seems to be keep pressing itself and thus always showing pause menu

![raiden](https://cloud.githubusercontent.com/assets/3000282/8547315/a93ad2a2-24f0-11e5-9394-728579fff35f.jpg)

**Comment by raven02** [comment]
Button pressing issue in Raiden IV has been fixed now in latest build

**Comment by benvanik** [comment]
I believe this is OK now.
