### ISSUE TITLE
Simple game API usage scanner.

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#171]
Would be nice to point a tool at a path and have it load ISO/STFS, crack open the xex, and dump a list of APIs used. The resulting data would be useful when trying to find other games using APIs or verifying compatibility.

**Comment by x1nixmzeng** [comment]
Do you see this working as a static analysis tool? Running a pass on the translated machine code, resolving API calls may be something I could have a go at writing.

I'm not sure how to approach discovering arguments at the moment.

**Comment by benvanik** [comment]
Oh, that'd be cool, but something even simpler would be useful: load the xex, scan the import table, and dump them to a file/table/etc. That way if we change XamFoo or some other method we have a good way of knowing which games to re-test. Going further and identifying API usage patterns would be awesome too, but not required to be useful.

I imagined a command line app linking in libxenia that used the filesystem API to load the iso/stfs/etc then xex2.h/cc to load the xex and get the header. That'd be the laziest/fastest way at least :P

**Comment by x1nixmzeng** [comment]
Well there's plenty to go on - [xuser_module.cc](../blob/c846ec30c3b7dd5eab85a153aa9e2a679d1e9f78/src/xenia/kernel/objects/xuser_module.cc#L194) already dumps what we need!

I'll look into making it a bit more standalone.
