### ISSUE TITLE
console output broken from subsystem:windows

### ISSUE THREAD

**Issue by shuffle2** [benvanik/xenia#228]
`AttachConsole` seems to fail when `wmain` is reached from `wWinMain` (even with `AllocConsole`).  
This results in seeing no output on stdout.
Changing the xenia project's subsystem to console fixes the issue, but I'm not sure that is wanted...?
This is on Win10, so perhaps it is a behavioral change if it was working before.

**Comment by shuffle2** [comment]
To be clear, I am talking about `xe::AttachConsole` "failing", not `::AttachConsole`. And where "failing" means that it succeeds in that the new value for `stdout` seems OK, but all writes to that `FILE*` fail.

**Comment by benvanik** [comment]
I recommend redirecting stdout to a file - that's what I do, as there's too much being printed now for console or visual studio to keep up. I think I gave up trying to get the windows subsystem target to output to console stdout because of that. If you can find out why it's not working, though, that'd be cool.

Don't want the main project as a console project. The unit tests and such are setup as console projects, though, and they seem to output ok.

**Comment by shuffle2** [comment]
fwiw I tested some combinations, and this seems to be a behavioral change between "toolset v120 (vs2013)" and v140 (vs2015). e.g. even on win8 + v140, it's broken.  
This is actually pretty funny, since redirecting on the command line results in the output being correctly written, while not redirecting makes it magically disappear. It feels almost like a feature :D

**Comment by benvanik** [comment]
Oh Microsoft... :P

**Comment by shuffle2** [comment]
here is the fix:
```c++
void AttachConsole() {
  bool has_console = ::AttachConsole(ATTACH_PARENT_PROCESS) == TRUE;
  if (!has_console) {
    // We weren't launched from a console, so make one.
    has_console = AllocConsole() == TRUE;
  }
  has_console_attached_ = has_console;
  if (!has_console_attached_) {
    return;
  }

  for (auto &file : { stdout, stderr }) {
    freopen("CONOUT$", "w", file);
    setvbuf(file, nullptr, _IONBF, 0);
  }
}
```
I like it (I am also super-excited about the new cmd.exe on win10, so maybe my opinion shouldn't be trusted)...

**Comment by shuffle2** [comment]
Hum, this is actually still kind of broken because using `freopen` results in not being able to redirect stdout on the commandline, now (inverse problem from before). Oh well.  
fwiw I only wanted this to work so i could use `xenia --help`, heh.

**Comment by shuffle2** [comment]
At some point it would be nice to display the gflags help in some obvious way.  
Anyways this just looks like a breaking change in the new toolset - and it's documented. so bleh.

**Comment by benvanik** [comment]
Heh, fun. Whenever I move over to Win10 I'll make sure this all works :)
