### ISSUE TITLE
xb build failed

### ISSUE THREAD

**Issue by haza1608** [benvanik/xenia#254]
This is only the last part as it wouldn't let my scroll further up, but it is the same thing.

10>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-hir-test\ /FdC:\Program' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
9>cl : Command line warning D9027: source file 'Visual' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
11>cl : Command line warning D9027: source file 'Files' ignored
9>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
10>cl : Command line warning D9027: source file 'Files' ignored
11>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
9>cl : Command line warning D9027: source file 'Studio' ignored
10>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
11>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
9>  xenia_main.cc
10>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
11>cl : Command line warning D9027: source file 'Visual' ignored
9>cl : Command line warning D9027: source file 'Files' ignored
10>cl : Command line warning D9027: source file 'Visual' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
11>cl : Command line warning D9027: source file 'Studio' ignored
9>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
10>cl : Command line warning D9027: source file 'Studio' ignored
11>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-ppc-test\ /FdC:\Program', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
10>
11>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-ppc-test\ /FdC:\Program' ignored
9>cl : Command line warning D9027: source file 'Visual' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
11>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
10>cl : Command line warning D9027: source file 'Files' ignored
11>cl : Command line warning D9027: source file 'Files' ignored
9>cl : Command line warning D9027: source file 'Studio' ignored
10>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
11>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xenia\ /FdC:\Program', object file assumed
10>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
11>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
9>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xenia\ /FdC:\Program' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
11>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
10>cl : Command line warning D9027: source file 'Visual' ignored
11>cl : Command line warning D9027: source file 'Visual' ignored
9>cl : Command line warning D9027: source file 'Files' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
11>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
10>cl : Command line warning D9027: source file 'Studio' ignored
11>cl : Command line warning D9027: source file 'Studio' ignored
9>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
10>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-hir-test\ /FdC:\Program', object file assumed
11>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
10>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-hir-test\ /FdC:\Program' ignored
11>cl : Command line warning D9027: source file 'Files' ignored
9>cl : Command line warning D9027: source file 'Visual' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
11>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
10>cl : Command line warning D9027: source file 'Files' ignored
11>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
9>cl : Command line warning D9027: source file 'Studio' ignored
10>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
11>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
10>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
11>cl : Command line warning D9027: source file 'Visual' ignored
9>cl : Command line warning D9027: source file 'Files' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
11>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
10>cl : Command line warning D9027: source file 'Visual' ignored
11>cl : Command line warning D9027: source file 'Studio' ignored
9>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
11>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-ppc-test\ /FdC:\Program', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
10>cl : Command line warning D9027: source file 'Studio' ignored
11>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-ppc-test\ /FdC:\Program' ignored
9>cl : Command line warning D9027: source file 'Visual' ignored
10>c1xx : fatal error C1083: Cannot open source file: '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-hir-test\vc140.pdb /Gd /TP /errorReport:prompt ..\..\base\main_win.cc test_add.cc test_byte_swap.cc test_extract.cc test_insert.cc test_load_vector_shl_shr.cc test_pack.cc test_permute.cc test_sha.cc test_shl.cc test_shr.cc test_swizzle.cc test_unpack.cc test_vector_add.cc test_vector_max.cc test_vector_min.cc test_vector_rotate_left.cc test_vector_sha.cc test_vector_shl.cc test_vector_shr.cc xe-cpu-hir-test.cc': No such file or directory
11>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
11>cl : Command line warning D9027: source file 'Files' ignored
9>cl : Command line warning D9027: source file 'Studio' ignored
10>cl : Command line warning D9027: source file 'Files' ignored
11>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xenia\ /FdC:\Program', object file assumed
10>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
11>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
9>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xenia\ /FdC:\Program' ignored
10>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
11>cl : Command line warning D9027: source file 'Visual' ignored
9>cl : Command line warning D9027: source file 'Files' ignored
10>cl : Command line warning D9027: source file 'Visual' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
11>cl : Command line warning D9027: source file 'Studio' ignored
9>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
10>cl : Command line warning D9027: source file 'Studio' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
10>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-hir-test\ /FdC:\Program', object file assumed
11>cl : Command line warning D9027: source file 'Files' ignored
9>cl : Command line warning D9027: source file 'Visual' ignored
10>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-hir-test\ /FdC:\Program' ignored
11>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
11>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
9>cl : Command line warning D9027: source file 'Studio' ignored
10>cl : Command line warning D9027: source file 'Files' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
10>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
11>cl : Command line warning D9027: source file 'Visual' ignored
9>cl : Command line warning D9027: source file 'Files' ignored
10>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
11>cl : Command line warning D9027: source file 'Studio' ignored
9>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
10>cl : Command line warning D9027: source file 'Visual' ignored
11>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-ppc-test\ /FdC:\Program', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
11>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-ppc-test\ /FdC:\Program' ignored
9>cl : Command line warning D9027: source file 'Visual' ignored
10>cl : Command line warning D9027: source file 'Studio' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
11>cl : Command line warning D9027: source file 'Files' ignored
9>cl : Command line warning D9027: source file 'Studio' ignored
10>cl : Command line warning D9027: source file 'Files' ignored
11>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xenia\ /FdC:\Program', object file assumed
10>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
11>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
9>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xenia\ /FdC:\Program' ignored
10>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
9>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
11>cl : Command line warning D9027: source file 'Visual' ignored
9>cl : Command line warning D9027: source file 'Files' ignored
10>cl : Command line warning D9027: source file 'Visual' ignored
11>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
9>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
11>cl : Command line warning D9027: source file 'Studio' ignored
9>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
10>cl : Command line warning D9027: source file 'Studio' ignored
9>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
10>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-hir-test\ /FdC:\Program', object file assumed
9>cl : Command line warning D9027: source file 'Visual' ignored
10>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-cpu-hir-test\ /FdC:\Program' ignored
9>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
10>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
9>cl : Command line warning D9027: source file 'Studio' ignored
10>cl : Command line warning D9027: source file 'Files' ignored
9>c1xx : fatal error C1083: Cannot open source file: '14.0\Xenia\xenia\build\obj\Debug\xenia\vc140.pdb /Gd /TP /errorReport:prompt src\xenia\base\main_win.cc src\xenia\xenia_main.cc': No such file or directory
10>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
10>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
10>cl : Command line warning D9027: source file 'Visual' ignored
10>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
10>cl : Command line warning D9027: source file 'Studio' ignored
13>------ Build started: Project: xe-gpu-trace-viewer, Configuration: Debug x64 ------
12>CSC : error CS0006: Metadata file 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Xenia\xenia\build\bin\Debug\Xenia.Debug.dll' could not be found
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program', object file assumed
13>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program', object file assumed
13>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>  main_win.cc xe-gpu-trace-viewer.cc
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program', object file assumed
13>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>c1xx : fatal error C1083: Cannot open source file: '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\vc140.pdb /Gd /TP /errorReport:prompt ..\base\main_win.cc xe-gpu-trace-viewer.cc': No such file or directory
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program', object file assumed
13>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
13>cl : Command line warning D9024: unrecognized source file type '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program', object file assumed
13>cl : Command line warning D9027: source file '14.0\Xenia\xenia\build\obj\Debug\xe-gpu-trace-viewer\ /FdC:\Program' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Files', object file assumed
13>cl : Command line warning D9027: source file 'Files' ignored
13>cl : Command line warning D9024: unrecognized source file type '(x86)\Microsoft', object file assumed
13>cl : Command line warning D9027: source file '(x86)\Microsoft' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Visual', object file assumed
13>cl : Command line warning D9027: source file 'Visual' ignored
13>cl : Command line warning D9024: unrecognized source file type 'Studio', object file assumed
13>cl : Command line warning D9027: source file 'Studio' ignored
========== Build: 1 succeeded, 12 failed, 0 up-to-date, 0 skipped ==========

ERROR: build failed with errors

Error: 1

**Comment by Razzile** [comment]
From what I can tell, you cloned xenia to a folder with spaces in. For reasons unknown to me, xenia has to be built from a directory whose path has no spaces in at all.

**Comment by haza1608** [comment]
Ok I'll clone it to the C:\ root

**Comment by benvanik** [comment]
Seems to be a VS bug or something; added README note about not checking out into a path with spaces.
