### ISSUE TITLE
Unable to initialize GL context

### ISSUE THREAD

**Issue by compl3x** [benvanik/xenia#256]
So, after building the solution and attempting to debug, I get the error:

X> (Hex) Unable to initialize GL content

(Hex) has changed at different executions so I don't know how useful it is to debug, but I seem to get these:

**Comment by EverythingTechTime** [comment]
I get that same error

**Comment by Razzile** [comment]
@EverythingTechTime I think i'm right in saying that this is because your graphics card doesn't support Opengl 4.5 (and especially GLSL 4.50)
