### ISSUE TITLE
Modify naming convention for platform-specific files

### ISSUE THREAD

**Issue by SirCmpwn** [benvanik/xenia#262]
Currently we have files like `src/xenia/base/debugger_{win,mac}.cc`.

Instead I propse `src/xenia/base/{win,mac}/debugger.cc`.

Thoughts?

**Comment by benvanik** [comment]
The _suffix naming style is in the [style guide](https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#File_Names), and consistent for other uses. Keeping the code together side-by-side instead of hiding down in other directories makes it easier for people to keep it in sync.

**Comment by SirCmpwn** [comment]
Gotcha. I'll deal with it a different way.
