### ISSUE TITLE
Original Xbox emulation:

### ISSUE THREAD

**Issue by Hydro5** [benvanik/xenia#276]
The 360 had an original xbox emulator. Would Xenia ever be able to reverse engineer that emulator and thus jump-start emulation of the original xbox?

**Comment by yorkiesandskittles** [comment]
Even if it were possible, it isn't a priority right now. The 360's Xbox
emulator isn't great, anyway.

**Comment by Razzile** [comment]
It may be possible, but I don't think the devs here are planning on doing an original xbox emulator as well.

**Comment by Jan4V** [comment]
if you can emulate the 360 you can emulate xbox emulation, there shoud be
no diffirence

2015-06-23 9:11 GMT+02:00 Razzile <notifications@github.com>:

**Comment by PatrickvL** [comment]
Even if this would would, it would be unbearably slow, since you would be running two layers of emulation : host CPU emulating the Xbox360 CPU, emulating the Xbox1 CPU. I *am* interested however, in how the Xbox360 emulates the NV2A GPU...

**Comment by benvanik** [comment]
Yeah, way out of scope for this project. They're likely using a lot of quirks of the system to achieve good performance and GPU compatibility that would require a lot of work to get correct and fast here.
