### ISSUE TITLE
MmQueryStatistics needs proper implementation

### ISSUE THREAD

**Issue by raven02** [benvanik/xenia#278]
available_pages set to 0x00013300 prevents Dragon Ball Z Raging Blast 1/2 from startup up .

**Comment by raven02** [comment]
@gibbed , i'm new to xenia here .Just wonder how to gather information that may help you in this case?

**Comment by gibbed** [comment]
This value was reduced to 0x00013300 to get the Ace Combat 6 demo booting further (it was trying to allocate too much based on the previous value).

**Comment by gibbed** [comment]
What kind of behavior is it causing Raging Blast/2 to exhibit with 0x13300?

**Comment by raven02** [comment]
When i press debug , it basically show nothing about where it dies in VS 2015

![debug](https://cloud.githubusercontent.com/assets/3000282/8313577/7ff53422-1998-11e5-848b-7af4be21fbb2.jpg)

**Comment by raven02** [comment]
It crashed immediate when startup

**Comment by raven02** [comment]
Looks like original xbox also has this function used

https://github.com/Echelon9/cxbx-shogun/blob/08b11f6e14ff9bdf935dbd2472c875866b7cd9b5/src/CxbxKrnl/EmuKrnl.cpp#L2496

**Comment by raven02** [comment]
Red Dead Redemption is also verifying this value in order to bootup

**Comment by SakataGintokiYT** [comment]
@gibbed  FiX Dragon Ball Raging Blast 1/2
