### ISSUE TITLE
X> 0930 Unable to setup command processor GL state

### ISSUE THREAD

**Issue by dimixar** [benvanik/xenia#282]
I get this error whenever I start up xenia.
![2015-06-25_10-24-35](https://cloud.githubusercontent.com/assets/759656/8349315/70971bca-1b24-11e5-9cfb-cec5e8897126.png)

I'm on a lenovo notebook with Nvidia GT 740m card.

**Comment by Razzile** [comment]
You need a GPU that supports OpenGL 4.5. the 740m only supports 4.4.

**Comment by dimixar** [comment]
Ohh, you're right. It supports only some extensions of OGL 4.5. And the missing part is the shading language version.
![2015-06-25_11-20-33](https://cloud.githubusercontent.com/assets/759656/8350247/51d1f27a-1b2c-11e5-8810-9ef7c13f5f24.png)

**Comment by MWFIAE** [comment]
I get this error:
X> 0D90 Unable to setup command processor GL state
![image](https://cloud.githubusercontent.com/assets/6072971/9447395/68a8a648-4a97-11e5-8cc5-7364ae6a186e.png)
Graphic Card is a GTX 770:
![image](https://cloud.githubusercontent.com/assets/6072971/9447415/864b8fd0-4a97-11e5-9bd9-d6c4d8640450.png)

Any ideas?
