### ISSUE TITLE
Add check for extensions (like glGetTextureHandleARB)

### ISSUE THREAD

**Issue by Blackbird88** [benvanik/xenia#289]
Everything builds fine, but after starting up the project it crashes and debugger is stuck on this line

`font_handle_ = glGetTextureHandleARB(font_texture_);`

I have no idea what's wrong. I have everything up-to date AFAIK.
Intel Core i7-3770S (AVX capable)
Nvidia GTX 580 (353.30)
W8.1 Pro x64 (All recommended updates)

Installed:
DirectX Redist (obviously)
VS 2015 Community RC
VC++ 2015 Redist (Both x86/x64)

**Comment by Razzile** [comment]
xenia requires OpenGL 4.5, apparently the GTX 580 only supports up to 4.2. Not sure if that's the cause of your problem but if not then you will experience more issues if this one gets fixed.

**Comment by Blackbird88** [comment]
Well that's weird. It says that I have full 4.4/4.5 support. Might be false then :/

**Comment by Razzile** [comment]
try using [this tool](http://www.realtech-vr.com/glview/) to check if you have full OpenGL 4.5 support.

**Comment by Blackbird88** [comment]
I actually did use that tool. It seems I missed that Shading language 4.50 is in Unsupported.

**Comment by Razzile** [comment]
Hmm weird. It says that's not supported for me either but xenia works completely fine for me. I am no openGL expert so I would wait for some input from the developers of xenia.

**Comment by benvanik** [comment]
Odd, as that should be there. I'll add a check for the extension and error out more elegantly.

**Comment by Blackbird88** [comment]
So is my GPU not sufficient ie. missing that particular extension?

**Comment by benvanik** [comment]
@Blackbird88 correct, you need https://www.opengl.org/registry/specs/ARB/bindless_texture.txt (this particular use is the first time it's called, but later on it's used for all textures in the GPU core)

**Comment by Blackbird88** [comment]
So which GPUs are minimum then? Obvious the requirement just bot bumped higher.

**Comment by benvanik** [comment]
@Blackbird88 anything that supports the full set of core GL 4.5 and the extensions currently used. I'll gather a list of them and show a better error message, but I don't know which GPUs or drivers will support them (all I know is my GTX 980 with the latest drivers work).

**Comment by Blackbird88** [comment]
Alright then thanks! So it seems D3D12 GPUs are safe bet anyway.

**Comment by benvanik** [comment]
Yeah, anything claiming D3D12 support should work (assuming the drivers support everything - I know nvidia's do, but am not sure about the status of AMD cards).
