### ISSUE TITLE
Implement vcmpbfp

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#303]
Many unreal games seem to use it.

**Comment by fuhuan416** [comment]
How to know that? The unreal game use it?

**Comment by raven02** [comment]
It shouldn't be already implemented here ?

https://github.com/benvanik/xenia/blob/master/src/xenia/cpu/frontend/ppc_emit_altivec.cc#L581

**Comment by gibbed** [comment]
He probably meant "vcmpbfp.".

**Comment by raven02** [comment]
I see. the rc condition .

**Comment by benvanik** [comment]
The if (rc) { case isn't implemented, and that's what these games are
hitting. This isn't too hard (I believe e.IsFalse(v) will do the 'v==0'
test and StoreCRField will store the result), but needs some tests and such
to make sure it's right.

**Comment by raven02** [comment]
So bad i don't have any unreal game to test it .

**Comment by benvanik** [comment]
Unit tests! :)

**Comment by raven02** [comment]
Regarding unreal game engine , it used in I'm Alive . 

In debug mode , ocassically the unreal logo show color but with no movie , it is pretty strange.

![unreal](https://cloud.githubusercontent.com/assets/3000282/8635475/595c2c86-2856-11e5-83c0-32693d139ba8.jpg)


In release mode , it always show logo in grey color but with movie playback
