### ISSUE TITLE
Error opengl 4.5

### ISSUE THREAD

**Issue by supneo** [benvanik/xenia#309]
Error in opengl , opengl 4.5 need to run xenia but im installed drivers suported 4.5 , xenia works in previous buils but in new builds same error :  

X> 1440 OpenGL GLSL version 4.50 is required.

Errors in opengl version detection?.

**Comment by Blaypeg** [comment]
Can you say what your graphics card is and what drivers you have installed?

**Comment by supneo** [comment]
Yes , AMD R9 280X , Drivers 15.15 , in old builds works in new same error.

**Comment by benvanik** [comment]
Use [GPU Caps Viewer](http://www.geeks3d.com/20150626/gpu-caps-viewer-1-24-0-released/) to check your GLSL version. Unless your version reads as 4.50 it is unsupported. If it does read something like 4.50, there may be an error in the detection that needs to be fixed, so paste the value you are seeing.

**Comment by supneo** [comment]
Oks , my driver is support opengl 4.5.13394 but my GLSL is 4.40 , sorry for the inconvenience , it seems that we can not test AMD in a long season , greetings .

**Comment by benvanik** [comment]
No worries. I'll add more information to the error message. Hopefully AMD will get their shit together and release a new driver soon!

**Comment by Kurdischerjapaner1** [comment]
ben vanik can you please fix star ocean the last hope ? and my graphic card is suportet open GL 4.5 but not open GLSL 4.5 only 4.40.can i start the Game anyway? I have AMD 7660HD quad core 3.8GHZ 8GB Ram DDR3

**Comment by Goyal99** [comment]
Xenia error
Openly 4.5 arb bindless texture is required
What should I do

**Comment by oscarbg** [comment]
Hi,
just tried to launch Xenia in OpenGL 4.5 mode with lntel HD 530 graphics which with latest drivers (15.60) and for a while support OpenGL 4.5.. any way crashes saying driver doesn't support OpenGL 4.5..
is because of arb_bindless_texture?
thanks..

**Comment by shadowbrony33** [comment]
@oscarbg Intel iGPUs are notorious for horrible graphics drivers and probably doesn't support some of the features in GL 4.5, you'd be better of getting a dedicated GPU if you are using a Desktop.
