### ISSUE TITLE
OpenGL Weird Issue Bug

### ISSUE THREAD

**Issue by GamingDamned** [benvanik/xenia#320]
http://u.cubeupload.com/GamingDamned/Error.png

It was working fine and then restarted windows this happened and tried installing drivers again and nothing. I'm 100% sure this is a bug and not sure how to fix this to continue testing games.

**Comment by Bugster** [comment]
AMD cards don't support GL 4.5 just yet, the next Catalyst update should add support though according to the footnotes of [this page](http://www.amd.com/en-us/products/graphics/desktop/r9#) (at the bottom open the footnote section and read footnote 8. "OpenGL® 4.5 support available in AMD Catalyst™ 15.30 WHQL driver")

**Comment by GamingDamned** [comment]
But it worked before. How is it now it doesn't?

**Comment by hlide** [comment]
That's because there is probably an added "lazy" test which is fatal with your version. That test is just looking a string with "4.5", not if your graphics card implements all the needed features. I guess this fatal check might have been a warning like "Your graphics card may not fully comply with the requested Open GL 4.5 features needed by Xenia. Run it at your own risk and do not complain with an issue bug at GitHub!"

**Comment by GamingDamned** [comment]
I wasn't complaining. But any way to bypass it? I understand they haven't added this yet. But i got a R9 295X2 and i know this is WIP.

**Comment by hlide** [comment]
Don't worry - I was not targetting you specifically with "complaining" but the hordes of knuckle-dragging grunts who might  be attempted to do so if someone is releasing Xenia binary one day. 

To answer your question, you must comment the code lines checking the presence of "4.5". Unless someone decides to change the fatal code into a warning to let the emulator continue.

**Comment by GamingDamned** [comment]
I see i'm a dev mainly have no time to mess with code. Just want to help test few games with spare time to help this project. I got barely any time. If you can tell me the easiest way or compile for me i be grateful. Later this month should have plenty of time off.

**Comment by hlide** [comment]
https://github.com/benvanik/xenia/commit/3cac71322ce32b2908dcb501aa5c05ede7b94e7a

Just comment the *if* clause and its body.

**Comment by GamingDamned** [comment]
Ah looks easy. I hope i can compile after lol. I rarely touch coding in my type of work. If works maybe i can contribute to those who having same issue and publishes patches until this gets sorted in driver.

**Comment by GamingDamned** [comment]
Just tired it. I'm terrible at visual studio. I already put the comment on it. Just need help compiling this.

**Comment by hlide** [comment]
did you follow the QuickStart in README.md?

**Comment by woody2014** [comment]
I also would like a fix for this but I am no dev.

**Comment by Quantum2** [comment]
Just comment the check line

2015-07-04 12:03 GMT+01:00 woody2014 <notifications@github.com>:

> I also would like a fix for this but I am no dev.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benvanik/xenia/issues/320#issuecomment-118500536>.
>



-- 
Rafael Francisco

**Comment by GamingDamned** [comment]
@hlide 
Yes i tired that. It's confusing.

**Comment by hlide** [comment]
I cannot help you more. Once you follow this guide then open vs2015 (xb edit), you need to comment the offending lines if not already done and click on Build. It should be enough to get your binary.

**Comment by GamingDamned** [comment]
@hlide 
I finally figured it out but now i'm stuck on xb part. You need to mention better steps on how to do this. It didn't say i had to download github thing and then use powershell command thing. Just a tip for those who want to step into this.

http://u.cubeupload.com/GamingDamned/xberror.png

Please help me i'm so much closer compiling this.

**Comment by GamingDamned** [comment]
@hlide

**Comment by GamingDamned** [comment]
Whoops for closing was on mobile. Still need your help @hlide

**Comment by hlide** [comment]
I am not an active contributer on Xenia and I think there have been some changes since the last time I built Xenia. So I cannot be that helpful if there are some new steps I am unaware of.

**Comment by woody2014** [comment]
change default shell to cmd

**Comment by Razzile** [comment]
@woody2014 I think xb.bat needs to run through the "Developer Command Prompt" that comes with visual studio now.
![Image](http://i.imgur.com/kPJxP8Y.png)

**Comment by woody2014** [comment]
Having variable path issues

**Comment by GamingDamned** [comment]
@woody2014 
I tired that.

@Razzile 
I tired this and this my error without doing Github powershell:
http://u.cubeupload.com/GamingDamned/cmdissuewithoutgithu.png
WIth github powershell it didn't say this error. This is why i need clearer steps. The steps doesn't seem to help much. Hope you can help me out.

**Comment by woody2014** [comment]
finally got everything working but latest master build does not have /gl_context.cc

**Comment by Nezarn** [comment]
@GamingDamned cmder sucks since some versions ago, they literally deleted 90% of the builtin git,

To make it work, just download cmder full version + msysgit https://msysgit.github.io/ and then copy msysgit files into cmder\vendor\msysgit\ and xb setup will work.

**Comment by GamingDamned** [comment]
@Nezarn 
I've got them now but now how do i fix this error:
http://u.cubeupload.com/GamingDamned/someerror.png

**Comment by hlide** [comment]
FYI, https://github.com/benvanik/xenia/commit/8c0614b2025c8d5c4d819510ad67c9e1e25a0a5b#commitcomment-12036277

**Comment by Nezarn** [comment]
@GamingDamned stop using powershell lol.

**Comment by GamingDamned** [comment]
@Nezarn 
Well it's with the stuff you told me to get. I still need steps here i'm super lost. I manage to fix the error but now still need to figure it out.

@hlide 
I'm aware of that.

**Comment by benvanik** [comment]
@GamingDamned this is not a support channel, this is a developer issue tracking list. This project is not even close to alpha-stage, and is not meant for use by those who are not developers or cannot self-sufficiently poke around.
