### ISSUE TITLE
Xbox360 Hardware Documentation

### ISSUE THREAD

**Issue by ADormant** [benvanik/xenia#327]
I know it wouldn't be a trivial amount of work but could you consider writing a Xbox360 hardware documentation like the ones available for the PS1, GBA and DS? I think it would be very helpful for all potential contributors and also for hardware preservation.
 I am talking about something like this
https://github.com/simias/psx-guide/blob/master/guide.tex
https://svkt.org/~simias/guide.pdf
http://problemkaputt.de/psx-spx.htm
http://problemkaputt.de/gbatek.htm

**Comment by vgturtle127** [comment]
http://free60.org/wiki/Main_Page
http://dev360.wikia.com/wiki/XBox360_Homebrew_Development_Wiki

Those might be good places to start. Also, you can look at the Wikipedia page for the Xbox 360.

I'm not sure this is related to this project, though. @benvanik might have some ideas or thoughts he may want to share though.

**Comment by benvanik** [comment]
The hardware is severely underdocumented :(
Many of the low level systems are total black boxes, and most of the reverse engineering I've been doing has been at the kernel interface level. I have no idea how the HAL works (I'm assuming some black magic). The big areas useful to document are around the CPU diffs from the normal PPC stuff and the shader microcode/GPU command list diffs from Ardreno. Those are probably useful only to people looking to either contribute to the emulator or write their own, and may be best served as comments in the code.
