### ISSUE TITLE
Stop running when read newly created system file

### ISSUE THREAD

**Issue by raven02** [benvanik/xenia#329]
This happen in Raiden IV .When run for first time , system file createD but when re-run the game , it then stop running when read this newly created system file.

content\4D4F07D1\00000001\RAIDEN4-SETTING

Possbily happen in other games i believe

**Comment by benvanik** [comment]
This may be fixed now. Can you retest?

**Comment by raven02** [comment]
Let me compile tonight and try out again .

**Comment by raven02** [comment]
@benvanik , it still stopped after 'press start button'. 

If u want to test some code changes against this , let me know.

**Comment by raven02** [comment]
This one works okay now .Closed
