### ISSUE TITLE
Byteswapping on texture format 565 

### ISSUE THREAD

**Issue by raven02** [benvanik/xenia#331]
565 texture format seems to get wrong color and may need byteswapping

![naruto](https://cloud.githubusercontent.com/assets/3000282/8598910/115fd878-2690-11e5-8eab-75028348a2ab.jpg)

However , when i tried to do byteswapping ,still not color correct .Probably other thing else?

    if (config.texture_format == TextureFormat::k_5_6_5)
    {
	  glPixelStorei(GL_UNPACK_SWAP_BYTES, GL_TRUE);
     }

    glTextureSubImage2D(texture, 0, 0, 0, texture_info.size_2d.output_width,
                        texture_info.size_2d.output_height, config.format,
                        config.type, reinterpret_cast<void*>(unpack_offset));

    if (config.texture_format == TextureFormat::k_5_6_5)
    {
	   glPixelStorei(GL_UNPACK_SWAP_BYTES, GL_FALSE);
    }

**Comment by benvanik** [comment]
Try doing `GL_UNSIGNED_SHORT_5_6_5_REV` in the texture format table instead of `GL_UNSIGNED_SHORT_5_6_5` as it is now. That's probably the best.
Alternatively, you could try messing with the swizzle map - look for `GL_TEXTURE_SWIZZLE_R` and hardcode those to what you think they are to see if it's the case.

**Comment by raven02** [comment]
Yep, i'm testing the REV right now and the game is running very slow

{TextureFormat::k_5_6_5, GL_RGB565, GL_RGB, GL_UNSIGNED_SHORT_5_6_5_REV},

**Comment by raven02** [comment]
Probably byteswapping should apply for 1555 as well though i don't have any game to test it .

**Comment by raven02** [comment]
Thanks fixed
