### ISSUE TITLE
Null pointer execution in GLProfilerDisplay::SetupFont

### ISSUE THREAD

**Issue by mojobojo** [benvanik/xenia#342]
In GLProfilerDisplay::SetupFont, gl_profiler_display.cc line 238 when it executes glMakeTextureHandleResidentARB(font_handle_) somewhere in there it tries to execute a null pointer. I am not too experienced with OpenGL otherwise I would have debugged this further. 

Some info on what I am running it on.
CPU: AMD FX 8350
GPU: ATI Radeon HS 6990 (Just literally got an update allowing OpenGL 4.5 so I could run Xenia)
Memory: 16GBytes DDR3

**Comment by benvanik** [comment]
You likely don't have support for bindless textures on that card.

**Comment by mojobojo** [comment]
Ah darn, thanks.

**Comment by benvanik** [comment]
I thought I was checking for this, but it may have broke with the latest changes. I'll make sure it's throwing up the proper error dialog tonight. Thanks for reporting!

**Comment by benvanik** [comment]
Odd - the check seems to be happening. Can you use [this](http://www.geeks3d.com/20150626/gpu-caps-viewer-1-24-0-released/) to see if on the OpenGL tab you have `GL_ARB_bindless_texture`? If so, and you are hitting this null pointer error there, it may mean AMD has messed something up :/

**Comment by mojobojo** [comment]
I do not have GL_ARB_bindless_texture

**Comment by benvanik** [comment]
Weird. I added another check, so hopefully it'll at least throw up the right error now. Thanks!
