### ISSUE TITLE
Error whilst running xenia in Visual Studio

### ISSUE THREAD

**Issue by haza1608** [benvanik/xenia#343]
Hi, whenever I click Local Windows Debugger to start xenia it says there is an error
(this is the output)

'xenia.exe' (Win32): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Xenia\Xenia\xenia\build\bin\Debug\xenia.exe'. Symbols loaded.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\nsi.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\wsock32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\XAudio2_8.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\XInput1_4.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10122.0_none_8477cf5a5cc8827c\comctl32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\ddraw.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\dciman32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\XAudio2_9.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Unloaded 'C:\Windows\System32\ucrtbase.dll'
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\avrt.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Program Files (x86)\AVG\AVG2015\avghooka.dll'. Cannot find or open the PDB file.
The thread 0x2628 has exited with code 0 (0x0).
The thread 0x268c has exited with code 0 (0x0).
The thread 0x2604 has exited with code 0 (0x0).
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\ig7icd64.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\igdusc64.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\wtsapi32.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Cannot find or open the PDB file.
'xenia.exe' (Win32): Unloaded 'C:\Windows\System32\version.dll'
The thread 0x25a8 has exited with code 0 (0x0).
The thread 0x2788 has exited with code 0 (0x0).
The thread 0x3d0 has exited with code 0 (0x0).
The thread 0x24cc has exited with code 0 (0x0).
Exception thrown at 0x00007FF6131B728D in xenia.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FF6131B728D in xenia.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Exception thrown at 0x00007FF6131B728D in xenia.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FF6131B728D in xenia.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Exception thrown at 0x00007FF6131B728D in xenia.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FF6131B728D in xenia.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

The program '[3508] xenia.exe' has exited with code 0 (0x0).

![image](https://cloud.githubusercontent.com/assets/5788953/8663370/fc24f760-29c1-11e5-9b14-e5cfeba7da62.png)

**Comment by benvanik** [comment]
This happens. Need more info to diagnose or do anything actionable (does this happen with other games, where is it dying (callstack, etc), what's the call history leading up to the crash, etc).
