### ISSUE TITLE
Problem compilation

### ISSUE THREAD

**Issue by Zangetsu38** [benvanik/xenia#355]
@benvanik  Why have removed the .sln file?
We can not now compiled.*
Why not use Cmake, which is known and simple to use, the premake I absolutely understand.

**Comment by benvanik** [comment]
Premake is used to generate the sln. Use 'xb premake' to generate it.

**Comment by Zangetsu38** [comment]
Not works I have a error 
![capture d ecran 2015-07-19 17 08 04](https://cloud.githubusercontent.com/assets/5261759/8766456/bd577b36-2e38-11e5-9195-76c846158efc.png)

**Comment by benvanik** [comment]
May be an issue with the vcvars stuff. Run from the Visual Studio developer
command prompt.

**Comment by Zangetsu38** [comment]
hm ok, now its wortks, but very not simple to use, cmake more simple

**Comment by hlide** [comment]
@Zangetsu38 allons un petit effort en anglais... et arrête de demander avec CMake si tu tiens à ta tête (la guillotine pourrait ne pas être très loin si tu persistes).

**Comment by Zangetsu38** [comment]
@hlide eu ? il faudrait que tu m'explique en quoi parlé de Cmake est si mal Citra s'en sert bien et ça fonctionne bien et c'est simple a utilisé.

**Comment by hlide** [comment]
@Zangetsu38 read this [FAQ](http://xenia.jp/faq/#why-did-you-do-x-why-not-just-use-y-you-should-use-y-nih-nih-nih). This is not about whether CMake is good or not, it is about choice.

**Comment by benvanik** [comment]
Thanks for clarifying @hlide.

@Zangetsu38 cmake and premake are identical in this case - you'd have been confused either way.

**Comment by Zangetsu38** [comment]
Yes to generate the same project and solution, but not in terms of practice and usability, that's all I said :)

**Comment by hlide** [comment]
@Zangetsu38

> des goûts et des couleurs, on ne discute pas
