### ISSUE TITLE
command_processor.cc - Assertion after ExecutePacketType3_WAIT_REG_MEM()

### ISSUE THREAD

**Issue by Kraust** [benvanik/xenia#360]
**Note:** This may be a compatibility issue with AMD GPUs but I still feel the need to report it, well aware of AMD's "spotty" OGL compatibility.

GPU: R9 270x
Drivers: Catalyst 15.7

Game: Tales of Vesperia - 4E4D07E9 (I think this is correct)
Assertion: 
![image](https://cloud.githubusercontent.com/assets/6548135/8815726/0f037a58-2feb-11e5-9685-f1be67a30a1e.png)

Program asserts after a WAIT_REG_MEM instruction. 

Log (OneDrive, couldn't think of a better place to put this)
https://onedrive.live.com/redir?resid=411CFB97ECDAC245!397&authkey=!AKayFxgIDPTgZx0&ithint=file%2ctxt

And a youtube video because why the hell not?
https://www.youtube.com/watch?v=YCB7kDJi08Y

**Comment by benvanik** [comment]
This is probably an unrecognized or mishandled GPU command buffer opcode. Would be useful to file this on the [game-compatability issue tracker](https://github.com/xenia-project/game-compatibility/issues).
