### ISSUE TITLE
Persona 4 Arena Ultimax XMA Crash

### ISSUE THREAD

**Issue by EIREXE** [benvanik/xenia#373]
@DrChat discovered that the reason why persona 4 arena crashes before loading the main menu is related to XMA, now, in earlier versions of the emulator, more exactly 6348c3d this didn't happen.

The game randomly either crashes the emulator or it gets a hang just before rendering the main menu loading screen, this doesn't seem to be related to the menu's graphics, as pointed out by DrChat and the fact that randomly you can get to see the main menu, just to crash seconds after, the crash has been confirmed to be related to XMA, but the hang hasn't, so it's still up to be checked in that sense.

Here's the log from a crash:
https://dl.dropboxusercontent.com/u/88583340/Xenia%20Logs/453907D2%20-%20Persona%204%20Arena%20Ultimax.txt

And this is the hang:
https://dl.dropboxusercontent.com/u/88583340/Xenia%20Logs/453907D2%20-%20Persona%204%20Arena%20Ultimax%20-%20Hang.txt

**Comment by raven02** [comment]
Probably latest build fixed the issue and i reach 

![persona1](https://cloud.githubusercontent.com/assets/3000282/8978005/c324fa34-36d0-11e5-882d-1964c701e2cd.jpg)


![persona](https://cloud.githubusercontent.com/assets/3000282/8977985/9f0b706a-36d0-11e5-857c-715e6b85e7cd.jpg)

**Comment by EIREXE** [comment]
It runs now.
