### ISSUE TITLE
Insufficient memory space on selected device

### ISSUE THREAD

**Issue by raven02** [benvanik/xenia#377]
It popup "Insufficient memory space on selected device" in Raiden IV since commit @DrChat 

https://github.com/benvanik/xenia/commit/9b722eb6026222443e9f8ca32924736fa257dddf

**Comment by raven02** [comment]
1T should be  1024 * 1024 * 1024 * 1024ull ?

**Comment by raven02** [comment]
Strange that reducing from 1TB to 1GB , it works again.

**Comment by benvanik** [comment]
My guess is 1TB is too much - way larger than any microsoft harddrive - and some games may be assuming the number is below some limit (and storing in a smaller data type/etc). There's no reason to claim 1TB.

**Comment by Nukem9** [comment]
It sounds like some kind of integer overflow, why not just use the default 250GB for most consoles?

**Comment by DrChat** [comment]
I guess so, but that's rather silly of the developers if they do cause the declaration is for a QWORD.

I guess we can just change it to 128GB, I boosted it cause I thought 1GB was not enough.

**Comment by benvanik** [comment]
I've learned not to underestimate game developer code quality ;)

**Comment by hlide** [comment]
no wonder, the type *int* is still used quite prominently instead of *intptr_t* so you may expect that kind of issue, especially when the game is meant to be ported in both 32-bit and 64-bit platforms (console or pc).

**Comment by raven02** [comment]
Possibly integer overflow ? as it still doesn't work even with reduced size 128G

**Comment by hlide** [comment]
4 GB is the max for a *unsigned int* (DWORD), any coincidence here ?

**Comment by gibbed** [comment]
I'm pretty sure the maximum HDD size offered in retail is 320 GB, so that's a bit strange.

**Comment by DrChat** [comment]
https://github.com/LestaD/SourceEngine2007/blob/master/se2007/engine/xboxsystem.cpp#L482

Looks like I was mistaken, the device free size is an unsigned long.

**Comment by DrChat** [comment]
https://github.com/LestaD/SourceEngine2007/blob/master/se2007/engine/xboxsystem.cpp#L482

Source uses the output as an unsigned qword, so this is odd.

**Comment by hlide** [comment]
Those devices are not like cartridges? virtual ones in a hard disk?

**Comment by hlide** [comment]
Or XDEVICE_DATA may have a second field for the high part of free bytes for devices of higher capacity. Microsoft has a long history of pair of fields for those things.

**Comment by DrChat** [comment]
Yeah, but it still wouldn't make sense though cause games are loading from the free bytes with a native "ld" instruction.

**Comment by raven02** [comment]
Possibly only this stupid game do it .Or probably we can keep it as 1G unless we seen other games that really need extra storage .My two cents.

**Comment by DrChat** [comment]
Could just set it to 0xFFFF... and everyone'll be happy!

**Comment by raven02** [comment]
Heehee 0xFFFFFFFF
