### ISSUE TITLE
page_count can exceed page_number in memory.cc

### ISSUE THREAD

**Issue by karalaine** [benvanik/xenia#380]
I ran into issue when booting up Lego Harry Potter. 
In memory.cc:653
low_address = 0
high_address = 536870911
size = 294649856
alignment = 65536

page_count: 71936
page_number: 64688
base_page_number rolls over as its assigned signed value and causes crash.

Callstack:

>   xenia.exe!xe::BaseHeap::AllocRange(unsigned int low_address, unsigned int high_address, unsigned int size, unsigned int alignment, unsigned int allocation_type, unsigned int protect, bool top_down, unsigned int \* out_address) Line 653  C++
>     xenia.exe!xe::PhysicalHeap::AllocRange(unsigned int low_address, unsigned int high_address, unsigned int size, unsigned int alignment, unsigned int allocation_type, unsigned int protect, bool top_down, unsigned int \* out_address) Line 1079 C++
>     xenia.exe!xe::kernel::MmAllocatePhysicalMemoryEx_shim(xe::cpu::frontend::PPCContext_s \* ppc_context, xe::kernel::KernelState \* kernel_state) Line 319   C++

**Comment by sephiroth99** [comment]
What version (git revision) are you using? Commit  510a8e5 should have fixed that...

**Comment by karalaine** [comment]
This was latest from master at the time, 14beb27ebc3a18defc82089e1599b4ebe7a910cd
Fix in 510a8e59cf364d0588442782f8736fe6707fc18e doesnt apply here since low page number is 0 and high page number 131056. 
So the problem is:
It goes top down the requested range starting from 131056 - 71936 = 59120.
It finds used page at 64688.
Now, what to do in case when there was no enough room in the left area? 
Clearly requested range can fit in only once so I think it should just jump out of the loop and give up.
