### ISSUE TITLE
How do I launch xenia?

### ISSUE THREAD

**Issue by xmicro** [benvanik/xenia#383]
I have everything installed and did all the commands. Now what?

**Comment by Razzile** [comment]
If you can't figure that out, are you sure you should be using xenia while it is in pre-alpha?

go to xenia directory, then build > bin > Windows > Debug (or Release if you built in release mode) > xenia.exe

**Comment by benvanik** [comment]
This issue tracker is for bugs, not techincal support. Stop spamming or you will be blocked.
