### ISSUE TITLE
the Kernel Version is not correct - could be the reason for many unplayable games

### ISSUE THREAD

**Issue by pharrowboy** [benvanik/xenia#387]
xbox 360 requires a valid kernel for it to run games, i was able to launch a homebrew app called DashLaunch that would install a custom dashboard but it tells me the current kernel version is unsupported. being kernel 2.65535.65535.3 might very well cause a few games not to load correctly. fixing the kernel version so that its the same as an xbox 360 might be helpful.

**Comment by pharrowboy** [comment]
![kernel](https://cloud.githubusercontent.com/assets/11796091/9291009/a531f972-4365-11e5-99b0-cdbbeb20188d.png)
heres a picture.

**Comment by gibbed** [comment]
While it's true the Kernel version specified by Xenia isn't exactly correct, I have yet to see a single game that checks the Kernel version.

**Comment by Quantum2** [comment]
I could not run a lot of my games on my RGH due to the kernel version being
too old, I had to update the dashboard or just give up, not sure if the
game itself performs any checks or if it was a dashboard function

2015-08-15 22:59 GMT+01:00 Rick Gibbed <notifications@github.com>:

> While it's true the Kernel version specified by Xenia isn't exactly
> correct, I have yet to see a single game that checks the Kernel version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benvanik/xenia/issues/387#issuecomment-131455875>.
>



-- 
Rafael Francisco

**Comment by pharrowboy** [comment]
alot of games prompt for you to update if youre not on a supported kernel by the game. there is a minimum but no maximum, but if you read the kernel number i listed, the format is incorrect: example: >>> 2.0.17349.0 is the proper format. not 2.65535.65535.3. if you look at all the kernel versions of the past https://en.wikipedia.org/wiki/Xbox_360_system_software, 

2.0.xxxxxx.0   <<< proper format

**Comment by gibbed** [comment]
That sounds like a mechanic of the dashboard, and not the game. If you have an example game that does this, please let us know.

**Comment by pharrowboy** [comment]
If you google it people on the internet say their xbox 360 cant run a new release game without updating. 
http://www.ixtreme.net/ixtreme-lt-lite-touch-firmware-phat-support/31241-playing-new-games-old-dashboard.html

The way xenia is coded there is no dashboard. Games require a minimum dashboard number/kernel version in order to run. But when i tried installing a homebrew dash it said the kernel had the wrong version. So if you put the pieces together fixing the kernel version to follow suit of the console would be wise not just for game compatibility but it would make the emulator more realistically closer to an xbox 360

**Comment by hlide** [comment]
or maybe the dashboard is considering each component as a *short* and so 2.65535.65535.3 will have be interpreted as 2.-1.-1.3 and the short comparison will fail for -1 of course. So many hypotheses...

**Comment by elfogames** [comment]
I guess that isn't the Problem
![nooo](https://cloud.githubusercontent.com/assets/16784631/15991679/5af89d70-3090-11e6-8c92-7f56751b08d1.jpg)
