### ISSUE TITLE
Contributing.

### ISSUE THREAD

**Issue by Snowlav** [benvanik/xenia#390]
Hey everyone, awesome progress I just got notice of this project via Reddit!

I was wondering why you guys aren't doing a kickstarter or maybe accept donations to help / speed up the progress!

Besides myself I am sure there lot's of people out there willing to contribute to this project.

**Comment by Razzile** [comment]
I can't speak for the developers of the project but I don't think donations have been needed for this project. I think benvanik and the others are working on Xenia purely for fun and educational purposes.

**Comment by jzelinskie** [comment]
Is there a design doc and high level overview of the project and goals/milestones located anywhere to help other developers get on the same page and make some meaningful contributions?

**Comment by Razzile** [comment]
@jzelinskie http://xenia.jp/http://xenia.jp/roadmap/ http://xenia.jp/faq/ as well as the docs in the repo are a good place to start.

**Comment by rlabrecque** [comment]
Yeah those are good placces, The best place to start though is to just rip a couple games, try them out, and then identify some issues that you could look into fixing.

All games have at least some sort of issue.
