### ISSUE TITLE
X> 09D0 Unable to setup command processor GL state

### ISSUE THREAD

**Issue by MWFIAE** [benvanik/xenia#401]
I get this error:
X> 0D90 Unable to setup command processor GL state
![image](https://cloud.githubusercontent.com/assets/6072971/9447874/da0778f8-4a99-11e5-8e0c-2485f64c6fda.png)

Graphic Card is a GTX 770:
![image](https://cloud.githubusercontent.com/assets/6072971/9447877/dda58748-4a99-11e5-9c3a-77ae92a7905d.png)

Any ideas?

I commented on a similiar issue, but I thought I should make an extra one
https://github.com/benvanik/xenia/issues/282#issuecomment-134312184

**Comment by benvanik** [comment]
Try updating your driver. It's 6 months old.

**Comment by MWFIAE** [comment]
Solved it, thanks! :+1:

**Comment by benvanik** [comment]
Awesome. I may try to put in a driver version check of some kind to warn about this.

**Comment by MWFIAE** [comment]
Would have prevented this issue :+1: 

Do you know why the old driver didn't work?
I mean OpenGL 4.5 was supported and it was the only thing mentioned as required for the gpu, so it should have worked, right?

Other things that have changed are OpenCL and PhysX, something to do with that?
![image](https://cloud.githubusercontent.com/assets/6072971/9473786/0c6f66ca-4b5d-11e5-84e2-2399ac80f374.png)

**Comment by benvanik** [comment]
It's likely one or more of the required extensions (not part of core OpenGL
4.5) were not yet implemented in those drivers.
