### ISSUE TITLE
Red/blue channels swapped in Banjo Kazooie HD

### ISSUE THREAD

**Issue by crwcomposer** [benvanik/xenia#402]
As seen in this reddit post:

https://www.reddit.com/r/emulation/comments/3i77ki/banjo_kazooie_hd_playable_on_xenia/

Color issue identified and demonstrated in this comment:

https://www.reddit.com/r/emulation/comments/3i77ki/banjo_kazooie_hd_playable_on_xenia/cue39cr

**Comment by gibbed** [comment]
Yeah, known issue with Banjo Kazooie. Suspected issues with render to texture.

**Comment by TranzRail** [comment]
I found that if you set the internal_format var to GL_RGB8 you get the correct colour profile, but then there's an issue with the alpha channel. The game loads using "k_8_8_8_8" as the ColorRenderTargetFormat. Perhaps we just need to keep the original arrangement (where it passes to  the GAMMA format) and flip the two colours around? I will keep experimenting (note, I am NOT by any stretch an "expert" when it comes to C/C++ or DirectX).

![banjo-kazooie-color1](https://cloud.githubusercontent.com/assets/1941176/10388772/362ed81c-6ec9-11e5-99b8-287f6f023884.png)

**Comment by raven02** [comment]
Possibly we may do it here

// TODO(benvanik): swap channel ordering on copy_dest_swap
// Can we use GL swizzles for this?

**Comment by raven02** [comment]
This one resolved and can be closed.

**Comment by benvanik** [comment]
:+1:

**Comment by robdhayes** [comment]
No, this issue is not resolved....

**Comment by Margen67** [comment]
It has been with the OpenGL renderer, but not with Vulkan.
https://github.com/benvanik/xenia/issues/578
