### ISSUE TITLE
Python 2.7 must be installed and on PATH:

### ISSUE THREAD

**Issue by Blackbird88** [benvanik/xenia#403]
Except it is. I have no idea what's going on here. It was working fine before :(
![image](https://cloud.githubusercontent.com/assets/4414625/9491018/483be7de-4bec-11e5-9700-7d4d8cde1984.png)
![image](https://cloud.githubusercontent.com/assets/4414625/9491027/5468246e-4bec-11e5-9458-e859e90f687c.png)

**Comment by Razzile** [comment]
i had this exact problem once, but i never figured out how to fix it because i reinstalled windows, and afterwards it was fine.

**Comment by Nezarn** [comment]
If you use xb then why are you in dev command prompt for vs2015? I used xb.bat from normal command prompt and it worked fine.

**Comment by Razzile** [comment]
@Nezarn it was a requirement before, it may not be anymore

**Comment by Blackbird88** [comment]
It happens regardless of what I use.

**Comment by agrecalypse** [comment]
When you say it was working fine before, what has been installed/changed since it last worked correctly?  I see you have the Xenia directory installed on the E: drive.  Is Python installed on the E as well?

Regardless, I'd suggest uninstalling Python.  Then check PATH to see if the Python references have been removed.  If they have not, remove them manually and then reinstall Python (using the option to have it create references in PATH).

**Comment by Blackbird88** [comment]
I forgot to mention I did that already. Uninstalling Python and removing it manually then reinstalling it with PATH checked in installer didn't do anything.
I don't recall doing anything that'd interfere with Path as yo ucan see python command works by itself. It just isn't detected somehow.

**Comment by agrecalypse** [comment]
Out of curiosity, if you install the Xenia directory to your C: drive, do you get the same results?

**Comment by Blackbird88** [comment]
Yes. That makes no difference.

**Comment by Razzile** [comment]
I have xenia on my E: drive and can compile fine with python on C:

**Comment by benvanik** [comment]
Run this on the command line and tell me what the output is:
```
python -c "import sys; print sys.version_info[:2]"
```

**Comment by Blackbird88** [comment]
![image](https://cloud.githubusercontent.com/assets/4414625/9497589/00f4a102-4c16-11e5-9128-ec0638232339.png)

**Comment by benvanik** [comment]
That's.... odd.

Try these:
```
CMD /c where python
echo %ERRORLEVEL%
```
(that should be `C:\Python27\python.exe` or something like it and then print 0)

```
CMD /c python -c "import sys; sys.exit(1 if not sys.version_info[:2] == (2, 7) else 0)"
echo %ERRORLEVEL%
```
(that should print 0)

**Comment by Blackbird88** [comment]
This is odd
![image](https://cloud.githubusercontent.com/assets/4414625/9497728/afd4ba9a-4c16-11e5-89b8-cb9f3ead3772.png)

**Comment by gibbed** [comment]
So the problem is cmd is somehow missing. WTF?

**Comment by agrecalypse** [comment]
Makes me wonder what your windir variable is set to.

**Comment by benvanik** [comment]
Well, that's the problem. I'm not sure how your computer is working at all ;)

Try:
```
where cmd
```
(it should print `C:\Windows\System32\cmd.exe`)

**Comment by Blackbird88** [comment]
'where' is not recognized as an internal or external command,
operable program or batch file.

WTF. I didn't touch eitehr of those.

**Comment by benvanik** [comment]
Hrm, did you replace your entire PATH with *just* the python folders, removing the system folders that were there before?

**Comment by gibbed** [comment]
Is C:\Windows\System32 in your PATH?

**Comment by Blackbird88** [comment]
Nah I only removed the Python paths.
ComSpec links to %SystemRoot%\system32\cmd.exe w/e that is.

**Comment by benvanik** [comment]
Make sure the following two paths are in your system variables `Path` (the lower box):
```
C:\Windows\system32
C:\Windows
```

If they are, I don't know what to tell you. You may have to do a system restore.

**Comment by Blackbird88** [comment]
Yeah that was it. Xenia works now. Something must've corrupted the Path else I have no idea. I wouldn't touch it like that for no reason.

**Comment by Razzile** [comment]
that PATH issue is EXACTLY what I had as well, I never even touched PATH
