### ISSUE TITLE
The program '[14504] xenia.exe' has exited with code 1 (0x1).

### ISSUE THREAD

**Issue by xmicro** [benvanik/xenia#404]
What should I do to launch it?

**Comment by agrecalypse** [comment]
Are you running from within VS?  If so, take a look [here](https://github.com/benvanik/xenia/blob/master/docs/building.md) under Debugging.

Or you can 
  * try running the xenia.exe straight from c:\xenia\build\bin\windows\debug\ and picking your .xex or .iso
  * try running cmd and entering **c:\xenia\build\bin\windows\debug\xenia.exe yourfile.xex > Output.log**

**Comment by xmicro** [comment]
Got it using the former method. Thank you.
