### ISSUE TITLE
Do I need a modded Xbox to rip the .xex or make the .iso, or can I use my PC and my PC's CD Drive?

### ISSUE THREAD

**Issue by xmicro** [benvanik/xenia#405]
Is there any way?

**Comment by agrecalypse** [comment]
There are ways.  A modded Xbox is not needed.  You will need a DVD drive capable of reading Dual Layer DVDs.

**Comment by xmicro** [comment]
My DVD drive supports dual layer. Now what?

**Comment by benvanik** [comment]
This is not the right place for this discussion. Please take it to another forum.
