### ISSUE TITLE
Fatal Error/Crash in Scott Pilgram Vs. The World

### ISSUE THREAD

**Issue by deadair3210** [benvanik/xenia#415]
Game plays almost flawlessley barring the lack of music until after you select your charecter and start the first level on which the emulator crashes. 
![capture](https://cloud.githubusercontent.com/assets/1053504/9650374/87feee9e-51c7-11e5-9e85-ffb718bddca7.PNG)

**Comment by benvanik** [comment]
This is an unimplemented instruction. You can ignore and it'll probably be fine.
