### ISSUE TITLE
Save issue in Scott Pilgram Vs. The World

### ISSUE THREAD

**Issue by deadair3210** [benvanik/xenia#418]
Game reports save as being corrupted every time when you first get to the menu. Wasn't sure if it was a issue that was known or not. I'm guessing that the emulator doesn't set up any sort of storage device yet?

**Comment by Razzile** [comment]
I think this report would be better in https://github.com/xenia-project/game-compatibility/issues :)

**Comment by deadair3210** [comment]
ok, sorry

**Comment by benvanik** [comment]
Yeah, please file on the relevant entry on game-compatibility. If the root issue is identified we can file an issue to fix it here.
