### ISSUE TITLE
Use Datatable for the compatibility list

### ISSUE THREAD

**Issue by Louhike** [benvanik/xenia#419]
Is it an option to use a library like Datatable (dependant on jQuery), to improve the array? I think it will help to add sorting/filtering to the table without reinventing the wheel. It is a widely used plugin, and opensource. I've used it on a project where we threw at it thousand of objects and it worked nicely.

**Comment by benvanik** [comment]
I don't particularly care too much, so long as it looks good, is maintainable by those who don't have a familiarity with whatever framework is used, and isn't ridiculously slow to load/etc.
