### ISSUE TITLE
Missing gflags file after running setup

### ISSUE THREAD

**Issue by robhshu** [benvanik/xenia#424]
Hello

I've cloned the xenia repo and run the setup command:

    .\xb.bat setup

Then opening the developer environment (VS2015) and launching xenia-app from the standard setup, gflags throws a fatal error when reading the file `scratch/flags.txt`. The callstack looks like this:

    >	xenia.exe!google::`anonymous namespace'::ReadFileIntoString(const char * filename) Line 1007	C++
     	xenia.exe!google::`anonymous namespace'::CommandLineFlagParser::ProcessFlagfileLocked(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & flagval, google::FlagSettingMode set_mode) Line 1123	C++
     	xenia.exe!google::`anonymous namespace'::CommandLineFlagParser::ProcessSingleOptionLocked(google::`anonymous-namespace'::CommandLineFlag * flag, const char * value, google::FlagSettingMode set_mode) Line 1186	C++
     	xenia.exe!google::`anonymous namespace'::CommandLineFlagParser::ParseNewCommandLineFlags(int * argc, char * * * argv, bool remove_flags) Line 1097	C++
     	xenia.exe!google::ParseCommandLineFlagsInternal(int * argc, char * * * argv, bool remove_flags, bool do_report) Line 1902	C++
     	xenia.exe!google::ParseCommandLineFlags(int * argc, char * * * argv, bool remove_flags) Line 1917	C++
     	xenia.exe!xe::Main() Line 79	C++
     	xenia.exe!wWinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, wchar_t * command_line, int __formal) Line 112	C++

Looking at the debugging project properties of xenia-app, the command arguments are setup with these commands:

    --flagfile=scratch/flags.txt 2>&1 1>scratch/stdout.txt

However, my local file directory does not include `scratch/flags.txt`.

I have 2 folders (after running setup):

* scratch
* scratch1

However, scratch1 **does** include flags.txt! Is this an issue with premake?

https://github.com/benvanik/xenia/blob/master/premake5.lua#L111

```lua
-- Create scratch/ path and dummy flags file if needed.
if not os.isdir("scratch") then
  os.mkdir("scratch")
  local flags_file = io.open("scratch1/flags.txt", "w")
  flags_file:write("# Put flags, one on each line.\n")
```

**Comment by benvanik** [comment]
:+1: never noticed because I had that file, and the buildbot never tried running things through VS :)
