### ISSUE TITLE
Project libavcodec is always out of date

### ISSUE THREAD

**Issue by robhshu** [benvanik/xenia#425]
Opening the debugger for xenia-app under VS2015 always prompts that the project `libavcodec` is out of date.

Changing the MSBuild warning level to diagnostic produces:

    1>Project not up to date because build input '<local path>\xenia\third_party\libav\include\libavcodec\xma2dec.h' is missing.

I suspect this is a premake issue with the **libav** module here: https://github.com/xenia-project/libav/blob/master/libavcodec/premake5.lua#L51

I've created opened the issue here because issues are not supported on the xenia-project/libav repository.

**Comment by benvanik** [comment]
Nice find - I'd noticed that too, but hadn't looked into it.
