### ISSUE TITLE
Rewrite PPC disassembly.

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#432]
Currently some instructions have no disassembly, others are poorly formatted, and the whole thing is pretty ghetto (string only). Having a richer disassembler that could output operands such that future UI and analysis logic could work would be nice. Being faster is also a good thing, especially if for analysis and not being presented as a string.

**Comment by kmather73** [comment]
@benvanik  I was wounding if you wanted every instruction listed in  ppc_instr_tables.h to have its own Disasm function or do you need one for every instruction in the PCC ISA?

Also when you say ghetto what else wound you wanted returned? (Sorry if this is a noob question.)

**Comment by benvanik** [comment]
It'd be nice to have as many as possible share code. Being able to disasm to get text or programmatic information (registers read/written, etc) would be nice, and most importantly it needs to be fast (not just a linear scan).

**Comment by kmather73** [comment]
I made lookup tables for all the vector and Altivec instructions so things will be fast, but I can't get MSVS to commit the changes it just gives the following error "Error encountered while pushing to the remote repository: Response status code does not indicate success: 403 (Forbidden)."

Do I need some kind of permission to commit to the repository?

**Comment by gibbed** [comment]
@kmather73 Yes, only people added as collaborators can push directly to the repo. I'd suggest making a fork on GitHub, pushing your changes there, then submitting a pull request.

**Comment by kmather73** [comment]
@gibbed Thank for letting me know that, kinda new VC and open source.

**Comment by benvanik** [comment]
@kmather73 not sure what you're working on - this was recently completed:
https://github.com/benvanik/xenia/blob/master/tools/ppc-instructions.xml
generates:
https://github.com/benvanik/xenia/blob/master/src/xenia/cpu/ppc/ppc_opcode_disasm.cc

**Comment by kmather73** [comment]
Well I did some work on the now old and removed  ppc_instr_tables.h and ppc_instr.cc  tables but it seems that you have moved to a new system in  ppc_opcode_lookup.cc and ppc_opcode_info.h

That what I get for being slow.  The new system is very clean though.
