### ISSUE TITLE
Build Failure due to not finding a file

### ISSUE THREAD

**Issue by jamiehofer** [benvanik/xenia#441]
```
Building debug...

- running premake...
Building configurations...
Running action 'vs2015'...
Generating build/xenia.sln...
Generating build/capstone.vcxproj...
Generating build/capstone.vcxproj.filters...
Generating build/elemental-forms.vcxproj...
Generating build/elemental-forms.vcxproj.filters...
Generating build/elemental-forms-testbed.vcxproj...
Generating build/elemental-forms-testbed.vcxproj.user...
Generating build/elemental-forms-testbed.vcxproj.filters...
Generating build/glew.vcxproj...
Generating build/imgui.vcxproj...
Generating build/libavcodec.vcxproj...
Generating build/libavcodec.vcxproj.filters...
Generating build/libavutil.vcxproj...
Generating build/libavutil.vcxproj.filters...
Generating build/xxhash.vcxproj...
Generating build/gflags.vcxproj...
Generating build/gflags.vcxproj.filters...
Generating build/xenia-core.vcxproj...
Generating build/xenia-app.vcxproj...
Generating build/xenia-app.vcxproj.filters...
Generating build/xenia-apu.vcxproj...
Generating build/xenia-apu-nop.vcxproj...
Generating build/xenia-base.vcxproj...
Generating build/xenia-base-tests.vcxproj...
Generating build/xenia-base-tests.vcxproj.filters...
Generating build/xenia-cpu.vcxproj...
Generating build/xenia-cpu.vcxproj.filters...
Generating build/xenia-cpu-tests.vcxproj...
Generating build/xenia-cpu-tests.vcxproj.filters...
Generating build/xenia-cpu-frontend-tests.vcxproj...
Generating build/xenia-cpu-frontend-tests.vcxproj.user...
Generating build/xenia-cpu-frontend-tests.vcxproj.filters...
Generating build/xenia-cpu-backend-x64.vcxproj...
Generating build/xenia-debug.vcxproj...
Generating build/xenia-debug-ui.vcxproj...
Generating build/xenia-gpu.vcxproj...
Generating build/xenia-gpu-gl4.vcxproj...
Generating build/xenia-gpu-gl4-trace-viewer.vcxproj...
Generating build/xenia-gpu-gl4-trace-viewer.vcxproj.user...
Generating build/xenia-gpu-gl4-trace-viewer.vcxproj.filters...
Generating build/xenia-hid.vcxproj...
Generating build/xenia-hid-nop.vcxproj...
Generating build/xenia-kernel.vcxproj...
Generating build/xenia-kernel.vcxproj.filters...
Generating build/xenia-ui.vcxproj...
Generating build/xenia-ui-gl.vcxproj...
Generating build/xenia-vfs.vcxproj...
Generating build/xenia-vfs.vcxproj.filters...
Generating build/xenia-apu-xaudio2.vcxproj...
Generating build/xenia-hid-winkey.vcxproj...
Generating build/xenia-hid-xinput.vcxproj...
Done.

- building (all):debug...
Traceback (most recent call last):
  File "xenia-build", line 1013, in <module>
    main()
  File "xenia-build", line 86, in main
    return_code = command.execute(args, pass_args, os.getcwd())
  File "xenia-build", line 534, in execute
    result = super(BuildCommand, self).execute(args, pass_args, cwd)
  File "xenia-build", line 500, in execute
    pass_args, throw_on_error=False)
  File "xenia-build", line 174, in shell_call
    result = subprocess.call(command, shell=False, stdout=stdout_file)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
'''

**Comment by TranzRail** [comment]
I'm going to guess that there's an issue with your Python installation.

**Comment by ca1ek** [comment]
Try using another python version.

-----Wiadomość oryginalna-----
Od: "TranzRail" <notifications@github.com>
Wysłano: ‎2015-‎10-‎19 12:14
Do: "benvanik/xenia" <xenia@noreply.github.com>
Temat: Re: [xenia] Build Failure due to not finding a file (#441)

I'm going to guess that there's an issue with your Python installation.

**Comment by jamiehofer** [comment]
I had to manually add Python to root by doing this: http://windowsitpro.com/systems-management/how-can-i-add-new-folder-my-system-path

**Comment by TranzRail** [comment]
The documentation [here](https://docs.python.org/2/using/windows.html) will tell you how to add the Python installation directory to the PATH variable if not already done so. If your issue is resolved, please report back here so this issue can be closed.

Thanks.

**Comment by jamiehofer** [comment]
I am still having the issue after trying different versions and making sure it is in PATH.

**Comment by jamiehofer** [comment]
``Total errors found: 1763``
I just ran xb style

**Comment by TranzRail** [comment]
For reference, I'm using Python 2.9.7 x64. I'd suggest giving that a try.

**Comment by jamiehofer** [comment]
Windows x86-64 executable installer?

**Comment by TranzRail** [comment]
Correct.

**Comment by jamiehofer** [comment]
I used that as well

**Comment by jamiehofer** [comment]
Have you been able to build after the most recent commits?

**Comment by TranzRail** [comment]
Just doing a fresh pull. Will let you know soon.

**Comment by TranzRail** [comment]
Yes, I was able to do a fresh clone and build. Xenia ran as expected.

**Comment by jamiehofer** [comment]
What OS?

**Comment by TranzRail** [comment]
![basic specs 1](https://cloud.githubusercontent.com/assets/1941176/10778421/10e56f32-7d8b-11e5-984a-be6002216b78.png)

**Comment by jamiehofer** [comment]
I am using Windows 10....

**Comment by TranzRail** [comment]
How are you running the commands? A console output of the errors would be helpful.

**Comment by jamiehofer** [comment]
I first run setup (that works), then
``C:\Users\hofst\xenia>xb build
Building debug...

- running premake...
Building configurations...
Running action 'vs2015'...
Generating build/xenia.sln...
Generating build/capstone.vcxproj...
Generating build/capstone.vcxproj.filters...
Generating build/elemental-forms.vcxproj...
Generating build/elemental-forms.vcxproj.filters...
Generating build/elemental-forms-testbed.vcxproj...
Generating build/elemental-forms-testbed.vcxproj.user...
Generating build/elemental-forms-testbed.vcxproj.filters...
Generating build/glew.vcxproj...
Generating build/imgui.vcxproj...
Generating build/libavcodec.vcxproj...
Generating build/libavcodec.vcxproj.filters...
Generating build/libavutil.vcxproj...
Generating build/libavutil.vcxproj.filters...
Generating build/xxhash.vcxproj...
Generating build/gflags.vcxproj...
Generating build/gflags.vcxproj.filters...
Generating build/xenia-core.vcxproj...
Generating build/xenia-app.vcxproj...
Generating build/xenia-app.vcxproj.filters...
Generating build/xenia-apu.vcxproj...
Generating build/xenia-apu-nop.vcxproj...
Generating build/xenia-base.vcxproj...
Generating build/xenia-base-tests.vcxproj...
Generating build/xenia-base-tests.vcxproj.filters...
Generating build/xenia-cpu.vcxproj...
Generating build/xenia-cpu.vcxproj.filters...
Generating build/xenia-cpu-tests.vcxproj...
Generating build/xenia-cpu-tests.vcxproj.filters...
Generating build/xenia-cpu-frontend-tests.vcxproj...
Generating build/xenia-cpu-frontend-tests.vcxproj.user...
Generating build/xenia-cpu-frontend-tests.vcxproj.filters...
Generating build/xenia-cpu-backend-x64.vcxproj...
Generating build/xenia-debug.vcxproj...
Generating build/xenia-debug-ui.vcxproj...
Generating build/xenia-gpu.vcxproj...
Generating build/xenia-gpu-gl4.vcxproj...
Generating build/xenia-gpu-gl4-trace-viewer.vcxproj...
Generating build/xenia-gpu-gl4-trace-viewer.vcxproj.user...
Generating build/xenia-gpu-gl4-trace-viewer.vcxproj.filters...
Generating build/xenia-hid.vcxproj...
Generating build/xenia-hid-nop.vcxproj...
Generating build/xenia-kernel.vcxproj...
Generating build/xenia-kernel.vcxproj.filters...
Generating build/xenia-ui.vcxproj...
Generating build/xenia-ui-gl.vcxproj...
Generating build/xenia-vfs.vcxproj...
Generating build/xenia-vfs.vcxproj.filters...
Generating build/xenia-apu-xaudio2.vcxproj...
Generating build/xenia-hid-winkey.vcxproj...
Generating build/xenia-hid-xinput.vcxproj...
Done.

- building (all):debug...
Traceback (most recent call last):
  File "xenia-build", line 1013, in <module>
    main()
  File "xenia-build", line 86, in main
    return_code = command.execute(args, pass_args, os.getcwd())
  File "xenia-build", line 534, in execute
    result = super(BuildCommand, self).execute(args, pass_args, cwd)
  File "xenia-build", line 500, in execute
    pass_args, throw_on_error=False)
  File "xenia-build", line 174, in shell_call
    result = subprocess.call(command, shell=False, stdout=stdout_file)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified``

**Comment by TranzRail** [comment]
Have you got the latest Visual Studio 2015 installed? Also, is there any reason as to why you put xenia in the root of your user profile folder?

**Comment by jamiehofer** [comment]
I have Visual Studio, I have no reason for having Xenia in root.

**Comment by TranzRail** [comment]
I think the error is with the Python trying to launch Visual Studio. Line 500 in the Python script points to this --> 

(Line 493) result = shell_call([
          'devenv',
          '/nologo',
          'build/xenia.sln',
          '/rebuild' if args['force'] else '/build',
          args['config'],
          ] + [('/project ', target) for target in args['target']] +
          pass_args, throw_on_error=False)

**Comment by jamiehofer** [comment]
I started a C project in Visual Studio, and now it is downloading some more. Perhaps the initial download did not contain all the necessary files.

**Comment by TranzRail** [comment]
Lets hope that does it.

**Comment by jamiehofer** [comment]
It worked!

**Comment by jamiehofer** [comment]
Unhandled exception at 0x00007FFFEE674388 (ucrtbase.dll) in xenia.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

**Comment by jamiehofer** [comment]
I am also failing the CPU tests (all of them). I am using a 5820k.

**Comment by TranzRail** [comment]
How did you launch xenia?

**Comment by jamiehofer** [comment]
I am running the CPU Tests.

**Comment by TranzRail** [comment]
Can you post a screenshot?

**Comment by jamiehofer** [comment]
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 is a Catch v1.2.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
PACK_FLOAT16_2
-------------------------------------------------------------------------------
..\src\xenia\cpu\testing\pack_test.cc(38)
...............................................................................

..\src\xenia\cpu\testing\pack_test.cc(54): FAILED:
  REQUIRE( result == vec128i(0, 0, 0, 0x7FFFFFFF) )
with expansion:
  {?} == {?}

-------------------------------------------------------------------------------
PACK_FLOAT16_4
-------------------------------------------------------------------------------
..\src\xenia\cpu\testing\pack_test.cc(66)
...............................................................................

..\src\xenia\cpu\testing\pack_test.cc(83): FAILED:
  REQUIRE( result == vec128i(0x00000000, 0x00000000, 0x64D26D8C, 0x48824491) )
with expansion:
  {?} == {?}

-------------------------------------------------------------------------------
PACK_SHORT_2
-------------------------------------------------------------------------------
..\src\xenia\cpu\testing\pack_test.cc(87)
...............................................................................

..\src\xenia\cpu\testing\pack_test.cc(95): FAILED:
  REQUIRE( result == vec128i(0) )
with expansion:
  {?} == {?}
```

**Comment by jamiehofer** [comment]
Do you know where one can acquire an ISO to test with?

**Comment by TranzRail** [comment]
Per the rules, I can't answer that question. FYI, Xenia can actually load .xex files directly.
