### ISSUE TITLE
Regression on Raiden IV and RR 6

### ISSUE THREAD

**Issue by raven02** [benvanik/xenia#462]
It breaks since https://github.com/benvanik/xenia/pull/454 and hit the breakpoint at copy_and_swap_16_unaligned()

@DrChat .FYI

**Comment by JohnGodgames** [comment]
Are you sure?RR6 was worked for me when I reverted https://github.com/benvanik/xenia/commit/c98d10545e3236dc466215cf0bad471e92247680

**Comment by raven02** [comment]
Yes , reverted that commit is working again however i would wait for @DrChat for proper fix .

BTW, this game suffers depth clearing issue in-game but seeing the demo from your youtube , it is working fine .

**Comment by JohnGodgames** [comment]
Just commented this line https://github.com/benvanik/xenia/blob/ee92f75a842b0b268808e7b502e4b3f982d136de/src/xenia/gpu/gl4/draw_batcher.h#L74 and also Eternal Sonata broken after this.

**Comment by raven02** [comment]
Thanks @JohnGodgames

**Comment by DrChat** [comment]
Shouldn't be caused by that fix. Regardless, we're about to overhaul the graphics backend, so this should be fixed when that comes around.

**Comment by raven02** [comment]
Thanks @DrChat .

**Comment by JohnGodgames** [comment]
It's not caused by graphics backend, but changes made in https://github.com/benvanik/xenia/pull/454 src/xenia/memory.cc @DrChat

**Comment by raven02** [comment]
It looks like it is okay now when new shader translator in place.
