### ISSUE TITLE
Possible support for OpenGL 4.4 GPU's ?

### ISSUE THREAD

**Issue by Unlimax** [benvanik/xenia#463]
Since this emulator is designed to run only on 4.5 OpenGL could we expect in any consideration to support 4.4 users too in the near future ?
Hope you guys extend your support .

**Comment by benvanik** [comment]
The emulator will be shifting to Vulkan in the near future. If your hardware supports the requisite features and you have updated drivers it may work, however I'm not sure exactly what the hardware compatibility looks like.
