### ISSUE TITLE
ntdll.dll issue

### ISSUE THREAD

**Issue by Baboulinet123** [benvanik/xenia#480]
![xenia issue](https://cloud.githubusercontent.com/assets/16181116/11616042/d2dc8ffe-9c70-11e5-812a-d871659e462a.JPG)

Hi, 

 I can't launch the emulator properly. I got many issues about DLL and I just downloaded some of them to fix it. However, I got this issue and I can't fix it for now. 

 Thanks. (and thank you for your work !)

**Comment by gibbed** [comment]
You don't meet the minimum requirements, which is Windows 8.

**Comment by Baboulinet123** [comment]
Hi,

 Thank you for your answer. But, the emulator will be available for windows 7 later ? Thanks.

**Comment by Razzile** [comment]
very very unlikely. xenia is built around functions present in windows 8+ and the goal is to always use the latest technology in xenia. see http://xenia.jp/faq/#can-you-add-support-for-windows-me-how-about-my-pentium-ii

**Comment by Baboulinet123** [comment]
Oh, I understand. Thank you for your answer.
