### ISSUE TITLE
Kernel/ObjectTable: Remove explicit specialization in class scope

### ISSUE THREAD

**Issue by sephiroth99** [benvanik/xenia#482]
Clang currently gives the following error:
```
In file included from ../src/xenia/emulator.cc:10:
In file included from ../src/xenia/emulator.h:18:
In file included from ../src/xenia/kernel/kernel_state.h:25:
../src/xenia/kernel/util/object_table.h:51:23: error: explicit specialization of
      'LookupObject' in class scope
  object_ref<XObject> LookupObject<XObject>(X_HANDLE handle) {
                      ^
1 error generated.
```

I would propose the following fix: sephiroth99/xenia@01278162. Basically, remove the specialization, add a type for XObject and do not assert when types mismatch and type is Object. If it seems OK, I'll send the PR.

**Comment by benvanik** [comment]
The error here is about where the specialization is defined, not that it exists. Try moving it out of the class.

Adding kObject isn't valid - there is no 'object' type. I'd rather keep the specialization.

**Comment by sephiroth99** [comment]
Right, I get ya. I'll work on it some more. Thanks for the feedback!

**Comment by DrChat** [comment]
This is invalid on clang?
Where do they expect you to put the specialization - under the class?

**Comment by paulsapps** [comment]
http://stackoverflow.com/questions/3052579/explicit-specialization-in-non-namespace-scope ?

**Comment by sephiroth99** [comment]
Updated branch here: https://github.com/sephiroth99/xenia/commit/a281f6d70df11bd72784fd4b290f48c5ecee3ac3

I'm sure I tried something similar to this before and it didn't work, so I came up witht that convoluted workaround in the original patch... Anyway this is way cleaner now.

@benvanik As usual, if this seems OK, I'll send the PR. Thanks!
