### ISSUE TITLE
Blank Render With full sound 

### ISSUE THREAD

**Issue by alexis23ange** [benvanik/xenia#483]
so i was testing star ocean 4 the last hope and started the game and all i hear is audio but no graphics so i got my buddy to test it and he got everything working very playable so this issue might be with my 290x/390x and opengl 4.5

**Comment by benvanik** [comment]
Unfortunately I'm not sure any of us have an AMD card. Someone who has one will have to diagnose.

**Comment by alexis23ange** [comment]
tell me how to do whats needed or if need be you can take over my pc for a bit and do it

**Comment by sephiroth99** [comment]
Most likely related to #416.
TLDR is there is something happening with Geometry Shaders.
In reality, AMD support level for GLSL is 4.4 (even though OGL support is 4.5). We have to wait until AMD has official GLSL 4.5 support I reckon.

**Comment by alexis23ange** [comment]
amd got full opengl 4.5 render with crimson drivers and windows 10 so it's not that and god i wish you guys would use direct x 12 opengl is a bloody mess and nothing ever works proper

**Comment by benvanik** [comment]
@alexis23ange unfortunately you'll probably have to wait until the vulkan rewrite.

**Comment by alexis23ange** [comment]
at least i know it will work being mantle at the core
