### ISSUE TITLE
Saving issue

### ISSUE THREAD

**Issue by adokova** [benvanik/xenia#484]
So i booted up the full game and after the save screen, buttons dont respond :/ ? the demo works fine.
![su test](https://cloud.githubusercontent.com/assets/16245681/11726191/cec50472-9f7d-11e5-9722-fa7e3de09bd3.png)

**Comment by Razzile** [comment]
this is probably not what the issues section is for. please post a full issue here https://github.com/xenia-project/game-compatibility

**Comment by adokova** [comment]
Ok

**Comment by robert-7** [comment]
@adokova can you please close this since it's not in the right place?

**Comment by maxton** [comment]
This might actually be an issue with the xenia UI (if it's the buttons on that popup that aren't responding), but the issue isn't specific enough to know that
