### ISSUE TITLE
Help me fix this error...

### ISSUE THREAD

**Issue by daisycow5** [benvanik/xenia#495]
When i try and open Xenia this pops up...
X> 14D8 Unable to initalize GL content
Please help me fix this.

**Comment by jackchentwkh** [comment]
could you please at least show us your PC setup including your hardwares, OS, and the Xenia build you're using.

**Comment by daisycow5** [comment]
![xenia 1](https://cloud.githubusercontent.com/assets/16442744/12035335/0faebcbe-ae90-11e5-9f5a-0855cb444b06.PNG)
Does this help

**Comment by daisycow5** [comment]
The Xenia build I'm using is:
EmuCR-Xenia-20150616-x64

**Comment by jackchentwkh** [comment]
seems you don't have any GPU listed in the necessary list.
http://delphigl.de/glcapsviewer/listreports.php?listreportsbyextension=GL_ARB_bindless_texture&sortby=description_asc

**Comment by daisycow5** [comment]
oh.... guess no 360 emulator for me :(

**Comment by daisycow5** [comment]
wait

**Comment by JoaRiski** [comment]
@daisycow5 As far as I know, the emulator is no where near ready to be used just for playing. Unless you're a developer, I doubt you'd find it useful.

**Comment by daisycow5** [comment]
@JoaRiski Well i'm trying to find out something about the emulator.

**Comment by daisycow5** [comment]
I should be able to get it
![xenia 2](https://cloud.githubusercontent.com/assets/16442744/12035948/9cb3b02e-ae95-11e5-9dbf-9532332e41c7.PNG)

**Comment by benvanik** [comment]
Sorry, this issue tracker is not for tech support.
As pointed out your graphics card may not be compatible or you may not have the latest drivers for it. Check both and if that still doesn't work you are likely out of luck.

**Comment by Xzip** [comment]
From me is the ARB_bindless_texture error and my gpu is GeFore GT 705
