### ISSUE TITLE
Size mismatch for specialised ControlFlowInstruction with Clang

### ISSUE THREAD

**Issue by sephiroth99** [benvanik/xenia#502]
When compiling with Clang, the static_assert_size for all 9 specialised ControlFlowInstructions get a hit (for example [this one](https://github.com/benvanik/xenia/blob/cbc74c92f40a68bd3f0f7ab9f6f276014288905c/src/xenia/gpu/ucode.h#L186)). The size Clang calculates is 6 bytes, instead of the indicated 8 bytes. If you count the bits in the packed Data struct for all 9 though, they do have 6 bytes exactly...!

The "base" ControlFlowInstruction does not get a hit because the last struct in the union is 2 dwords.

Which is the correct size? I suppose 8 bytes was for alignment purposes? Do we remove bytes from the "base" instruction, or add to the specalised ones? Must also keep in mind that MSVC is very happy to fit the 6 bytes of bitfields in 8 bytes... It was always wonky to play with bitfields and MSVC, so whatever changes it must stay compatible...

**Comment by benvanik** [comment]
Fun!
8 bytes is correct - the instructions are overlapped. You can see the shift trickery that happens [here](https://github.com/benvanik/xenia/blob/cbc74c92f40a68bd3f0f7ab9f6f276014288905c/src/xenia/gpu/ucode.h#L505).
VC++ pads out bitfields to the full dword values, and I guess clang doesn't. Odd. Adding additional unspecified padding bits to bring each dword out to a full 32bits seems like the cleanest option (so in your linked example adding an `uint32_t : 16;` at the end).

**Comment by sephiroth99** [comment]
OK I'll play around with that. There is a high possibility that adding padding will make MSVC go over 8 bytes. I'll find a way that works for both.

**Comment by benvanik** [comment]
If the bits still total <= 32 it shouldn't go over.

**Comment by benvanik** [comment]
Fixed!
