### ISSUE TITLE
X> 1fac unable to initialize GL context

### ISSUE THREAD

**Issue by DJseba554** [benvanik/xenia#512]
please help me with xenia becouse when I open it it shows xenia error X> 1fac unable to initialize GL context (windows 10)

**Comment by Razzile** [comment]
what graphics card do you have? P.S this issue tracker isn't for support

**Comment by DJseba554** [comment]
Radeon

**Comment by Razzile** [comment]
but which radeon? radeon is the name of their GPU line.

The chances are that if you don't know the exact details about your gpu, it probably doesn't support xenia and you probably shouldn't be using a pre release version of xenia

**Comment by benvanik** [comment]
As Razzile says, this issue tracker is not for tech support.
