### ISSUE TITLE
xb build fails

### ISSUE THREAD

**Issue by davidm71** [benvanik/xenia#513]
Hi,
I ran 'xb build' in cmder with python 2.711 installed (last 2.7 release) and get this error:
'WindowsError: [Error 2] The system cannot find the file specified'

Any ideas anyone?

Thank you.

**Comment by Blackbird88** [comment]
According to AppVeyor it's not buildable for anyone now.

**Comment by benvanik** [comment]
the fork of yaml-cpp I was using deleted their branch. fixing
