### ISSUE TITLE
Dragon Ball: Raging Blast 1/2  [State playable]--> Emulator Crash  

### ISSUE THREAD

**Issue by SakataGintokiYT** [benvanik/xenia#519]
I updated topic in [Game compatibility list]   but nobody ever looks  #50
https://github.com/xenia-project/game-compatibility/issues/50

Now game stopped emulator [crash]
Xenia Git (2016/01/15) - http://www.emucr.com/2016/01/xenia-git-20160115.html

*Working
 Xenia Git (2015/06/10) - http://www.emucr.com/2015/06/xenia-git-20150610.html
Game Speed  very  good 
Movie :
https://www.youtube.com/watch?v=F-uJ9fmn7Dk
https://www.youtube.com/watch?v=0K76IZ4J9aA

**Comment by DrChat** [comment]
This doesn't belong here - keep it in the game-compatibility repository.
