### ISSUE TITLE
Virtua Fighter 5: Final Showdown - Error with reading disc.

### ISSUE THREAD

**Issue by fenix008** [benvanik/xenia#523]
I just checked it and this error starting from this build (http://www.emucr.com/2015/06/xenia-git-20150628.html), it worked before (with no any graphics), but now it's not working.

It's still not working and writes a new error (http://rghost.ru/7xLJm2Vt9.view)

P.S. if need any info I can provide it.

**Comment by SakataGintokiYT** [comment]
'After Burner Climax  the same problem'

**Comment by voltagex** [comment]
Do you have a log for it?

**Comment by fenix008** [comment]
atm - no, but I can test it later and post log here.

**Comment by fenix008** [comment]
okay, log is here - http://rghost.ru/7wvjz7MSY

**Comment by fenix008** [comment]
this problem is still going..

**Comment by voltagex** [comment]
@fenix008 Unfortunately writing an emulator from scratch is hard. Have you got a log from a recent build?

**Comment by fenix008** [comment]
a bit later.... But in recent build it's the same.

**Comment by fenix008** [comment]
Sorry, I'm too late....there is my log file.
http://rgho.st/8fJDDNHKj

**Comment by fenix008** [comment]
@voltagex Sorry, I'm too late....there is my log file.
http://rgho.st/8fJDDNHKj

**Comment by fenix008** [comment]
It's still doesn't work.

[VF5FS 14.03.2017.zip](https://github.com/benvanik/xenia/files/840057/VF5FS.14.03.2017.zip)

**Comment by gibbed** [comment]
Too general of an issue to research, need to handle this on a game to game basis.
