### ISSUE TITLE
Have they given up supporting AMD until they switch to Vulkan or D3D12?

### ISSUE THREAD

**Issue by RenegadeSaiyan** [benvanik/xenia#536]
Just would like to know, that's all.

**Comment by Husono** [comment]
Xenia requires GLSL 4.5 which AMD cards currently do not support. GLSL is not the same as OpenGL. Xenia will probably be supported on AMD cards once they are updated to support the newest GLSL.

**Comment by RenegadeSaiyan** [comment]
Okay thank you
