### ISSUE TITLE
Problem add commit #514 DrChat check this !

### ISSUE THREAD

**Issue by SakataGintokiYT** [benvanik/xenia#555]
@DrChat 
@benvanik 
##### Video :  https://www.youtube.com/watch?v=Q9CaQEXoTDc&feature=youtu.be

**Comment by Razzile** [comment]
it's nice that you're willing to post so many reports but mentioning devs in every issue will probably annoy them. They'll definitely take a look at the report sooner or later :P

**Comment by DrChat** [comment]
Yeah, I did ask you not to mention us (me and other contributors) everywhere before.
We're working on a Vulkan backend and graphics will be completely overhauled.

Comparison videos like this would be useful, but make sure you're making them for stuff we're not actively working on.
Don't use this repository to report on issues specific to a single game.
Please follow the rules, we're not going to prioritize your issues over anything else.

**Comment by benvanik** [comment]
@SakataGintokiYT your issues are welcome (you're highlighting good problems! and providing good examples to help us narrow down issues!), but this project is done by us for our own fun and enjoyment and we'll get to things as soon as we can. Please refrain from calling out developers here - the issues you file are going to be looked at the same regardless. As @DrChat, the game-compatibility repository is better for per-game issues, where as this repository is for tracking core development tasks or issues that affect large numbers of games. If you find something like that it's useful to highlight, but again as a single bug and not calling out developers.
