### ISSUE TITLE
Fix Crash  In  Dragon Ball Games

### ISSUE THREAD

**Issue by SakataGintokiYT** [benvanik/xenia#557]
@Razzile 
@benvanik 
##### Update:
src/xenia/kernel/xboxkrnl_memory.cc
stats ->title.available_pages = 0x00020000;  [Dragon Ball Raging Blast 1/2 Works  ]
stats ->title.available_pages = 0x00019000;  Only Intro work ;)

-Dragon Ball Raging Blast 1 (0x00020000  Works) / [ 0x00019000 Work opening but crash]
-Dragon Ball Raging Blast 2 (0x00020000 Works) / [ 0x00019000 Work opening but crash]
-Dragon Ball Z: Ultimate Tenkaichi ( 0x00019000 Intro / Opening  ) 

<img src="http://www.fotoszok.pl/upload/af13cbe7.jpg" alt="Fotoszok.pl" />

**Comment by voltagex** [comment]
Hey @SakataGintokiYT - can you add a little bit of context here about what this is and how this fixes crashes?

**Comment by SakataGintokiYT** [comment]
@voltagex 
<img src="http://www.fotoszok.pl/upload/af13cbe7.jpg" alt="Fotoszok.pl" />
