### ISSUE TITLE
i cant run

### ISSUE THREAD

**Issue by mailtorohan007** [benvanik/xenia#559]
Iam unable to run the emulator though my gpu is open gl 4.5. Plzz help

**Comment by kmather73** [comment]
If you can't get Xenia to run then you probably shouldn't be messing around with it, also since Xenia is still in "early" development you probably shouldn't expect much in terms of smooth play-ability of most game.

As a final note this is not a help thread its true purpose is for reporting bugs which will help the development of Xenia.

**Comment by mailtorohan007** [comment]
Is there any way to use it ?
And are you editing it for pc with open gl less than 4.5?
And what about android version of it ?

**Comment by resetnow** [comment]
yeah and also does it run on my 286 with qnx? i have math coprocessor!

seriously though the nature of the project really attracts non-programming community.

**Comment by mailtorohan007** [comment]
How to run plz tell me...
I download gta v for xbox 360 it costed me 16.2 gb and i dont want it to go in wain....
And i see people uploading videos that they are running gta v using xenia emulator and that runs very smoothly...

**Comment by Jan4V** [comment]
Haha, yeah, you look like that kind of people who believe those fake videos. You cant emulate GTA V using this emulator, it cant 100% emulate even minecraft. You must wait, the programmers are working hard on this. Also, why the first game you tried on this emulator was GTA V? Logically im not gonna waste bandwidth and test it with a little XBLA game. Plus you shouldnt pirate games, as its highly illegal and against the terms of use of this emulator(at least i think).

**Comment by mailtorohan007** [comment]
So that was just a waste...
Anyway thnx for that...

**Comment by mailtorohan007** [comment]
So i am gonna download it for my pc..
Is that legal?

**Comment by Jan4V** [comment]
No, downloading a cracked game is illegal for all platforms.

**Comment by mailtorohan007** [comment]
Well no one bothers that even rockstar games.
I have a question that will it work if i download..??

**Comment by mailtorohan007** [comment]
Or this is also fake?

**Comment by Jan4V** [comment]
You cannot discuss illegal activities in here. Someone please close this issue.

**Comment by mailtorohan007** [comment]
Ok sorry for that 
Closing it..
