### ISSUE TITLE
Diretcx 10 ?

### ISSUE THREAD

**Issue by korhan33** [benvanik/xenia#561]
friends my system pretty good, but I'm an old graphics card and supports diretcx diretcx 10 10 support series?

**Comment by korhan33** [comment]
video card to remain in 2008 .

**Comment by Razzile** [comment]
yea no. xenia is meant to leverage the latest technologies. an old video card and dx10 won't cut it, not even close

**Comment by korhan33** [comment]
oh. thanks.

**Comment by phly95** [comment]
I would think a 2008 card would barely run Dolphin, never mind Xenia or RPCS3

**Comment by korhan33** [comment]
wrote my system that intel core i5 2500K to 3.30 GHz four core 16 GB RAM ASRock eXtreme 3 gene 3 cross at the motherboard waste XL GTX 580 graphics card I use the corrupt 9400GT graphics card type would be nice if you get the diretcx 10 support 980 graphics card it'll take , but I want to try the following Xenia arriving
