### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by kobyaustin1** [benvanik/xenia#564]
my game banjo kazooie nuts and bolts crashes after the second logo how do i fix this

**Comment by Razzile** [comment]
this is not what the issue system is for

**Comment by itslemoobman** [comment]
The emulator and/or your PC is most likely unable to run the game for the moment.

**Comment by VelocityRa** [comment]
I feel like this should be closed.

**Comment by Razzile** [comment]
@benvanik *nudge*
