### ISSUE TITLE
Red Dead Redemption Blank Screen

### ISSUE THREAD

**Issue by XxTheK3LLERWithinxX84** [benvanik/xenia#566]
I know there was a similar thread, but I can't find it anymore, but anyways, I'm using the latest Xenia build, I have got the game's iso and dvd (DVD file format crashes since there's no file on it). When I open the file, the game just displays blank screen, just when it suppose to display Rockstar logo getting shot, I hear the sound but after that, I can't hear anything at all.
The CPU is taking around about 68-70% is that normal?

My computer specifications:
Intel Core i7 4790 3.6GHz - 4GHz
GTX 750 Ti  2GB OCed
8GB 1600MHz RAM

Thanks everyone! I'll try to update you if anything changes, plus the log massively increases so I can't upload it.

EDIT:
The newer build on this page: https://ci.appveyor.com/project/benvanik/xenia/build/artifacts worked more better but the game loads slowly but better. The logo displayed correctly.
The first mission seems to always fail, just after the cutscene, saying: "Failed. You have abandoned your contract." to me it seems to be like wrong co-ordinations for John Marston, as if he's in somewhere else.

**Comment by Razzile** [comment]
the main xenia repo issue page isn't for individual game problems. Please take this issue to here https://github.com/xenia-project/game-compatibility/issues/108

EDIT: you did

**Comment by XxTheK3LLERWithinxX84** [comment]
@Razzile, sorry about that!
