### ISSUE TITLE
xenia.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by XxTheK3LLERWithinxX84** [benvanik/xenia#567]
This error keeps appearing even on recent clean installed windows 7, it worked perfectly on winodws 10.
When opening the program is displays this:
![capture](https://cloud.githubusercontent.com/assets/16472463/14060900/d531c2d8-f369-11e5-8564-cd86412f38f8.PNG)
How can I fix this? Plus, I have ntdll.dll already in sysWOW64 and system32 folders.

**Comment by Nezarn** [comment]
Xenia works only on windows 8.1 or later.

**Comment by XxTheK3LLERWithinxX84** [comment]
Ah... sorry about that then. Guess I was lazy to read that properly...
