### ISSUE TITLE
Question about OpenGL Compatibility

### ISSUE THREAD

**Issue by thx3ever** [benvanik/xenia#568]
I'm about to replace my AMD HD 7770 so i want to ask a simple question:
If i buy NVIDIA GTX 560TI it supports GL_ARB_BINDLESS_TEXTURE? Since it says support OpenGL 4.5 SL 4.5, so i don't want to make a mistake or i will buy NVIDIA GTX 650Ti

**Comment by SakataGintokiYT** [comment]
buy GTX 650Ti

**Comment by thx3ever** [comment]
One more question: the GTX 650Ti its better than Zotac Geforce GTX 750?

**Comment by SakataGintokiYT** [comment]
gtx 650 ti is better

**Comment by Blackbird88** [comment]
Just for record [all those GPUs support it]
(http://delphigl.de/glcapsviewer/listreports.php?listreportsbyextension=GL_ARB_bindless_texture&sortby=description_asc)
Read [FAQ](http://xenia.jp/faq/#what-kind-of-gpu-do-i-need) next time.

**Comment by Gamedev1909** [comment]
all you will hear here is all nvidia but i would get a rx 480 a 200$ card with full opengl 4.5 support and amazingly fast
