### ISSUE TITLE
FIFA WORLD CUP 2010 not work

### ISSUE THREAD

**Issue by isoft-lu** [benvanik/xenia#570]
"your selected storage device is no longer available. You will need to select a storage device to save games"
this open game menu but in 5sec exit. Strange game .iso has 7GB all original, but cant run any game I tested 3 and give up,
fuck you japanase.

**Comment by deadair3210** [comment]
"fuck you japanase"

what does that have anything to do with this?

**Comment by isoft-lu** [comment]
what? I lost time to fucking looking for some xbox360 emulator, and then after getting 3 adwares and malware I came to your fucking shit which not work as well!
If you want to do something then release something WHAT actually WORKS and not a bullshit!

**Comment by lukestrong** [comment]
Wow...
I can't tell if your trolling, or if your just an ungrateful idiot.
Xenia is not meant for playing (or pirating) games, its still got a lot more work before it can run most retail games at full speed. To be honest, its progressing really well! If you look at videos of Xenia's early builds and compare them to videos of the later builds, you'll see that some games are completely playable!
Your bug report helps the devs fix xenia, but your attitude does not.
