### ISSUE TITLE
Sonic the Hedgehog (2006) Instant Death during certain actions on certain setups

### ISSUE THREAD

**Issue by cmexp** [benvanik/xenia#572]
While testing this game on newer builds (this bug didn't appear in the 2015 builds), I noticed that certain actions would kill me instantly while showing me a black screen (or a frozen screen) until respawn. And watching videos of people playing the game on the same builds, it seems the bug is not affecting them. The system I was testing this on had a GTX 980, Intel 5930k, DDR4 2133 RAM, and Windows 10.

The things that trigger this are:

- [Light dashing in midair](https://gfycat.com/IndelibleAcrobaticArabianhorse) ([compared to when not in midair](https://gfycat.com/IndelibleValidBalloonfish))

- [Certain bounce pads](https://gfycat.com/SpiritedClutteredBunting)

- [Grabbing onto the whale in this scripted event](https://gfycat.com/ImmaculatePaltryEyra)

I feel like this is worth attention since it only happens on certain configurations.

**Comment by Razzile** [comment]
this probably isn't an issue for the main repo. please file a report [here](https://github.com/xenia-project/game-compatibility)

**Comment by DPersonalized** [comment]
I think steps should be taken to make the existence of https://github.com/xenia-project/game-compatibility and what exactly it is for more obvious. For example, on the main page of this repo, write "ANY GAME-RELATED ISSUES SHOULD BE POSTED [HERE](https://github.com/xenia-project/game-compatibility)" or something like that (same with the website, as well.) I didn't even know that repo existed until @Razzile linked it.

**Comment by cmexp** [comment]
I knew about the repo, but I got confused seeing things like "[x game] crashes emulator" in the main issue tracker so I thought this issue was for the main one.

**Comment by DrChat** [comment]
Does the entire game become frozen or just video?

**Comment by cmexp** [comment]
When I die in these instances, only the 3D parts of the game freeze/blank out. The HUD is still animated, and I respawn just fine.

**Comment by DrChat** [comment]
:+1: Neat - You had me worried there, if the game itself froze then this would be a huge debugging project.

If you can, see if this still happens with my Vulkan PR.

**Comment by SakataGintokiYT** [comment]
@DrChat 
How to build Xenia Vulkan

**Comment by DrChat** [comment]
@SakataGintokiYT That question is off topic in both of the threads you've asked it in.
If you want help, please ask #xenia on IRC.

**Comment by SakataGintokiYT** [comment]
<img src="https://i.ytimg.com/vi/_QR9QP0Rjsc/hqdefault.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

**Comment by ScorchEmber256** [comment]
fixed by #574 
Seems to work fine now
