### ISSUE TITLE
Unable to build on Linux (Fedora 23)

### ISSUE THREAD

**Issue by vezza** [benvanik/xenia#575]
# ./xenia-build build

Building debug...
- running premake...
  Building configurations...
  Running action 'gmake'...
  Done (859ms).
  Building configurations...
  Running action 'codelite'...
  Done (786ms).
- building (all):debug...
  make: ingresso nella directory "/home/andrea/xenia/build"
  ==== Building capstone (debug_linux) ====
  ==== Building gflags (debug_linux) ====
  gflags.cc
  In file included from ../third_party/gflags/src/gflags.cc:96:
  In file included from ../third_party/gflags/src/gflags/gflags.h:81:
  /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/../../../../include/c++/5.3.1/string:38:10: fatal error: 'bits/c++config.h' file not found
  # include <bits/c++config.h>
  
  ```
   ^
  ```
  
  1 error generated.
  gflags.make:180: set di istruzioni per l'obiettivo "obj/Linux/Debug/Linux/Debug/gflags/gflags.o" non riuscito
  make[1]: **\* [obj/Linux/Debug/Linux/Debug/gflags/gflags.o] Errore 1
  Makefile:147: set di istruzioni per l'obiettivo "gflags" non riuscito
  make: **\* [gflags] Errore 2
  make: uscita dalla directory "/home/andrea/xenia/build"

ERROR: build failed with one or more errors.

**Comment by jobs-git** [comment]
it says you don't have "bits/c++config.h"

Try to see if these works.
http://stackoverflow.com/questions/4643197/missing-include-bits-cconfig-h-when-cross-compiling-64-bit-program-on-32-bit
