### ISSUE TITLE
Errors while starting a Madden 15/Red Dead Redemption

### ISSUE THREAD

**Issue by Jonatino** [benvanik/xenia#576]
I've attached some errors I got when trying to start Madden:

https://dl.dropboxusercontent.com/u/91292881/ShareX/2016/05/xenia_2016-05-24_06-46-49.png

(I also got the error below when trying Red Dead Redemption)
https://dl.dropboxusercontent.com/u/91292881/ShareX/2016/05/xenia_2016-05-24_06-47-18.png

https://dl.dropboxusercontent.com/u/91292881/ShareX/2016/05/xenia_2016-05-24_06-47-42.png

I'm excited to start contributing to this emulator :) Thank you so so much for the work you've already done, this thing is awesome!

**Comment by SakataGintokiYT** [comment]
Wrong build :P
<img src="http://www.fotoszok.pl/upload/9df88236.png" alt="Fotoszok.pl" />

**Comment by DrChat** [comment]
I appreciate you trying to help, but these aren't really useful nor in the right places.

Check the game compatibility repository and please do post if something interesting happens (other than an assert dialog). Gonna go ahead and close this issue.
