### ISSUE TITLE
ARB_bindless_texture Error

### ISSUE THREAD

**Issue by Xzip** [benvanik/xenia#577]
Help me when i want to play on xenia it shows this error:
(X) Opengl Extension ARB_bindless_texture is required.
Ensure you have the latest drivers of your GPU that it suports OpenGL 4.5 see http://xenia.jp/faq for more infromation and listof supported GPUs.

**Comment by nulcearc** [comment]
It means that your graphics card doesn't support OpenGL 4.5.

**Comment by Razzile** [comment]
that label is perfect in every way
