### ISSUE TITLE
No game input any game!

### ISSUE THREAD

**Issue by dpsman917** [benvanik/xenia#580]
Xenia Launches my game Perfectly i see the title screen and hear sound its full 60fps!!
But when i push start on my controller the game wont play i get no input at all!!
I have tried 7 different builds of xenia and 3 different controllers and tried x360ce always the same no input.

I looked and looked for another post on the issue and i could not find one.

I even tried on my other computer same result full load game title screen no controller input.

This is seriously depressing me i am usually able to figure out issues myself via public info and having it teased right in front of me is not fun :(

**Comment by Margen67** [comment]
What OS are you using?

Try using the keyboard and see if that works.

**Comment by dpsman917** [comment]
i tried pressing x for start and every key on the keyboard running windows 10 x64 pro

**Comment by Razzile** [comment]
it's probably a problem with the game. I know doritos crash course wouldn't accept controller input when I tried it, @DrChat would know more than me though

**Comment by Margen67** [comment]
What game is it?

**Comment by dpsman917** [comment]
Blue Dragon disk 1, i was unaware that a game could be the cause, i guess i should have picked any other 2nd try besides the blue dragon demo for troubleshooting lol... its a hidden gem game so i guess it makes sense no one else would have tried to play it.

**Comment by Razzile** [comment]
@dpsman917 blue dragon is the game i want xenia to play most of all, but right now both the arcade demo and disc crash. One day ;-;

**Comment by dpsman917** [comment]
@Razzile i can assure you the latest xenia from vulcan branch i belive can fully load blue dragon you simply cannot play, for reasons i assume is because blue dragon was not programmed with xinput.
