### ISSUE TITLE
Blue Dragon Game incompatibility

### ISSUE THREAD

**Issue by dpsman917** [benvanik/xenia#581]
<img width="960" alt="new bitmap image" src="https://cloud.githubusercontent.com/assets/10163906/16063279/5c8adaa4-3266-11e6-8e42-862d1b1d7bde.png">

Xenia log
[xenia.txt](https://github.com/benvanik/xenia/files/315152/xenia.txt)

Also i left game open for over an hour and the cinematic that is supposed to start while afk on title screen never starts. im giving up on this for now but i figured i should give you guys this info, hope it helps =)

**Comment by x1nixmzeng** [comment]
The sourcecode (`xenia_main.cc`) shows xenia supporting 3 input systems.

Try adding this line to `scratch/flags.txt`:

    --hid=winkey

**Comment by Razzile** [comment]
this blue dragon problem is probably the game's fault and not xinput

**Comment by Margen67** [comment]
Game-specific issues belong on https://github.com/xenia-project/game-compatibility/
