### ISSUE TITLE
CPU leak 50% idle?

### ISSUE THREAD

**Issue by thx4ever** [benvanik/xenia#585]
When i start the emulator, in open file dialog it are using 58% of my CPU withou gaming
![resources](https://cloud.githubusercontent.com/assets/7145630/16179473/5e94c30c-363d-11e6-945c-8c2cda211451.jpg)
Is that normal or its a bug?

**Comment by Razzile** [comment]
did some profiling

![image](https://cloud.githubusercontent.com/assets/5256381/16179549/fdbb180a-3660-11e6-9547-7d068ac719d6.png)

not sure how accurate this actually is

**Comment by DrChat** [comment]
As of now, this is normal. Two threads are spinning even when they have no work to do (xma and gpu).

The GPU thread can't wait on any events as the overhead of waiting takes too long, but XMA can be improved.

**Comment by DrChat** [comment]
Fixed as of d9b52d1afa7ef9100c415b35d96f16e59238affe.
