### ISSUE TITLE
support fatx

### ISSUE THREAD

**Issue by woody2014** [benvanik/xenia#587]
Is it a pipe dream or can it be implemented.

**Comment by Razzile** [comment]
This is remarkably vague, could you explain in more detail.

**Comment by theoldsport** [comment]
Oh you mean you have a USB formatted to FATX? the proprietary Xbox filesystem format

**Comment by jackchentwkh** [comment]
theoldsport <notifications@github.com> 於 2016年6月21日 星期二寫道：

> Oh you mean you have a USB formatted to FATX? the proprietary Xbox
> filesystem format
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/benvanik/xenia/issues/587#issuecomment-227399627>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/APnC7djyJUpd-lrNyP5rTAEjWY_tID7nks5qN7r_gaJpZM4I6gxW>
> .
>


-- 
thanks and regards!

Jack Chen
Substrate sales and tech. service
YXsemicon Ltd.
Cell: +886-933311773
Office:+886-7-7536832
Fax:+886-7-7431976

**Comment by woody2014** [comment]
i mean is it possible for someone to code xenia to use fatx,if someone were to have a usb stick with it fromated by xbox

**Comment by woody2014** [comment]
fatx explorer can see file can it not?

**Comment by theoldsport** [comment]
So are you trying to read straight off a FATX USB or a FATX image file on a FAT32 USB?

**Comment by 0xdeafcafe** [comment]
If you want to extract files from a fatx device, you can just use https://github.com/landaire/Up by @landaire. I recall @benvanik saying he didn't want/had no plans to support fatx device reading in Xenia, but I could be wrong.

**Comment by Razzile** [comment]
admittedly xenia supporting FATX would be useful, but I'd rather xenia focused more on running games now and maybe add fatx support when it's much more developed

**Comment by woody2014** [comment]
i shall close this issue if devs do not want to add it.
