### ISSUE TITLE
'OpenGL Graphic Problem' 

### ISSUE THREAD

**Issue by SakataGintokiYT** [benvanik/xenia#590]
Build : [212cd6e]

Naruto Generations :
*Log :{ 2GB -->20MB } http://www16.zippyshare.com/v/4wArLJ6k/file.html
*Shader_Cache :{ frag / vert } https://mega.nz/#!McwynYRI!ML2SX07iAKgxafy-BehMWRuyKU6BAXnWxiwWKIWpwnc

Problem in games :
-Iron Man 1 {Intro }
-Asterix at the Olympic Games
-Dragon Ball Z: Burst Limit  { Intro }
-The Legend of Spyro: Dawn of the Dragon
-Dragon Ball Z Budokai HD Collection
-Naruto Shippuden Ultimate Ninja Storm 2
-Naruto Shippuden: Ultimate Ninja Storm Generations
-Naruto Shippuden Ultimate Ninja Storm 3
-Naruto Shippuden: Ultimate Ninja Storm Revolution

<img src="http://www.fotoszok.pl/upload/80a1b04f.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/e4547e24.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/ae44a888.png" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/6fe69be6.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/ecdae372.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/e958abea.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/51dcbef1.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/e86e29f3.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/862b207f.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/29f57a58.jpg" alt="Fotoszok.pl" />

**Comment by ScorchEmber256** [comment]
@DrChat 
@SakataGintokiYT 
@benvanik 
Its interesting to see that this problem affects mainly smooth models. Could be worth looking into.
