### ISSUE TITLE
R9 280X OpenGL Issue

### ISSUE THREAD

**Issue by DJEwan** [benvanik/xenia#593]
I'm using xenia from June 21 2016 and I'm using an R9 280X with Driver Packaging Version
15.30.1025.1001-151129b-297237E and OpenGL® Version
6.14.10.13416. Geeks3D GPU Caps Viewer says I have OpenGL 4.50. Xenia says that I need OpenGL 4.50 to run it, but my card clearly supports it.

**Comment by Razzile** [comment]
can you check that your current driver also supports GLSL 4.50 too

**Comment by DJEwan** [comment]
I did a driver update and now it works
