### ISSUE TITLE
Support CPU extension SSSE3 like RPCS3

### ISSUE THREAD

**Issue by zminhquanz** [benvanik/xenia#603]
RPCS3 Emulator is support SSSE3 is minimum to run it , Xenia system requirement too high and not support it

**Comment by gibbed** [comment]
Xenia is not RPCS3, system requirements will always differ.

I personally have no plans to work on reducing system requirements, not sure about other contributors.

**Comment by Blackbird88** [comment]
By the time Xenia will actually be able to emulate most games decently that CPU of yours will be severely outdated anyway.

**Comment by ikki84** [comment]
By the time, lots of things potentially will happen.
I think that most of users are just expecting to see progress related to the issues about (AMD Videocards/ OpenGL and Vulkan backends).

**Comment by CyberPhy** [comment]
it would be nice to have SSSE3 on xenia

**Comment by hlide** [comment]
Why?  what might SSSE3 bring up that it would be nice? SSE-like and AVX-like instructions should not be mixed in the code or they will suffer big latencies. I don't know if Xenia has lowered requirement. If not, SSE3 is totally unrelevant.

**Comment by Margen67** [comment]
@CyberPhy It would be nice to have you upgrade your CPU.

**Comment by akaltar** [comment]
Exactly what parts of the code would require an alternate SSSE3 version to not require AVX? I would be interested in contributing, but my computers don't have AVX.

**Comment by olodar** [comment]
> @CyberPhy It would be nice to have you upgrade your CPU.

it would be nice to give us money for upgrade CPU, otherwise this is empty talking
