### ISSUE TITLE
Xbox 360 discs.

### ISSUE THREAD

**Issue by CGWatkins** [benvanik/xenia#606]
Hi, I was just wondering if and how you can use xbox 360 discs on xenia? I go to open the files in the disc drives and nothing happens. Please help.

**Comment by Razzile** [comment]
you can't open the disc directly. please follow[ this tutorial ](https://www.reddit.com/r/emulation/comments/4uxeo0/how_to_rip_your_xbox_360_and_xbla_games_for_use/)for how to play your xbox games in xenia

**Comment by DrChat** [comment]
Xbox 360 discs are unreadable by normal drives due to a layer of protection on the xbox DVDs themselves.
Even the Xbox One can't read these discs.

**Comment by allbombson** [comment]
but xbox ones can run 360 games

**Comment by mirh** [comment]
Kreon and 0800 drives aren't that impossible to get. 
And at least once upon a time the dual layer dvd swap trick used to work with every reader. 

It's not really a tragedy to wait 10-20 minutes for the ripping, but it would be cool if I could just place a disk in my SH-D162D and play it immediately like it was the real thing.
