### ISSUE TITLE
Drag'n'drop file into program window

### ISSUE THREAD

**Issue by TotalCaesar659** [benvanik/xenia#614]
Hello, could you make the ability to drag'n'drop files into main window of Xenia for launch? I'm used to drag'n drop files between programs, and Xenia doesn't have this ability.
![0000](https://cloud.githubusercontent.com/assets/14265316/18258238/8bcc33b6-73da-11e6-99a5-e1561ffd1482.jpg)

**Comment by DrChat** [comment]
Should be fairly easy to do. I can leave this open for anyone willing to tackle this (aka I'm gonna be lazy).

**Comment by Parovozik** [comment]
Hey. But Drag'n'Drop works if you make this direct to xenia.exe ;)

**Comment by TotalCaesar659** [comment]
@Parovozik, I know, but I used to throw files from one window to other, as well as in Total Commander. And it's more comfortable to target the file to big window than to xenia.exe. So I think this idea is useful.

**Comment by Margen67** [comment]
Fixed by https://github.com/benvanik/xenia/commit/e3ac7bdae883b2bff3f0ac3d63e9561388e1dddd
