### ISSUE TITLE
Vulkan Issue - BSOD while testing certainly games (DRIVER_IRQL_NOT_LESS_OR_EQUAL)

### ISSUE THREAD

**Issue by JohnGodgames** [benvanik/xenia#615]
After vulkan was merged to master, I'm getting this BSOD in certain games.Tested also on older or newest nvidia drivers...the same.

**PC specs:**
CPU - Intel Core i7 6700K @ 4.60 Ghz
RAM - 32 GB DDR4
GPU - GeForce GTX 1080 G1 Gaming 8GB
OS  - Windows 10 64bit

**Known games:**
- 0 day Attack on Earth

![dump](https://cloud.githubusercontent.com/assets/11453507/18347733/7384a4c0-75c7-11e6-910f-2d637c25e420.PNG)

[Minidump download](https://mega.nz/#!3AUi1DbC!L7DCG8VaVL6efB3yRlGs_OydxVwdST1rkEBK1YPcE2I)

**Comment by Nukem9** [comment]
This is a bug in nvidia's driver...it essentially calls a null function pointer and brings down the system. I don't see how this is relevant to xenia.

**Comment by JohnGodgames** [comment]
Tested again on latest master + latest drivers 372.70 and it's ok now...hmm
