### ISSUE TITLE
Xenia latest builds blue textures in dragon ball z and BRICK dante´s inferno

### ISSUE THREAD

**Issue by samipower** [benvanik/xenia#616]
Xenia latest builds blue textures in dragon ball z and BRICK dante´s inferno and blue textures.

in xenia past builds  dante works well but only  black/white textures.

**Comment by CorpenEldorito** [comment]
This is the wrong place for game related bugs.

**Comment by Parovozik** [comment]
Dante Inferno works without change. Just Default api now this Vulkan, and before this OpenGL. Use key --gpu=gl4 for use OpenGL

**Comment by Margen67** [comment]
#578
