### ISSUE TITLE
No Python Installed Error? What Path?

### ISSUE THREAD

**Issue by Johnmakuta** [benvanik/xenia#618]
Hi, sorry that I'm an absolutely infant when it comes to programming (I'm best with Java currently). I wanted to mess around with Xenia so I installed Python 2.7 and uninstalled 3 just encase it  would cause any issues but now I get this error in cmd:

```
ERROR: no Python executable found on PATH.
Make sure you can run 'python' or 'python2' in a Command Prompt.

Python 2.7 must be installed and on PATH:
https://www.python.org/ftp/python/2.7.9/python-2.7.9.msi
The system cannot find the batch label specified - exit_error

```
What path should it be installed on?

**Comment by rlabrecque** [comment]
Have you restarted after installing Python?

**Comment by Razzile** [comment]
also possible python isn't in your PATH environment variable

**Comment by Johnmakuta** [comment]
@rlabrecque Have not restarted. I'll do that and try again.

**Comment by DrChat** [comment]
Made a workaround for this in 3b7002e945d077ca05693f2b8f25b30ad4fb1627.
