### ISSUE TITLE
Switching active title .xex from default.xex

### ISSUE THREAD

**Issue by XeClutch** [benvanik/xenia#621]
Say you're in the menus of COD4 and you go down to switch to multiplayer. Normally on console this would launch default_mp.xex. When doing this on xenia it just locks up. The only way to get into multiplayer is to launch specifically from default_mp.xex. You cannot do it from inside the default.xex.

**Comment by Nukem9** [comment]
https://github.com/benvanik/xenia/issues/591 (fyi)

**Comment by DrChat** [comment]
Yeah - duplicate of #591
