### ISSUE TITLE
Green lines, Graphics fucked

### ISSUE THREAD

**Issue by jordanwilliams1** [benvanik/xenia#623]
Trying to play black ops 2 on xenia.

Getting weird green lines
https://i.gyazo.com/f0535a593b59b8085c889ffb6df8ae6c.jpg

**Comment by Margen67** [comment]
What kind of graphics card are you using?
What is the version of the graphics driver?
Do other games work?

**Comment by DrChat** [comment]
Wrong place for game issue reports.
