### ISSUE TITLE
Wish lower GPU required.

### ISSUE THREAD

**Issue by fuhuan416** [benvanik/xenia#625]
I has a GPU supported with OpenGL 4.3 and DX 11.1, and i want to play some 2D's game, just like 'Castlevania:Harmony of Despair'. Any ideas to do this guys?

**Comment by JoaRiski** [comment]
I'm fairly confident there are no plans of extending compatibility currently, as there are more important things that need to be worked on. It is an open source project though, so feel free to submit a PR

**Comment by Margen67** [comment]
Get a better graphics card.
