### ISSUE TITLE
graphic problem with Vulkan (TloS)

### ISSUE THREAD

**Issue by Felixkruemel** [benvanik/xenia#626]
If I try to play TloS with gl4 it works, but it has no playable performance (0.6fps). If I try to play it with Vulkan I get Graphic Erros (Screenshot http://www36.zippyshare.com/v/bDHOdES1/file.html). Here is the log: http://www36.zippyshare.com/v/taZAuZGd/file.html (unzipped 25MB)

I haven't found any discussion about that in the issue pages, so I made this. 
Is that the right place for it?

**Comment by Margen67** [comment]
No. Game compatibility reports go in https://github.com/xenia-project/game-compatibility/
