### ISSUE TITLE
Vulkan - Support indexed vfetches

### ISSUE THREAD

**Issue by SakataGintokiYT** [benvanik/xenia#628]
Problem: The Vulkan backend does not support indexed vfetches

9457c63a / f5168c57

**Ice Age: Dawn of the Dinosaurs**
<img src="http://www.fotoszok.pl/upload/eb49248c.jpg" alt="Fotoszok.pl" />
**[Dump frames](https://mega.nz/#!9UZmWQ6I!vUfYL0kwe-MhH_OR7fEWCn0pEKRdEe4Uw6rxV9tgNr4)**

---------------------------------------------------------------------------------------------------------------

**Bakugan Battle Brawlers**
<img src="http://www.fotoszok.pl/upload/aac8dcd9.jpg" alt="Fotoszok.pl" />
**[Dump frames](https://mega.nz/#!5JgUGbza!a9f26nOlF9Za7eXS2E-N5TV9Q4v1xJW4QAJf6zwsw08)**

---------------------------------------------------------------------------------------------------------------

**Fist of the North Star**
<img src="http://www.fotoszok.pl/upload/257c01ab.jpg" alt="Fotoszok.pl" />
**[Dump frames](https://mega.nz/#!dBQyiT7L!cJ3aSKdOX6vsMSz4Xf8lxYUr3byiAFyx8UdUH42S-IM)**

**Comment by DrChat** [comment]
Yeah - there's still a fairly huge issue: We don't support vertex fetching via arbitrary indices. That kind of breaks a lot of games.

**Comment by Felixkruemel** [comment]
Is this planned for the future, or Is it to hard to code?

**Comment by DrChat** [comment]
Both.

**Comment by sabretooth** [comment]
I had a quick look at Ice Age: Dawn of the Dinosaurs since I have that title laying around. The game doesn't use indexed fetch for its smooth-skinned meshes. They render just fine in the GL4 backend, but are distorted on Vulkan. My guess is that the shader is being mistranslated for SPIRV; I'll look into it more later.

**Comment by DrChat** [comment]
This (indexed vfetch) has been fixed as of 1a263f14a2dfcd3c56c170a7d95cabaa880b77a2.
