### ISSUE TITLE
Over G Fighters not getting past intro screen

### ISSUE THREAD

**Issue by AXMiller96** [benvanik/xenia#632]
I have tried to get Over G Fighters to work (specifically got Xenia to try and play this game on PC). I have got the .000 file which I rename to .iso. Then I drag it into xenia.exe and it runs.
The first intro screens (developer logos i.e. ubisoft) run fine, then the intro movie plays. The screen cutts and does all these weird things through the movie. After that the start screen pops up but.. it has no writing at all, just the start screen image. Normally it should have OVER G FIGHTERS in big letters, along with some text. I click start and then the screen dims, and it stops there. 
Am I doing something wrong here? I've checked the compatibility page, and Over G Fighters isn't mentioned, but there is a youtube video of someone testing it, and getting to the start screen (with words on it).

**Comment by Razzile** [comment]
this is the wrong place for game related issues, please make an issue [here](https://github.com/xenia-project/game-compatibility/)
