### ISSUE TITLE
I get an error even though I have met the proper requirements.

### ISSUE THREAD

**Issue by yeom48274** [benvanik/xenia#633]
Hello. When you start Xenia, the message "Unable to initialize Vulkan Graphics Subsystem" emerges and Xenia does not start. This message is displayed even though I properly meet Xenia's system requirements, so what should I do? Thanks in advance!
`i> 000003E4 Build: detached / e3ac7bdae883b2bff3f0ac3d63e9561388e1dddd on Nov 17 2016
i> 000003E4 Initializing Vulkan 1.0.0...
i> 000003E4 Found 1 global layers:
i> 000003E4 - VK_LAYER_NV_optimus (spec: 1.0.24, impl: 0.0.1)
i> 000003E4   NVIDIA Optimus layer
i> 000003E4 Found 4 global extensions:
i> 000003E4 - VK_KHR_surface (0.0.25)
i> 000003E4 - VK_KHR_win32_surface (0.0.5)
i> 000003E4 - VK_EXT_debug_report (0.0.4)
i> 000003E4 - VK_NV_external_memory_capabilities (0.0.1)
i> 000003E4 Verifying layers and extensions...
i> 000003E4 - optional extension VK_EXT_debug_marker not found
i> 000003E4 - enabling extension VK_KHR_surface (0.0.25)
i> 000003E4 - enabling extension VK_KHR_win32_surface (0.0.5)
i> 000003E4 Initializing application instance...
i> 000003E4 Debug validation layer not installed; ignoring
i> 000003E4 Found 0 physical devices:
i> 000003E4 RenderDoc support requested but it is not attached
i> 000003E4 Instance initialized successfully!
!> 000003E4 No devices available for use
X> 000003E4 Unable to initialize Vulkan graphics subsystem.
Ensure you have the latest drivers for your GPU and that it supports Vulkan. See http://xenia.jp/faq/ for more information and a list of supported Gpus.`
`

![default](https://cloud.githubusercontent.com/assets/23091729/20453569/08d22a1a-ae6d-11e6-9b07-bc69d1868f3f.JPG)

**Comment by Razzile** [comment]
do you have vulkan drivers? xenia by default uses vulkan now instead of OpenGL 4.5

**Comment by Nezarn** [comment]
@yeom48274 GTX 550ti doesn't support vulkan, run xenia with --gpu=gl4

**Comment by SaifAlSubhi** [comment]
You will get the same error with nVidia GTX 980 Ti while VulkanRT Libraries 1.0.51.0 is installed and even with older version.

**Comment by SaifAlSubhi** [comment]
`i> 00003A58 Build: detached / ca729404ea32ff62b1cba58d8b55c4e09b0593ce on Jun 28 2017
i> 00003A58 Initializing Vulkan 1.0.0...
i> 00003A58 Found 2 global layers:
i> 00003A58 - VK_LAYER_NV_optimus (spec: 1.0.49, impl: 0.0.1)
i> 00003A58   NVIDIA Optimus layer
i> 00003A58 - VK_LAYER_VALVE_steam_overlay (spec: 1.0.3, impl: 0.0.1)
i> 00003A58   Steam Overlay Layer
!> 00003A58 Vulkan check: vkEnumerateInstanceExtensionProperties returned VK_ERROR_INITIALIZATION_FAILED
!> 00003A58 Vulkan check: vkEnumerateInstanceExtensionProperties returned VK_ERROR_INITIALIZATION_FAILED
i> 00003A58 Found 0 global extensions:
i> 00003A58 Verifying layers and extensions...
i> 00003A58 - optional extension VK_EXT_debug_marker not found
!> 00003A58 ERROR: required extension VK_KHR_surface not found
!> 00003A58 ERROR: required extension VK_KHR_win32_surface not found
!> 00003A58 Layer and extension verification failed; aborting initialization
!> 00003A58 Failed to create instance
!> 00003A58 Failed to initialize vulkan instance
X> 00003A58 Unable to initialize Vulkan graphics subsystem.
Ensure you have the latest drivers for your GPU and that it supports Vulkan. See http://xenia.jp/faq/ for more information and a list of supported GPUs.
`
