### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by Margen67** [benvanik/xenia#634]
Since people can't read there should be a message in the issue template saying something like "Game compatibility reports don't go here; To make a game compatibility report go here instead: https://github.com/xenia-project/game-compatibility/"
It should probably be put in contributing.md as well.

**Comment by TotalCaesar659** [comment]
This is a great idea! Let me upgrade it: there are text fields may be placed into the main window of Xenia (it's empty now): the game and its code may be picked up automatically from the file after launch, and the fields of state and issues can be filled by the player. And the button "Send to the database")))

**Comment by DrChat** [comment]
Someone can open a pull request with a template, and if it looks good I'll pull it :)

**Comment by Margen67** [comment]
Possibly solved by https://github.com/benvanik/xenia/commit/9903ed687939843be0516ebda34a69be2a9dff0d

**Comment by DrChat** [comment]
Yep

**Comment by Margen67** [comment]
"(If applicible, upload a logfile and link it here)"
It should be "applicable"
