### ISSUE TITLE
Start Xenia in Fullscreen

### ISSUE THREAD

**Issue by GamerDude27** [benvanik/xenia#635]
So I've been digging around under the skin of Xenia to possibly find a launch parameter like **--fulscreen** to start Xenia in fullscreen mode, but I just couldn't find anything during my attempts. I've tried window explorers, code digging and whatnot but with no success. At this point I'm lead to believe there is no way to do this, I even tried to make a AutoHotKey script to send the key press F11 on startup, but that didn't work either.

The reason for wanting Xenia to run in fullscreen mode on startup is because I'm using both Steam Big Picture and LaunchBox to run my emulators, and I have a startup parameter or a work around to run every emulator I have to run in fullscreen on startup except Xenia.

I'd very much love if you'd add a startup parameter to Xenia or point out the correct parameter to use if there already is one.

Thank you

**Comment by DrChat** [comment]
Fairly trivial to implement.

**Comment by Margen67** [comment]
What about resolution options? 1080p, 720p, etc.

**Comment by DrChat** [comment]
Xenia runs at 720p always at the moment.

**Comment by TotalCaesar659** [comment]
https://github.com/benvanik/xenia/pull/644
This issue may be closed, I guess.

**Comment by DrChat** [comment]
Indeed 👍

**Comment by shanethmoore** [comment]
Looks like this has reverted.

**Comment by Aleksey-Kon** [comment]
> Похоже, это вернулось.

is it possible now to make xenia when running on full screen?

**Comment by Triang3l** [comment]
`--fullscreen=true`

> > Похоже, это вернулось.
> 
> is it possible now to make xenia when running on full screen?

`--fullscreen=true` works for me in the latest `master` branch version.

**Comment by GermanChap** [comment]
> > > Похоже, это вернулось.
> > 
> > 
> > is it possible now to make xenia when running on full screen?
> 
> `--fullscreen=true` works for me in the latest `master` branch version.

This 100% worked for me. Thank you.

I've added it as an application parameter for my Launchbox instance and boom, works.

Thank you for this.
