### ISSUE TITLE
i7 6700 CPU RX 460 4GB Sapphire Will by support ? in Future ?

### ISSUE THREAD

**Issue by zerr10** [benvanik/xenia#636]
hi my PC : 

i7 6700 3.4 Ghz Skylake RAM DDR4 2133 MHZ dual RX 460 4GB is full support Open gl 4.5 but xenia no work...

work only 1 version **Xenia-20160621-x64**  but crash after intro for all games , other version no work...
pls help. :( 

i test new version but crash all time even the intro does not work

**Comment by Krakn** [comment]
https://github.com/benvanik/xenia/blob/master/CONTRIBUTING.md

**Comment by zerr10** [comment]
sorry but i dont understand... i low speak english...

**Comment by SakataGintokiYT** [comment]
@zerr10 
At the moment, AMD graphics cards are not supported

**OpenGL 4.5 Black Screen on AMD Cards :** https://github.com/benvanik/xenia/issues/563
**Vulkan Issues / Discussion:** https://github.com/benvanik/xenia/issues/578

**Comment by zerr10** [comment]
:(   i'm crying... but in futur will by support ?

**Comment by Felixkruemel** [comment]
AMD Cards have no really good Driver die Vulkan. It will never be supported unless AMD does something with there drivers...

**Comment by MoochMcGee** [comment]
>AMD Cards have no really good Driver die Vulkan.
>no really good Driver die Vulkan.
>Driver die Vulkan.
>die Vulkan.

WELP, YOU HEARD IT HERE

**Comment by Nezarn** [comment]
@Felixkruemel so if AMD already kills nvidia in Vulkan performance with shit drivers (just look at DOOM, novideo(nvidia) is nowhere near AMD in performance), what will happen when AMD gets good Vulkan driver? lel

**Comment by DrChat** [comment]
Xenia will receive support on AMD as soon as I acquire an AMD card or another developer steps in.
