### ISSUE TITLE
Crash on Vulken backend on AMD GPU (R9 390 16.11.5)

### ISSUE THREAD

**Issue by shadowbrony33** [benvanik/xenia#640]
[xenia.log.txt](https://github.com/benvanik/xenia/files/626279/xenia.log.txt)

Xenia crashes when attempting to load/render game

**Comment by neolightning** [comment]
AMD Vulkan does work, its a issue only with Xenia right now, we think it may have something to do with DRM, etc

**Comment by Nukem9** [comment]
https://github.com/xenia-project/game-compatibility
https://github.com/benvanik/xenia/issues/636#issuecomment-262523812

It's probably nothing to do with DRM.

**Comment by shadowbrony33** [comment]
Currently the main contributers do not own AMD GCN GPUs so they cannot fix the issues with AMD cards as of right now.

**Comment by neolightning** [comment]
I would love to try and fix it, but i am a complete noob at c++, i am willing to try AMD Vulkan Test builds tho

**Comment by DrChat** [comment]
This is a known issue - I cannot fix this myself though.
