### ISSUE TITLE
Several Game Issues

### ISSUE THREAD

**Issue by Kokujou** [benvanik/xenia#642]
Build: af8e231 (at least that's what it says from the title line)
Fable 2:
Error: Boots up some dev logosbut than crashed "guest has crashed, paused itself, details written to the log" 
Asuras Wrath: Loading gif, then freeze, no crash
Tales of Vesperia: boots up some dev logos but than hangs and windows-crashes. (gets white and has to be destroyed)

i would post the .log file but its 498MB. but if it'd be a help i'd upload it to Share-Online

**Comment by robert-7** [comment]
This seems like it's game specific, and so issues should be documented here: https://github.com/xenia-project/game-compatibility/issues. In fact, tack it on to this if it's relevant: https://github.com/xenia-project/game-compatibility/issues/205
