### ISSUE TITLE
Vulcan rx 460 4GB i7 6700 3.4ghz Xenia no work

### ISSUE THREAD

**Issue by zerr10** [benvanik/xenia#647]
work only command --gpu=null but only sound in sonic , and command --gpu=gl4 work sound + secren but work only 1 game sonic and very bug. graphic... amd card will by suport ?

vulcan all time crash,
one game work sonic

**Comment by Razzile** [comment]
yes

**Comment by maxton** [comment]
Again, the developers are well aware of the issue with AMD cards, but none of the developers have an AMD card to test on. Until there is a developer with an AMD card or AMD fixes their Vulkan drivers this will remain an issue.

**Comment by Margen67** [comment]
https://github.com/benvanik/xenia/issues/578

**Comment by neolightning** [comment]
AMD Vulkan works fine, its Xenia that needs to be fixed, just wait, it will hopefully eventually be fixed
![screenshot_5](https://cloud.githubusercontent.com/assets/6211989/21239999/5b30a826-c2d7-11e6-98cc-a06762134aa4.png)
