### ISSUE TITLE
Some Help Please 

### ISSUE THREAD

**Issue by puffpuffkeep** [benvanik/xenia#651]
Assertion failed!

Program: C:\Users\me\Desktop\xenia.exe
File: ..\third_party\vulkan\loader\extensions.c
Line 123
Expression: icd_term !=NULL &&
icd_term->DebugMarkerSetObjectNameEXT $$ "loader: null
DebugMarkerSetObjectNameEXT ICD pointer"

Anyone know how i can fix this?

**Comment by DPersonalized** [comment]
What are your system specs?

**Comment by puffpuffkeep** [comment]
i7 4790k, r9 290x 8 gigs ram

**Comment by puffpuffkeep** [comment]
I got it to run with a older version of xenia

**Comment by inckie** [comment]
For nvidia, updating display drivers resolved the issue.

**Comment by DrChat** [comment]
Yeah - looks like it's a driver issue. Try updating your drivers - otherwise not a Xenia issue :)
