### ISSUE TITLE
memory.cc Heap exhausted!

### ISSUE THREAD

**Issue by JustinPuksic** [benvanik/xenia#652]
After successfully compiling the App, I loaded a .iso file into the program.
So, the program accepts it and loads the Game Title and Icon successfully and then throws an error and jumps to the line :
```
  if (start_page_number == UINT_MAX || end_page_number == UINT_MAX) {
    // Out of memory.
    XELOGE("BaseHeap::Alloc failed to find contiguous range");
    assert_always("Heap exhausted!");
    return false;
  }
```

Someone knows what causes the error and how to fix it ?

**Comment by Margen67** [comment]
What are your specs?
What game are you trying to run?

**Comment by LastFlux** [comment]
I might be able to add something here.
This error seems to only occur with Halo Reach out of the few games that I have attempted to run. Doesn't matter if gpu is using Opengl or Vulkan, seems to occur before the gpu is initialized. Other games will boot, have sound, and display may or may not work.
Yet other people have been able to boot Reach into a very buggy menu so this might be a game specific bug?

Specs:
i5-3570k OC/4.3GHz
16GB Ram
Radeon R9 290 4GB

**Comment by Margen67** [comment]
Halo Reach crashes for me even with an NVIDIA graphics card, so it's not just you.
It only boots on older commits so the people you're talking about must have been using one.
Since it's an issue specific to that game it should go here: https://github.com/xenia-project/game-compatibility/issues/52
