### ISSUE TITLE
Viva pinata keeps on crashing.

### ISSUE THREAD

**Issue by theknighthodor** [benvanik/xenia#656]
Hi,

I am new to the Xbox 360 emulator and i really wanted to try to play viva pinata 2 without having to buy a xbox so i wanted to try and get a emulator so i got here and now i am trying to run the emulator and i get a error saying this ( screenshot attached) and i wanted to know if it could be easily fixed. I hope someone can help me out. Thanks. 

![7wxxb31](https://cloud.githubusercontent.com/assets/25020029/21789126/ff05c56c-d6d2-11e6-91cc-dd3f1e1196d2.png)

**Ps: where can i find te log so i can attach it.**

**Comment by DrChat** [comment]
Please refer to the [game compatibility repository](https://github.com/xenia-project/game-compatibility/issues) where this game is already posted. (It won't be fixed anytime soon, sorry 👎 )
