### ISSUE TITLE
Delete vulkan branch

### ISSUE THREAD

**Issue by Margen67** [benvanik/xenia#657]
Vulkan has already been merged and the branch hasn't had any changes since then.

**Comment by vgturtle127** [comment]
@benvanik @gibbed @DrChat @Margen67 Maybe they want to keep the branch for future development?

**Comment by DrChat** [comment]
Nope, Vulkan is part of the main repo now.

**Comment by vgturtle127** [comment]
@DrChat Alright, thanks.

**Comment by Margen67** [comment]
What is gh-pages for?

**Comment by gibbed** [comment]
It's for http://xenia.jp/.
