### ISSUE TITLE
Xenia almost instantly crashes after launching anything with --vulkan_native_msaa=true

### ISSUE THREAD

**Issue by Margen67** [benvanik/xenia#658]
Logs:
[Banjo-Kazooie.txt](https://github.com/benvanik/xenia/files/699102/Banjo-Kazooie.txt)
[Minecraft.txt](https://github.com/benvanik/xenia/files/699103/Minecraft.txt)
[N+.txt](https://github.com/benvanik/xenia/files/699112/N.txt)
[BanjoTooie.txt](https://github.com/benvanik/xenia/files/699118/BanjoTooie.txt)

**Comment by NuclearC** [comment]
try to use opengl renderer

**Comment by Margen67** [comment]
@NuclearC Then it wouldn't do anything.
What would be the point?

**Comment by DrChat** [comment]
This was a flag I added to mess around with native MSAA, but I've abandoned it now because it's not as straightforward as I thought it would be.
This can be removed for the time being.

**Comment by Margen67** [comment]
So anti-aliasing/resolution options will be added eventually?

**Comment by rlabrecque** [comment]
Sure why not if someone gets them working?
