### ISSUE TITLE
Direct X 12 Xenia

### ISSUE THREAD

**Issue by Gamedev1909** [benvanik/xenia#660]
More of info regarding Dx12

https://blogs.msdn.microsoft.com/pix/download/ this new tool Helps optimize for dx12 and as most of you know DX12 can be ported to Vulkan as they share many things in common.

So this tool could lead to better vulkan support as proven by decaf who fixed all the opengl issues in a matter of days into coding.

article is here **https://www.neowin.net/news/microsoft-previews-pix-for-windows-10-a-game-analytics-tool**

No hate please take it into account as i will be and if it proves a good tool i will start coding dx12 for xenia down the road thanks all.

**Comment by Margen67** [comment]
I think it would be better to spend time fixing Vulkan instead of creating another renderer.

**Comment by Gamedev1909** [comment]
I am helping on that also but as i said dx12 can help bring a better fixed vulkan

**Comment by NuclearC** [comment]
im sure its too hard to implement dx12 back-end for xenia. But anyway, better to try :D

**Comment by aquaraider11** [comment]
I wouldn't want dx12 back end, but if you want to make one, go for it.

But i too think it would be better to focus on Vulkan as its cross platform, and has features Dx12 simply does not.

Also Vulkan shouldn't be that hard to optimize, as you'll always know exactly everything you have.

Through i m really new / self learned programmer so take everything you hear from me with grain of salt and don't expect much from me :D

**Comment by Gamedev1909** [comment]
Well cool news dx12 went sorta open source

**Comment by DrChat** [comment]
We won't be working on a DX12 backend. As said before, you're free to do so.
