### ISSUE TITLE
When running "Ratatouille" my PC crashes out of nowhere. ending with a BSOD. (Stop error VIDEO_SCHEDULER_INTERNAL_ERROR (119))

### ISSUE THREAD

**Issue by ABlankNam3dKidBugsOnly** [benvanik/xenia#661]
My hardware (If needed)
CPU: i3-2130
GPU: GTX 1050TI (EVGA, SSC, 4GB)
RAM: Team Group ram stick 8GB (unknown) + Samsung 8GB (Both @ 1.6 GHZ)
HDD WD Black 1TB + WD Caviar Green 1TB (Not in raid, one is a backup to save me in the event one commits suicide)
MB: ASUS P8H61-M LE/CSM R2.0

WinDBG analysis says this:

*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

Use !analyze -v to get detailed debugging information.

BugCheck 119, {a, d69, d6a, ffffda0945ec0010}

Page 1c0 not present in the dump file. Type ".hh dbgerr004" for details
Page 1c0 not present in the dump file. Type ".hh dbgerr004" for details
Page 1c0 not present in the dump file. Type ".hh dbgerr004" for details
Probably caused by : dxgmms2.sys ( dxgmms2!VidSchiResetEngine+6ad )

Followup:     MachineOwner
---------

1: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

VIDEO_SCHEDULER_INTERNAL_ERROR (119)
The video scheduler has detected that fatal violation has occurred. This resulted
in a condition that video scheduler can no longer progress. Any other values after
parameter 1 must be individually examined according to the subtype.
Arguments:
Arg1: 000000000000000a, The subtype of the bugcheck:
Arg2: 0000000000000d69
Arg3: 0000000000000d6a
Arg4: ffffda0945ec0010

Debugging Details:
------------------

Page 1c0 not present in the dump file. Type ".hh dbgerr004" for details
Page 1c0 not present in the dump file. Type ".hh dbgerr004" for details
Page 1c0 not present in the dump file. Type ".hh dbgerr004" for details

DUMP_CLASS: 1

DUMP_QUALIFIER: 401

BUILD_VERSION_STRING:  14393.693.amd64fre.rs1_release.161220-1747

SYSTEM_MANUFACTURER:  System manufacturer

SYSTEM_PRODUCT_NAME:  System Product Name

SYSTEM_SKU:  SKU

SYSTEM_VERSION:  System Version

BIOS_VENDOR:  American Megatrends Inc.

BIOS_VERSION:  1414

BIOS_DATE:  09/23/2014

BASEBOARD_MANUFACTURER:  ASUSTeK COMPUTER INC.

BASEBOARD_PRODUCT:  P8H61-M LE/CSM R2.0

BASEBOARD_VERSION:  Rev x.0x

DUMP_TYPE:  1

BUGCHECK_P1: a

BUGCHECK_P2: d69

BUGCHECK_P3: d6a

BUGCHECK_P4: ffffda0945ec0010

CPU_COUNT: 4

CPU_MHZ: d48

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 2a

CPU_STEPPING: 7

CPU_MICROCODE: 6,2a,7,0 (F,M,S,R)  SIG: 29'00000000 (cache) 29'00000000 (init)

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

BUGCHECK_STR:  0x119

PROCESS_NAME:  System

CURRENT_IRQL:  0

ANALYSIS_SESSION_HOST:  AIDENS-HELWETT-

ANALYSIS_SESSION_TIME:  01-19-2017 21:04:24.0275

ANALYSIS_VERSION: 10.0.14321.1024 amd64fre

LAST_CONTROL_TRANSFER:  from fffff802e1af34ae to fffff803f03ce6f0

STACK_TEXT:  
ffff9780`8633a688 fffff802`e1af34ae : 00000000`00000119 00000000`0000000a 00000000`00000d69 00000000`00000d6a : nt!KeBugCheckEx
ffff9780`8633a690 fffff802`e57b4ca5 : 00000000`00000000 ffffda09`450f2290 ffffda09`450f2290 ffffda09`45f10000 : watchdog!WdLogEvent5_WdCriticalError+0xce
ffff9780`8633a6d0 fffff802`e582ee29 : ffffda09`45f10000 00000000`00000000 00000000`00000001 ffffda09`4678a001 : dxgmms2!VidSchiResetEngine+0x6ad
ffff9780`8633a9c0 fffff802`e58137fa : ffffda09`45f10000 00000000`0000000f 00000000`00000000 ffffda09`4678a000 : dxgmms2!VidSchiResetEngines+0x99
ffff9780`8633aa00 fffff802`e579a130 : 00000000`00000000 00000000`00002a36 00000000`0032a9fd 00000000`00000001 : dxgmms2!VidSchiCheckHwProgress+0x2072a
ffff9780`8633aa70 fffff802`e57fec1f : ffffda09`4500cc00 ffff9780`8633abd0 ffffda09`4500cc20 ffffda09`00000000 : dxgmms2!VidSchiScheduleCommandToRun+0x50
ffff9780`8633ab80 fffff802`e57febe0 : ffffda09`4678a500 ffffda09`4678a000 00000000`00000080 fffff802`e57feb60 : dxgmms2!VidSchiRun_PriorityTable+0x2f
ffff9780`8633abd0 fffff803`f0286729 : ffff9780`85420180 fffff803`f03d3adf 00000000`067b892e ffffda09`45eeb800 : dxgmms2!VidSchiWorkerThread+0x80
ffff9780`8633ac10 fffff803`f03d3bb6 : ffff9780`85420180 ffffda09`45eeb800 fffff803`f02866e8 00000000`00000000 : nt!PspSystemThreadStartup+0x41
ffff9780`8633ac60 00000000`00000000 : ffff9780`8633b000 ffff9780`86335000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x16

STACK_COMMAND:  kb

THREAD_SHA1_HASH_MOD_FUNC:  9a1338a4437b37b8e08606e08dd8510005649747

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  a70012e2c3219177d350e9ae02ec6da38cb50068

THREAD_SHA1_HASH_MOD:  3fc6881a98176ffc9fc7ecf208878f0528196cd9

FOLLOWUP_IP: 
dxgmms2!VidSchiResetEngine+6ad
fffff802`e57b4ca5 cc              int     3

FAULT_INSTR_CODE:  468948cc

SYMBOL_STACK_INDEX:  2

SYMBOL_NAME:  dxgmms2!VidSchiResetEngine+6ad

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: dxgmms2

IMAGE_NAME:  dxgmms2.sys

DEBUG_FLR_IMAGE_TIMESTAMP:  584a7bb9

IMAGE_VERSION:  10.0.14393.576

BUCKET_ID_FUNC_OFFSET:  6ad

FAILURE_BUCKET_ID:  0x119_A_DRIVER_REPORTED_INVALID_ABORTED_FENCE_dxgmms2!VidSchiResetEngine

BUCKET_ID:  0x119_A_DRIVER_REPORTED_INVALID_ABORTED_FENCE_dxgmms2!VidSchiResetEngine

PRIMARY_PROBLEM_CLASS:  0x119_A_DRIVER_REPORTED_INVALID_ABORTED_FENCE_dxgmms2!VidSchiResetEngine

TARGET_TIME:  2017-01-20T04:45:38.000Z

OSBUILD:  14393

OSSERVICEPACK:  0

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  784

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS Personal

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  2016-12-20 22:50:57

BUILDDATESTAMP_STR:  161220-1747

BUILDLAB_STR:  rs1_release

BUILDOSVER_STR:  10.0.14393.693.amd64fre.rs1_release.161220-1747

ANALYSIS_SESSION_ELAPSED_TIME: 61c

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:0x119_a_driver_reported_invalid_aborted_fence_dxgmms2!vidschiresetengine

FAILURE_ID_HASH:  {0583d7c3-1bed-bfe8-626e-b1b699451419}

Followup:     MachineOwner
---------

Hopefully the info included will help you fix this glitch that crashes windows! (I assume you know the in and out's of windows 10 & 8.1, so either you fix the bug or tell me to try doing something on my end to fix it)

(File:MEMORY.DMP this file would contain your emu's data, would it?  https://drive.google.com/file/d/0B9v3_yuRUlx3VzdVWVpxMXh4YUU/view?usp=sharing)
Github wont let me upload it.

**Comment by gibbed** [comment]
Given the age of when this was created, it's probably no longer relevant after the changes made for AMD support. If this problem still occurs, please open a new issue with specific version info of what Xenia build/commit was used as well.
