### ISSUE TITLE
About support for SS4 instruccionts,not all SS4 cpus are obsolete

### ISSUE THREAD

**Issue by mrkaratechamp** [benvanik/xenia#666]
Hi, I have a EVGA classified SR-2 With two pair of Xenon x5690 six core, OC to 4.4 GHZ, and 32 GB ram, Nvidia 980 GTX TI, With 24 threads, you will tell me my system is obsolete?? I need to upgrade?!?!, any intel cpu new generation is a joke in terms of performance,  I have no way to spend on a new system, and what can I gain??, AVX instructions?!?!, please, I know this emulator should be to high end systems, but any i7 (first generation included), overclocked to 3.8 or more ghz, is still considered a high end system, with a good motherboard and gpu off couse, so re think about it, because I can be sure my machine is still outperform a lot of i7 5 and 6 gen.

**Comment by resetnow** [comment]
http://xenia.jp/faq/#can-you-add-support-for-windows-me-how-about-my-pentium-ii

**Comment by mrkaratechamp** [comment]
sorry, but this is a joke? PENTIUM 2? are you retarded? I think My system should outperform x99999999999 at yours,  I got a msi laptop with a 960m,  and a i6670, and runs xenia because AVX instructions, but that laptom performance is like 10% of my multi cpu system, so, please, if you will aswerd at least read the thread asshole.

**Comment by resetnow** [comment]
>Support for older operating systems and processors will not be added unless a contributor steps up to build and maintain them
>contributor steps up to build and maintain them

**Comment by mrkaratechamp** [comment]
I'm never talking about older operatings system, I totally agreed windows 8 or 10, is the way to go, but What I'm telling it's a xenon SIX CORE processor is not a OLD processor, it's a processor than still outperfom any i7 4 cores from 4 or 5 gen, so, considered a processor old because it's not have AVX instruccions it's a wrong way to go, that's I trying to say, and that's why ps3 pcsx3 emulator considerer ss4 instruccions as well, don't paste me useless and generic info, I write about a very specific and a true reality of many users, why in the hell people with i7 six cores hardware and more than 4 ghz will considered their system obsoletes?? because this emulator?? please...

**Comment by raynebc** [comment]
Just because you don't like an answer doesn't make it wrong.  Whining is not going to resolve this in your favor.

**Comment by paulsapps** [comment]
What resetnow is trying to say is:

```Support for older operating systems and processors will not be added unless a contributor steps up to build and maintain them
contributor steps up to build and maintain them```

**Comment by mrkaratechamp** [comment]
please read about the benchmark of i7 over the time... (not 2.6 1 gen vs 3.8 5 gen, but equall ghz, I mean an oc i7 1 gen to 4 gb, vs 6 gen i7 4ghz), you will be surprice...,  with my machine there aren't absolute nothing than a i7 new gen can compare it, the only update possible is get a dual cpu machine, and get the new xenon generation, spend more than 4000 usd, to gain... 7 % performance.... that is smart to you?,

with gpus, I can fully understand they pass obsolete, with amd cpus too, If I have a intel core quad, and I talk about performance, I can understand too, but i7 architecture is unique, with only a fews improvements over the time, every i7 1 and 2 gen cpu have absoluted nothing old from, and have performance enought to run any, the desition to make AVX only compatible is just wrong, because the performance you will gain using date vectors is absurd low, have you seing the benchmarks??,  the only way to boost performance is got high cicles in the cpu frecency, brute force, so leaving a large number of capable cpus out it's just a bad way, and that kind of desitions will make a lot interesting the pcsx3 project, instead of this one, 

it;s a huge difference between obsolete hardware,(hardware that are not capable of do things), and old hardware than in their time was too expensive to get (yes, x5690 it's a 2011 cpu, but on 2011 cost about 3000 usd!!!) and still today it's outperform  any new cpu, we are talking about just and instruction added, not about the real capability of the hardware, If you tell me a i7 4770k 4 cores is better than a xenon x5690 six cores oc to 4.4 ghz... well, then all benchmarks are wrong too,

it's really a shame look how the people think here.... I came thinking this was an interesting project but well... the truth is pscx3 was a lot superior, and I think microsoft was working on a 360 emulator for pc too so... when it's come, I will sure it will work at 100% on my system, because... well, it; capable to move any at 100%. so, good luck, you guys kill the project by yourself.

**Comment by Inifield** [comment]
I don't think you understand how this work, they are not getting paid to work on this emulator, they are doing it for fun and learning, not for you. If they don't want to support something it's their right and if you are not happy about it feel free to implement SS4 and whatever you want and submit a PR, and don't give me that "its a shame people don't think like me blah blah" you didin't even contribute and you're rude to everyone

**Comment by gibbed** [comment]
> All active contributors are on modern systems and busy with higher priority tasks.
If you want to contribute support for SSE4, then by all means.
