### ISSUE TITLE
xenia crash

### ISSUE THREAD

**Issue by ghost** [benvanik/xenia#668]
Hi guys, i downloaded top spin 4 xbox 360 version: iXtreme (6th wave), and downloaded latest update xenia emulator, but loading screen after game crashed and fonts changed like that;
![xen111](https://cloud.githubusercontent.com/assets/25799768/22985741/03c2bef6-f3b2-11e6-94c4-0f786ff056b4.jpg)

I would be glad if you help, thanks.

**Comment by resetnow** [comment]
game-specific issues should be reported to https://github.com/xenia-project/game-compatibility
