### ISSUE TITLE
Dead or Alive Extreme 2 doesn't work on my computer.

### ISSUE THREAD

**Issue by GreecetedFate** [benvanik/xenia#669]
![1](https://cloud.githubusercontent.com/assets/25829223/23038940/788a9e9c-f494-11e6-9138-e86ee396b490.png)
![2](https://cloud.githubusercontent.com/assets/25829223/23039035/cf6f87fe-f494-11e6-8134-1460acd070a1.png)

Images are inverting and it just turns off after loading.

+ Sorry for my english because I'm not good at it.

**Comment by maxton** [comment]
To quote the issue template which you somehow haven't read:

> DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
> a game specific issue would be e.g. "Game X crashes after you hit a character a certain way"
> A Xenia issue would be e.g. "Kernel export NtDoSomething does nothing"
> For specific games, visit https://github.com/xenia-project/game-compatibility/issues

Please make an issue at [https://github.com/xenia-project/game-compatibility/issues](https://github.com/xenia-project/game-compatibility/issues)
