### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by azoreseuropa** [benvanik/xenia#671]
Can I compile it for macOS ? You only have Windows and Linux.

**Comment by Razzile** [comment]
i highly doubt it. apart from many OS specific functions not being implemented for mac yet, macOS doesn't even support vulkan (hell it doesnt even support OpenGL 4.5). 
Your best bet for running xenia on a macbook is to install windows on it

**Comment by azoreseuropa** [comment]
Thank you. Makes sense. :)

**Comment by Margen67** [comment]
Duplicate of #596
