### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by Giwayume** [benvanik/xenia#677]
Just a question I'm sure you've gotten before.

Windows 7 has 48% global desktop operating system market usage. 

What made you think it was a good idea to not support half of the desktop computers in the entire world?

**Comment by tetration** [comment]
Probably because windows seven doesnt support direct x 11 nor 12, which
makes it way harder to get a good framerate in games that are already
lagging so much in the emulator.

**Comment by gibbed** [comment]
http://xenia.jp/faq/#why-do-you-need-opengl-45-wont-30-work-fine

**Comment by Giwayume** [comment]
+tetration
LOL DirectX 11 runs on even Vista and DirectX 12 doesn't run on Windows 8, the minimum requirement.

**Comment by Giwayume** [comment]
+gibbed
Opengl 4.5 can also run on Windows 7.
I haven't been given a valid reason here.

**Comment by gibbed** [comment]
See the two links I gave, I have no interest in expanding upon your query when it's already answered by the FAQ.

**Comment by Giwayume** [comment]
Again, it was not explained in the FAQ. There is no technical reason you cannot support Windows 7 with your current technology stack.

**Comment by Razzile** [comment]
apart from API functions used that don't exist prior to windows 8 (for example https://github.com/benvanik/xenia/blob/bc0ddbb05a9872a72d6af0afc5caa464ddb1a417/src/xenia/cpu/backend/x64/x64_code_cache_win.cc#L72) and no dev who has the time to rewrite functions that use these API calls to support windows 7.

If you want support for windows 7 so bad why not work on it yourself?

**Comment by minuteworld** [comment]
I'm pretty sure more people would be able to test your emulator if you supported an os most people used. I'M JUST SAYIN'

**Comment by paulsapps** [comment]
If most people used it then one of them would send a PR to make it work, JUST SAYIN
