### ISSUE TITLE
2d texture in vulkan

### ISSUE THREAD

**Issue by metallicafor1984** [benvanik/xenia#679]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by metallicafor1984** [comment]
Hi mate. I dont know anything about coding but after your recent tweaks in 2d texture in vulkan forza motorsport 3 stoped showing any introes, however  u can still hear the sound. I hope that will be i bit of a help for u. I hope u get it right. good luck:)

**Comment by Margen67** [comment]
If you want to help you can start by reading the issue template.


# DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
# a game specific issue would be e.g. "Game X crashes after you hit a character a certain way"
# A Xenia issue would be e.g. "Kernel export NtDoSomething does nothing"
# For specific games, visit https://github.com/xenia-project/game-compatibility/issues

**Comment by metallicafor1984** [comment]
Sorry  mate. i have  done as u asked
