### ISSUE TITLE
Compiling for Windows 7 

### ISSUE THREAD

**Issue by JaCzekanski** [benvanik/xenia#68]
Hi,
I've cloned this project and tried to build it on my machine using W7 (VS2013), but as I see you're using Windows 8 API functions:
- RtlAddGrowableFunctionTable
- RtlGrowFunctionTable
- RtlDeleteGrowableFunctionTable

Is there any way to implement/replace this functions? I haven't dived into source code to understand what exactly this does (something JIT related, I suppose). Commenting out this functions and changing xinput.lib to xinput_9_1_0 allows Xenia to compile and run, but it crashes during .xex execution.

[edit]
For Windows 7 use XInput from DirectX SDK, not from Platform SDK included with Visual Studio.

**Comment by cyclonmaster** [comment]
Put aside x86 support, but how about win 7 x64 support? I feel it strange that win 7 x64 is not part of xenia support.

**Comment by Blaypeg** [comment]
Hopefully you will be able to upgrade from Win 7 to Win 10 painlessly enough, that would be a simpler solution for most people than try change xenia to work on Win 7, also DX12 on Win 10 wont hurt performance at all.

**Comment by rlabrecque** [comment]
Yeah I looked into this but I'll be upgrading to Windows 10 along with the rest of my friends so I didn't feel that it was worth my time at that point.

And like Blaypeg said benvanik is looking at going DX12 at some point and the backwards compat with even Win8 will stop there at least for a while until Vulkan is out.

**Comment by The-MAZZTer** [comment]
FYI Ben once Windows 10 is released, all 7 owners get a free upgrade (as long as they claim it within a year) so it'll become less of an issue since you can then have a workaround to recommend.

**Comment by mirhl** [comment]
Regardless I'm not going to abandon my metro-free OS. 

And hell, I'm pretty sure it's possible to get even 64 bit XP to work (with v1*x*0_xp platform target)

Now I would understand if you said *this* is a pretty hard to manage (it's NT 5 after all), but I don't see why even Vista support should be a big deal to include. 

It's still supported in latest Windows SDK and (with the exception of XAudio2 perhaps) it's not that big deal to address, at least in pcsx2

**Comment by hlide** [comment]
@mirhl if you want it so badly under Win7, just fork the source, modify it to make it work with Win7 (and know the taste of hell of portability vs. efficiency) and then you'll be qualified to criticize some choices... but now you're not in position to demand anything as such without any contribution.

**Comment by benvanik** [comment]
@mirhl as hlide says, if you want to take ownership of the Windows XP port such contributions would be welcome.

**Comment by sk8rthug** [comment]
Shortly speaking, it should be done for Win7 because it's great and still the most common OS for PC in the world, and Win8 with Win10 are just crap.

**Comment by minuteworld** [comment]
I don't know about that, alot of games are becoming playable on xenia and alot of people are still using windows 7 :/

**Comment by paulsapps** [comment]
Damn how many of these pointless "pls support my OS for free" threads are there? These all need to be closed off. Nothing is stopping you from making it work, don't know how? Pay someone, end of.

**Comment by sgtfrankieboy** [comment]
Windows 7 is outdated and no longer maintained by Microsoft. When Xenia is finished it will be another couple of years.

Making Xenia compatible with W7 is a complete waste of time for the people actually developing it. So either you install Windows 10, or add W7 support yourself.

Please also remember this is a probably hobby for most of the developers, they don't owe you, or anyone else a W7 version.

**Comment by mirh** [comment]
I still haven't got what's the missing piece of the puzzle in W7. 
Anyway, let's please stop rhetoric arguments and live peacefully with either decision any dev will deem better.
