### ISSUE TITLE
Midnight Club LA causes assertion error and warning GPU: Write to unknown register

### ISSUE THREAD

**Issue by theunreplicated** [benvanik/xenia#688]
With the game Midnight Club LA in xenia Debug Mode, I am constantly getting the message:
Assertion false: cs->owning_thread == XThread::GetCurrentThread()->guest_object() all the time.
This seems to correspond to the function RtlLeaveCriticalSection in kernel/xboxkrnl/xboxkrnl_rtl.cc .

Also digging through the logs, I found many entries of the likes:
w> 00000004 GPU: Write to unknown register (1973 = 00010000)
w> 00000004 GPU: Write to unknown register (1964 = 00000001)
w> 00000004 GPU: Write to unknown register (1973 = 00000000)
I thought maybe this could be the reason why e.g. the car models in this racing game are not getting rendered at all,so as if certain data would be stored in the wrong registers. Also I find it strange that this racing game at the first glance seems to be working, it becomes clear that you cannot move your car(not an control issues as person in there is moving according to controls) and even in races enemies don't move so everything is standing still. As the xbox has no physics api, I am guessing this is not an issue with apis, more so an internal bug in xenia(maybe instruction processing bug or race condition).

Apart from that Visual Studio's debug console printed: exception xe::gpu::vulkan::TextureCache::AllocateTexture has returned nullptr , this is because the returned nullptr from allocatetexture is going to be referenced in the function DemandResolveTexture.

**Comment by DrChat** [comment]
See: #610.
