### ISSUE TITLE
Almost every game crashes now 

### ISSUE THREAD

**Issue by tmccaff** [benvanik/xenia#690]
Every game that was somewhat loading, etc crashes with new Xenia Commit 761ae4ee. Not sure why example like Dead Island games was loading, etc now just crashes.

**Comment by resetnow** [comment]
Probably optimizer having a field day with undefined behaviour and stuff

**Comment by Margen67** [comment]
It's actually https://github.com/benvanik/xenia/commit/b40d75aa3dc05d1b5b32af441d818cfe953f15ba

**Comment by DrChat** [comment]
Hmm - can I get a stack trace?

**Comment by tmccaff** [comment]
How do I do a stack trace?

**Comment by tmccaff** [comment]
Seems new commit fixed some issues

**Comment by DrChat** [comment]
Indeed - it was a typo. This appears to be fixed now.
