### ISSUE TITLE
OpenGL freezes Xenia after small amount of time

### ISSUE THREAD

**Issue by spectrumm** [benvanik/xenia#692]
[//]: # When running Xenia with the OpenGL renderer using my AMD Sapphire Radeon 7970, ANY game freezes after about 5 seconds, making testing/playing anything impossible.

[//]: # In theory it should not freeze after a little bit of time when other people dont report it using a game that actually runs well as an example.

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # I have a bunch of logs, if they have VK in the title its Vulkan, so dont worry about that. [Gist's](https://gist.github.com/spectrumm)

**Comment by Margen67** [comment]
OpenGL is depreciated.

**Comment by MoochMcGee** [comment]
@Margen67 *deprecated

**Comment by spectrumm** [comment]
@Margen67 Vulkan never works on anything. I'd love to use what my GPU was made for, but sadly vulkan just doesnt work, like, ever

**Comment by XeClutch** [comment]
Honestly you shouldn't be expecting actually play anything consistently using Xenia but I do somewhat agree that Vulkan needs to be fixed. There are too many instances of color swapping and if just that were fixed we might be able to play a few games.

**Comment by gibbed** [comment]
Too general of an issue to research, need to handle this on a game to game basis.
