### ISSUE TITLE
Last couple of builds fail to launch

### ISSUE THREAD

**Issue by Irixion** [benvanik/xenia#695]
So, getting straight to the point, the last couple of builds don't launch, throwing a "MSVCP140D.dll" is missing from your system. I have the Visual Studio updates installed, but it's still not launching for some reason. Nothing's changed on this machine, and older builds do launch, so I'm not sure what's going on.

**Comment by Razzile** [comment]
this happens when you try to run a debug build of a program compiled with visual studio outside of visual studio. Try building for release mode instead

**Comment by Irixion** [comment]
...Well now I feel like an idiot. Thanks for the heads up! Not sure why I missed that =_=.
