### ISSUE TITLE
Discord for Xenia

### ISSUE THREAD

**Issue by Pirate321** [benvanik/xenia#696]
I'm not sure if i am doing this right, i tried contacting on freenode but i have no idea how that works.

I made discord server for xenia, it's still young but with time it will be better and bigger.   

Here's invite link https://discord.gg/AypM7uN                             

Is there a chance to make it official?

**Comment by Razzile** [comment]
I'm not sure development chat would work in discord but it would be good for the average xenia user to discuss stuff in, maybe then the freenode channel can go back to being developer focused

**Comment by Pirate321** [comment]
I'm not suggesting that devs use discord for development chat, although there could be a channel for devs only, i want this to be for Xenia users, devs can join but don't have to be active all the time, like Nekotekina he's on RPCS3 discord but he maybe responds to one message per day, i need approval from the developers to make this discord server official so that's why i'm here

**Comment by maxton** [comment]
There are already two IRC channels for Xenia on Freenode (#xenia and #xenia-dev), and the issues page for the project is definitely not the place for this kind of discussion anyway.

**Comment by Gamedev1909** [comment]
not everyone likes irc and a dev channel can be restricted by roles to a channel it be the perfect idea

**Comment by Razzile** [comment]
I reckon an (un)official discord for xenia would be a cool idea but only when more progress has been made and progress is more constant

**Comment by Gamedev1909** [comment]
From what ive seen discord’s help more with making progress then anything else
