### ISSUE TITLE
CTRL+O shortcut doesn't function

### ISSUE THREAD

**Issue by raynebc** [benvanik/xenia#698]
I'm finding that when I open Xenia and press CTRL+O, it does not launch the File>Open function even though the File menu indicates that keyboard shortcut is valid.  To rule out an issue with my keyboard (one of those where function lock is forced enabled by default in Windows 10) I verified that this key sequence works in other applications.

**Comment by DrChat** [comment]
Probably wasn't hooked up :P

If you (or someone else) wants to learn a bit, see if you can't hook it up yourself!
