### ISSUE TITLE
Xenia throws an error

### ISSUE THREAD

**Issue by Ezzie1** [benvanik/xenia#699]
Isn't Xenia throws an error, the program start not possible since you do not have ucrtbased.dll, VCRUNTIME140D.dll, MSVCP140D.dll but all require a driver installed.Can you recommend me something ?

**Comment by Margen67** [comment]
Try the Release build instead of the "Checked" build.

**Comment by Ezzie1** [comment]
Tried that but the problem is that ucrtbased.dll VCRUNTIME140D.dll, MSVCP140D.dll in folders or not, but the files VCRUNTIME140.dll, MSVCP140.dll ucrtbase.dll is (

**Comment by Ezzie1** [comment]
And sorry that I write is not understandable, since I Russian and bad speak on English cucumber

**Comment by Razzile** [comment]
https://github.com/benvanik/xenia/issues/695

**Comment by Margen67** [comment]
Regardless you shouldn't download dll files from random sites.
