### ISSUE TITLE
Xenia Won't Launch

### ISSUE THREAD

**Issue by Darth4212** [benvanik/xenia#706]
Whenever I try to launch Xenia nothing happens.

**Comment by ryantuuk** [comment]
When you load it in visual studio, do you see 'xenia-app' in bold?  That's the project you should highlight and then run the local Windows debugger. F5 is the short cut I think.

**Comment by Darth4212** [comment]
Okay so I ran debug and got this
`Line 1468: static vector<string> argvs;`
After that there is a red X and it says

> Exception Unhandled
Unhandled exception at 0x00007FF61F591B90 in xenia.exe: 0xC000001D: Illegal Instruction. occurred

**Comment by Darth4212** [comment]
What does this mean exactly?

**Comment by Razzile** [comment]
what's your cpu?

**Comment by hlide** [comment]
Your cpu is trying to execute an invalid instruction which is either unknown or not supported. Please make a screenshot of your debug finding and your CPU features.

**Comment by DrChat** [comment]
Download [hwinfo64](https://www.hwinfo.com/download.php) and screenshot the CPU window with the list of supported features.

**Comment by iwanttobethebee** [comment]
wow...you all are genuis men

**Comment by iwanttobethebee** [comment]
is the issue solved?

**Comment by DrChat** [comment]
Assuming your CPU doesn't support AVX and closing this one.
