### ISSUE TITLE
Error On Latest 'premake-core' Submodule

### ISSUE THREAD

**Issue by CDAGaming** [benvanik/xenia#709]
[//]: # (Describe what's going wrong:)
During Premake and any Commands related to it, an error related to the premake-core submodule would appear(This is on it's latest changes)
[//]: # (Describe what should happen:)
Premake Commands should function as normal
[//]: # Log:
`Error: ...pos/xenia/third_party/premake-core/src/base/term.lua:8: attempt to index global 'term' (a nil value)`

**Comment by gibbed** [comment]
Xenia has its own fork of premake. Don't try to use the latest one.

**Comment by DrChat** [comment]
Indeed - this error also just appears to be unrelated to Xenia.

**Comment by CDAGaming** [comment]
https://github.com/premake/premake-core/compare/master...xenia-project:master

There is only one file change listed in the diff. It should be able to be updated to latest, unless the current code of xenia has some incompatibility issues, hence this issues making.

Some other submodules ive upgraded had worked fine without any issues
