### ISSUE TITLE
[QUESTION] Access to virtual filesystem / dump files from mem

### ISSUE THREAD

**Issue by PASAf** [benvanik/xenia#711]
Is there way to access virtual filesystem of xenia from Windows? I need access to some files that game creates during boot and can't figure out how to do it.

**Comment by gibbed** [comment]
If it's creating new files you'll find those under the 'content' directory.

**Comment by PASAf** [comment]
There is no 'content' folder created.

**Comment by raynebc** [comment]
My Xenia executable creates a "content" subfolder (relative to the executable itself).  Do you have write permission to the directory containing your Xenia instance?  Is it in a User Account Control protected area of the file system (ie. root of system volume, in 32 or 64 bit "Program Files" directory)?

**Comment by PASAf** [comment]
@raynebc No, it is on D drive, tried run xenia as Administrator. Maybe it is just in mem? Is there any way to view & dump files in virtual filesystem from mem?

**Comment by gibbed** [comment]
There are other tools available to extract content from games. I'd suggest you look into them.

**Comment by PASAf** [comment]
Ok, show me the tool for unpacking Diablo III xbox CPKs (not criware!)

**Comment by gibbed** [comment]
That's going to be game specific and unrelated to Xenia. Without owning that game, I could not tell you what format it actually is. I'd expect it to be a Blizzard proprietary format though, perhaps based on MPQ?

**Comment by PASAf** [comment]
I'd be not mention that, but you've started. I just looking into possibility that Xenia allow more debugging and easy way to explore different game formats.

**Comment by gibbed** [comment]
That's perfectly fine. Just know that unless it's a system/Xbox provided format, that's all effectively transparent to Xenia since the game-specific format handling would be in guest code and emulated.
