### ISSUE TITLE
How can I support this project monetarily?

### ISSUE THREAD

**Issue by Kraahkan** [benvanik/xenia#712]
Hey guys. Appreciate the work you're doing. Anywhere to donate to the project?

Cheers

**Comment by raynebc** [comment]
Not directly as far as I know, but there is a crowd-funding campaign to contribute money towards hardware:
https://fundrazr.com/81DYF1

**Comment by gibbed** [comment]
I think @DrChat already got the AMD video card.

**Comment by raynebc** [comment]
The campaign indicates the surplus is going toward a jailbroken console.

**Comment by sabretooth** [comment]
Jailbroken console, huh? I have an old JTAG-modded Xbox 360 lying around. If that would be of any use to any of the developers, I'd be happy to ship it off; I haven't even turned the thing on in years.

**Comment by DrChat** [comment]
Console is already acquired. I left the fundrazr open if people want to send money my way as a thanks.

As for donations to the project directly, I had some plans but haven't been working on them lately.
