### ISSUE TITLE
Crash after loading any game

### ISSUE THREAD

**Issue by Jhogece** [benvanik/xenia#713]
[//]: # (Describe what's going wrong:)
For example when I load the game Sonic '06 (it happens with all games I want to load), the whole program crashes after maximum drawing half of the loading screen. I fired up vs2017 and it showed that it crashed right after vkQueueWaitIdle (Unhandled exception at 0x00000000529D5B78 (nvoglv64.dll) in xenia.exe).
What was called before was xe::ui::VulkanContext::BeginSwap() and xe::ui::Window::OnPaint().

This is the log from the crash. (The logfile is from the I think latest version)
[xenia.txt](https://github.com/benvanik/xenia/files/1062547/xenia.txt)

I do have tested it on previous versions and it didn't worked out there too.

**Comment by iwanttobethebee** [comment]
can u show me the properties of xenia GL(direct acces) maybe i could help

**Comment by Jhogece** [comment]
What do you mean exactly?

**Comment by Parovozik** [comment]
First write your PC specs
And Sonic 06 not works without custom 'cache' file
Try games as Asterix Olympic Games, Bomberman Live, Spongebob Robotic Revenge, Ice Age 3

**Comment by Jhogece** [comment]
I got an i7-7700k, 16 Gigs of ram and a GTX 1070 inside the machine.

Okay, I'll try those games later..

**Comment by shadowbrony33** [comment]
Build it as release, then Ctrl + F5

**Comment by Banisher-of-Evil-SOUL-24** [comment]
My emulator crashes after a CPU fence exception: -    this            0x0000000000

**Comment by Banisher-of-Evil-SOUL-24** [comment]
This only when I try to boot up FFXIII, my favorite game, PERIOD hehehehehehe
