### ISSUE TITLE
OpenGL extension ARB_bindless_texture is required

### ISSUE THREAD

**Issue by blamboo** [benvanik/xenia#723]
So, I opened up Xenia for the first time and got an error saying "OpenGL extension ARB_bindless_texture is required. Ensure you have the latest drivers for your GPU and that it supports OpenGL 4.5. See http://xenia.jp/faq/ for more information and a listof supported GPUs." So, I check to see if my driver is up to date. It is, I check to see if it supports OpenGL and it does. It's an Nvidia GT 630. I don't understand why it keeps giving me this error. I don't see anyone else having this problem.

**Comment by Nukem9** [comment]
![image](https://user-images.githubusercontent.com/4228359/27071585-8eb6c8a0-4feb-11e7-81c6-2a37c176c564.png)

**Comment by tmccaff** [comment]
OPENGL is deprecated from my understanding. Xenia default is Vulkan. Try using this flag and see what happens. Xenia --gpu=gl4

**Comment by scribam** [comment]
If OpenGL is deprecated, would it be possible to update the System Requirements in the [FAQ](http://xenia.jp/faq/) to reflect this change ?

**Comment by drillsar** [comment]
I am sure it's being worked on.

**Comment by drillsar** [comment]
@scribam @blamboo I am guessing you can request a change or do a pull request saying OpenGL is being deprecated and Vulkan is the default one.

**Comment by drillsar** [comment]
If I am not mistaken soon OpenGl will be taken out completely. Vulkan is better just still work in progress.
The docs should be updated to mention this.

**Comment by tmccaff** [comment]
Proposed a pull request #734 to mention the use of Vulkan over OpenGL. This issue should be closed.
