### ISSUE TITLE
Xam_User_cc bug?

### ISSUE THREAD

**Issue by drillsar** [benvanik/xenia#730]
I was looking at the code in Xam_user.cc

and noticed this line:
```
if (user_index) {
    // Only support user 0.
    SHIM_SET_RETURN_32(X_ERROR_NOT_LOGGED_ON);
    return;
  }
```
Why 2 returns?

**Comment by maxton** [comment]
Really? That's not two returns. That is a statement setting the return value and a return.

**Comment by drillsar** [comment]
I see that now when I removed the shim got confused trying to convert to new style and having issues with this shim call xamuserfriends in that file.
