### ISSUE TITLE
Imported a variable with no value

### ISSUE THREAD

**Issue by tmccaff** [benvanik/xenia#733]
Getting the following in Xenia logs:

C> 00002160 WARNING: imported a variable with no value: ExTimerObjectType
C> 00002160 WARNING: imported a variable with no value: ExSemaphoreObjectType
C> 00002160 WARNING: imported a variable with no value: ExEventObjectType
C> 00002160 WARNING: imported a variable with no value: ExThreadObjectType

**Comment by DrChat** [comment]
These are fine as of now. They're filled with dummy values that are referenced later in Xenia code.
