### ISSUE TITLE
Xenia crash with certain game

### ISSUE THREAD

**Issue by Spinn10** [benvanik/xenia#738]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Spinn10** [comment]
Hey everyone,
so I hope you can help me out with this.
When I first noticed there's an XBOX 360 emulator, I really got happy. I could finally play a game of my childhood on my PC. But my problem is, that when I start Xenia and select the game "Viva Pinata Trouble in Paradise" (It's a .iso-file) , it starts. But at a certain point, it says Xenia crashed. A few times when I tried it, there was a message from Windows, which said, "NVIDIA Kernel Driver ..." (or something like that) does not respond anymore. Can you help me out please?!

My PC contains:
GPU: GTX 1050 Ti (with lastest drivers) (OpenGL 4.5 compatible)
CPU: AMD Ryzen 5 1400 (should be AVX or AVX2 compatible)
8 GB RAM

I'll put the log in here. (I didn't figure out how to put a screenshot into this :/)
[xenia.txt](https://github.com/benvanik/xenia/files/1105079/xenia.txt)

**Comment by Margen67** [comment]
# DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!

![see](https://user-images.githubusercontent.com/3462541/27589131-37909230-5aff-11e7-8d7b-d2093e496845.png)

**Comment by tmccaff** [comment]
go to http://xenia.jp use the compatibility tracker for the game and add the issue.

**Comment by Spinn10** [comment]
@Margen67 thanks for telling me.
I didn't know whether this is a game issue or something else. I'm not really confident with such topics.
My apologies.

**Comment by reaperfallen** [comment]
Hi! I'm having a trouble with the game, the game crash and generate a folder called "scratch"... 
I'll give you the file you're finding in the subfolder "gpu", I think you can examine it and find a solution.

Specs 
2700x
GTX 970
8x2 GB Ram 2400Mhz
Windows 10 Last Version (1903)
