### ISSUE TITLE
Not sure if this is a bug in Xaudio2

### ISSUE THREAD

**Issue by tmccaff** [benvanik/xenia#739]
I am troubleshooting audio issues in certain games. I came across this:

In Xenia/Src/xenia/apu/xaudio2/xaudio2_audio_system.cc

On line:
46 it has  xdriver->Shutdown();
47 has assert_not_null(xdriver);

isn't it supposed to be the other way around? 
46 assert_not_null(xdriver);
47  xdriver->Shutdown();

**Comment by tmccaff** [comment]
@DrChat I think found another bug this time in emulator.cc
on line 112 has this std::unique_ptr<xe::cpu::backend::Backend> backend;
113 has if (!backend) {

Why should be check the value of the smart pointer if we haven’t placed anything there? This check is redundant and it should be removed. Or this is a logical error (a wrong variable is checked) and it should be fixed. I am thinking more of a logical error, but not sure what variable is to be checked.

**Comment by DrChat** [comment]
@tmccaff The order of the two statements does not matter. If xdriver is null, it's fucked either way.
And the backend nullptr check is valid. It is most certainly not a bug.

I appreciate that you're trying to learn C++ and how this emulator works at the same time, just keep the learning to yourself for now. You're raising way too many non-issues as of now.
And I wish you luck learning C++ through this project.
