### ISSUE TITLE
Request: TSX instructions

### ISSUE THREAD

**Issue by GoldWind** [benvanik/xenia#74]
Could you implement TSX instructions in Xenia,they increase multithreading performance and maybe they could help with synchronisation between threads.

**Comment by eligrey** [comment]
@benvanik Many current CPUs support TSX correctly now. Most of Broadwell-E, all of Kaby Lake-H, and a few of the consumer Broadwell and Skylake CPUs now correctly support TSX (if you have the relevant microcode updates).

**Comment by raven02** [comment]
Yes rpcs3 just provides support of tsx which help persona 5 heavily
