### ISSUE TITLE
Add Futurize Python 2 + 3 compatibility

### ISSUE THREAD

**Issue by drillsar** [benvanik/xenia#748]
It allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead.

I can start this, but not sure what files need to be changed for this to happen.

**Comment by rlabrecque** [comment]
#747 fixes one of the few python 3 incompatibilities.

The only other changes to make xenia py3 compatible now are basically just in. https://github.com/benvanik/xenia/blob/master/xb.bat

**Comment by Kriskras99** [comment]
I'm currently working on making xenia-build (and xb.bat) Python 3 compatible.

**Comment by drillsar** [comment]
@Kriskras99 ok thanks. I was looking into it, but if your doing it I won't. Thanks
