### ISSUE TITLE
i can´t download xenia( i only have the 8.0 windows capatible version) 

### ISSUE THREAD

**Issue by iwanttobethebee** [benvanik/xenia#752]
[//]: # (i can not download the new version of xenia because were u putted(click here) i was directed into a website that said(memcpy function fix V512)

[//]: # (Describe what should happen:) when i click the word "here" it should downloud the new version of xenia

[//]: # (If applicable, provide a callstack here - esp. for crashes) ... idk

[//]: # (If applicable, upload a logfile and link it here)
[xenia - Xbox 360 Research Emulator - Google Chrome 9_7_2017 12_45_05 a. m..mp4.zip](https://github.com/benvanik/xenia/files/1133559/xenia.-.Xbox.360.Research.Emulator.-.Google.Chrome.9_7_2017.12_45_05.a.m.mp4.zip)

**Comment by Margen67** [comment]
what

**Comment by mmdanggg2** [comment]
I think you were looking for this: 
![image](https://user-images.githubusercontent.com/3161587/27993886-ef097400-64a9-11e7-9bae-2f00b6137d8a.png)

![image](https://user-images.githubusercontent.com/3161587/27993896-0b58ad92-64aa-11e7-9a67-24c19f9a1b50.png)

![image](https://user-images.githubusercontent.com/3161587/27993902-1d1ea5ae-64aa-11e7-93a9-cebb98fb81cd.png)

![image](https://user-images.githubusercontent.com/3161587/27993905-2f8c5e34-64aa-11e7-8d1c-2df0838d44d8.png)

**Comment by iwanttobethebee** [comment]
thanks mmdang (\'o'/)

**Comment by iwanttobethebee** [comment]
i closed it because idk how to put a checkmark in the issue

**Comment by gibbed** [comment]
Closing the issue is the correct thing to do.
