### ISSUE TITLE
gflags.cc bug fixed

### ISSUE THREAD

**Issue by drillsar** [benvanik/xenia#754]
gflags new version fixes this bug I think, but one on my next comment is a new bug.
Was getting the following error from PVS Studio Analyzer issue #746 

V575 gflags.cc 556 The 'strncmp' function processes '0' elements. Inspect the third argument.

The line 556:
```
  if (strncmp(clean_name, kRootDir, sizeof(kRootDir)-1) == 0) { 
```
Change line to: thanks to schuhschuh
```
if (sizeof(kRootDir) > 1 && strncmp(clean_name, kRootDir, sizeof(kRootDir)-1) == 0) {
```

**Comment by drillsar** [comment]
Another bug Fixes 728 an excessive check in gflags.cc on line 1030,1031:

```
if (arg[0] != '-' ||           // must be a program argument
  | (arg[0] == '-' && arg[1] == '\0')) {  // "-" is an argument, not a flag
```
should be changed to:
```
if (arg[0] != '-' || arg[1] == '\0') {	// must be a program argument "-" is an argument, not a flag
```

**Comment by iwanttobethebee** [comment]
ok

**Comment by drillsar** [comment]
Did a pull request for these changes at:
https://github.com/benvanik/gflags

**Comment by drillsar** [comment]
Fixed
