### ISSUE TITLE
AMD GPU: Crashes when loading any game with Vulkan backend

### ISSUE THREAD

**Issue by shadowbrony33** [benvanik/xenia#759]
Xenia instantly crashes when loading any game with the Vulkan Backend with AMD GPU (R9 390X) Driver 17.7.1.
I will test this on a 1050Ti when I get the chance.

Crash log for Sonic 06:
https://pastebin.com/YRVqaYq8

**Comment by zerocold1981** [comment]
!> 00000004 Vulkan check: vkCreateImage returned VK_ERROR_INITIALIZATION_FAILED 
again...

**Comment by Margen67** [comment]
#578 ?

**Comment by zerocold1981** [comment]
Yes, the discussion #578is closed prematurely. After all, the problem with AMD is still there and you need at least some sort of solution
