### ISSUE TITLE
Float comparisson

### ISSUE THREAD

**Issue by drillsar** [benvanik/xenia#765]
I was looking over the code and seen the following code pipeline_cache.cc line 724 which is I think supposed to be doing bit-representation check. This is just one case many others like it

```
bool PipelineCache::SetShadowRegister(float* dest, uint32_t register_name) {
  float value = register_file_->values[register_name].f32;
  if (*dest == value) {
    return false;
  }
  *dest = value;
  return true;
}
```
shouldn't it be like an example

```

if (fabs(*dest - value) < 0.00001)
```
or something like that

From what I read you want to compare two float values, but in this case it's wrong. The thing is, if both float numbers that we are comparing contain NaN (even in the same bit representation), you'll get *dest != value, and your code will not work in the way you want.

**Comment by gibbed** [comment]
Nope.

**Comment by paulsapps** [comment]
Very detail technical argument there @gibbed :P

**Comment by drillsar** [comment]
lol ok. I just thought it's wrong to compare floats with ==

**Comment by gibbed** [comment]
@paulsapps @drillsar It only matters if we actually care about the value of the float. For most cases, we are passing floats off to another library/driver and don't actually care what the value is.

**Comment by drillsar** [comment]
@gibbed Thanks for explaining that. I guess we can close this than.
