### ISSUE TITLE
Constant Propagation OPCODE_SPLAT Appears to be Broken

### ISSUE THREAD

**Issue by AllanCat** [benvanik/xenia#767]
### Issue
As I mentioned [here](https://github.com/xenia-project/game-compatibility/issues/285#issuecomment-314017320), the constant speed up for OPCODE_SPLAT breaks many games's vertices and physics(Tested on **Sonic06**(wonky camera, death on jump pad) and **Bayonetta**(enemy spinning like fridge spinner)).

This change was in [PR#514](https://github.com/benvanik/xenia/pull/514), comment out OPCODE_SPLAT makes many stuff working again. I haven't figured out why it causes problem, only found out by comparing logged values between Splat in value.cc and the original Splat in hir_builder.cc, the values have different ordering and amounts(but most part are the same).

### Video
Before(test video by EOGC):
https://www.youtube.com/watch?v=6AaForznZF8
After(with some other fixes on my xenia fork):
https://www.youtube.com/watch?v=Fb0TJT4f73k

### Log file
Here's the log file for Sonic 06, I commented OPCODE_SPLAT out and only log the values.
[splat_log.txt](https://github.com/benvanik/xenia/files/1177728/splat_log.txt)
It's logged as "!> 00000028 splat(cpp or hb) type: %d, value: %d"
You can searching by using keyword "splat".

**Comment by DrChat** [comment]
This is a very nice catch! Awesome work.

I'm not too sure what would cause the difference between the [JIT's splat](https://github.com/benvanik/xenia/blob/master/src/xenia/cpu/backend/x64/x64_sequences.cc#L6623) implementation, and the constant implementation though.

**Comment by AllanCat** [comment]
@DrChat 
With constant check "(i->src1.value->IsConstant() && i->src2.value->IsConstant())" these two opcodes in cpp almost got zero hit, only 1 OPCODE_DOT_PRODUCT_3 on Bayonetta's opening(and after this it didn't pass to hir_builder which is weird too).

Logging OPCODE_DOT_PRODUCT_3/4 without constant check in cpp and hir_builder can yield some data, with constant check it just got zero hit.

I tried the following combinations:
1.  Comment out OPCODE_DOT_PRODUCT_3 and OPCODE_DOT_PRODUCT_4 in cpp
The games are still broken.
2.  Comment out OPCODE_DOT_PRODUCT_3, OPCODE_DOT_PRODUCT_4 and OPCODE_SPLAT in cpp
Seems no changes compared to only comment out OPCODE_SPLAT.

**Comment by AllanCat** [comment]
Oops I'm dumb, it's passing to x64_sequences like you mentioned, now the amounts and values are the same(see log file, only logged INT32_TYPE). I'll try to print out dest value to see what's difference.
[xenia_splat2.txt](https://github.com/benvanik/xenia/files/1188308/xenia_splat2.txt)

**Comment by DrChat** [comment]
Yeah - could you do some investigation of the differences in output between the constant dot product and the JIT's dot product?

Splat doesn't seem to be the issue - and the only way to have a float splat is from dot product.

**Comment by DrChat** [comment]
I may have been wrong to point out DP3/DP4.
Set a breakpoint in that OPCODE_SPLAT case in the propagation pass, and walk the `i->prev` chain backwards until you hit an OPCODE_SOURCE_OFFSET, then report what you see here.

**Comment by AllanCat** [comment]
Okay, here's the test report:
I set breakpoint on OPCODE_SPLAT's INT32_TYPE(since INT32_TYPE is what cause game breaks)
This is the first hit on Sonic06 with i->src1.value->constant.i32 = 0x00000001
![splat](https://user-images.githubusercontent.com/1924514/28972489-6e9914e2-7962-11e7-8c57-65d598c3b2d7.png)
There's a lot of 1b0, can't sure what it is.

Btw I can't go further because Xenia crashes on playing video file when running with VS2015(both debug/released)

**Comment by DrChat** [comment]
Okay, that means it's a future instruction. Just to verify that this particular splat causes an issue, skip it in the VS debugger (by dragging the execution pointer to the break statement) and see if it fixes anything.

**Comment by DrChat** [comment]
Instructions that use OPCODE_SPLAT (**but not necessarily the culprit**):
```
vcfsx
vcfux
vctsxs
vctuxs
vmsum3fp128
vmsum4fp128
vspltb
vsplth
vspltw
vspltisb
vspltish
vspltisw
```

**Comment by SakataGintokiYT** [comment]
OPCODE_SPLAT: ON / OFF
![n](https://user-images.githubusercontent.com/13681488/36871451-9709ca54-1da2-11e8-9acb-11963f43b18f.png)

**Comment by DrChat** [comment]
@SakataGintokiYT Interesting. Appreciate the picture showing the impact!
This is most likely an x86 backend SSE instruction clobbering a constant input somehow.

**Comment by DrChat** [comment]
@SakataGintokiYT @AllanCat Do you both have AVX2 enabled or disabled?
If it's enabled, could you specify `--enable_haswell_instructions=false` and test it again?

**Comment by Parovozik** [comment]
@DrChat this equally for ivy-bridge CPU's too

**Comment by DrChat** [comment]
Okay, cool.
@Parovozik, can you verify if 6c97dbaf81010e7345c5cd8119bbc663c274c5d4 affects this bug at all?

**Comment by Parovozik** [comment]
@DrChat i tried. This without changes for me.
# Logs:
[Naruto UNS3.log](https://github.com/benvanik/xenia/files/1776281/Naruto.UNS3.log)
[Sonic.log](https://github.com/benvanik/xenia/files/1776283/Sonic.log)
[bayonetta.log](https://github.com/benvanik/xenia/files/1776284/bayonetta.log)
# Screenshots:
![bandicam 2018-03-02 21-51-48-075](https://user-images.githubusercontent.com/19775644/36916454-ff637164-1e64-11e8-80dd-82ff28d80171.jpg)
![bandicam 2018-03-02 21-44-37-702](https://user-images.githubusercontent.com/19775644/36916473-0af2e474-1e65-11e8-94ff-a6d821a7da29.jpg)
![bandicam 2018-03-02 21-48-47-114](https://user-images.githubusercontent.com/19775644/36916477-0ee4b24c-1e65-11e8-90f8-25e95a4f1e98.jpg)

**Comment by DrChat** [comment]
Okay - are there any games with a quick repro case?
Can you find a game that takes less than 1 minute from boot to see this issue happen? Preferably the shortest you can find.

**Comment by Parovozik** [comment]
Sonic 2006 (if skip movie and cut-scene)

**Comment by DrChat** [comment]
Sonic 06 is a no-go. Blackscreens for me - I'll look into it later but I'm not interested in it now.

**Comment by DrChat** [comment]
Banjo Kazooie Nuts and Bolts appears to be a repro case. Camera angles messed up in intro.

**Comment by SakataGintokiYT** [comment]
@DrChat You can quickly reproduce this problem in Naruto UNS: Generations-Demo on the title screen.
![bez tytulu](https://user-images.githubusercontent.com/13681488/36920825-487c8f5a-1e62-11e8-9ae1-69e890e74ba9.png)

**Comment by DrChat** [comment]
@SakataGintokiYT Excellent - thanks.

# Occurrences of splats
## Naturo Storm: Generations
`822DA9BC                 vspltisw  v26, -1`
`822DAA00                 vspltisw  v8, 1`

**Comment by DrChat** [comment]
Offending function in full:

```
.text:822DB540 # =============== S U B R O U T I N E =======================================
.text:822DB540
.text:822DB540
.text:822DB540 sub_822DB540:                           # CODE XREF: sub_8218DFC8+CCp
.text:822DB540                                         # .text:821D19A0p ...
.text:822DB540                 vor128    v18, v62, v94
.text:822DB544                 vspltisw  v16, 1        # v16 = constant
.text:822DB548                 vor128    v17, v63, v95
.text:822DB54C                 vspltisw  v0, -1        # v0 = constant
.text:822DB550                 vor128    v15, v61, v93
.text:822DB554                 vor128    v19, v60, v92
.text:822DB558                 vpermwi128 v29, v18, 0xC8
.text:822DB55C                 vcfsx     v5, v16, 0    # v5 = constant
.text:822DB560                 vpermwi128 v28, v17, 0xB0
.text:822DB564                 vslw      v14, v16, v0  # v14 = constant
.text:822DB568                 vpermwi128 v23, v18, 0xB4
.text:822DB56C                 vpermwi128 v63, v17, 0xD8
.text:822DB570                 vpermwi128 v62, v18, 0x70
.text:822DB574                 vpermwi128 v61, v18, 0x84
.text:822DB578                 vmulfp128 v4, v29, v28
.text:822DB57C                 vpermwi128 v60, v17, 0xC4
.text:822DB580                 vpermwi128 v59, v17, 0x60
.text:822DB584                 vmulfp128 v3, v23, v63
.text:822DB588                 vpermwi128 v58, v17, 0xC8
.text:822DB58C                 vpermwi128 v57, v18, 0xC4
.text:822DB590                 vmulfp128 v2, v94, v60
.text:822DB594                 vpermwi128 v56, v18, 0x60
.text:822DB598                 vmulfp128 v1, v93, v59
.text:822DB59C                 vpermwi128 v55, v17, 0x70
.text:822DB5A0                 vpermwi128 v54, v17, 0x84
.text:822DB5A4                 vor128    v13, v90, v58
.text:822DB5A8                 vpermwi128 v25, v18, 0xB0
.text:822DB5AC                 vor128    v9, v89, v57
.text:822DB5B0                 vpermwi128 v30, v18, 0xD8
.text:822DB5B4                 vor128    v7, v88, v56
.text:822DB5B8                 vpermwi128 v27, v17, 0xB4
.text:822DB5BC                 vor128    v8, v87, v55
.text:822DB5C0                 vor128    v6, v86, v54
.text:822DB5C4                 vpermwi128 v53, v15, 0x6C
.text:822DB5C8                 vnmsubfp  v4, v25, v4, v13
.text:822DB5CC                 vpermwi128 v52, v15, 0x2C
.text:822DB5D0                 vpermwi128 v51, v15, 0x1C
.text:822DB5D4                 vnmsubfp  v0, v30, v3, v27
.text:822DB5D8                 vpermwi128 v31, v19, 0xD8
.text:822DB5DC                 vmulfp128 v22, v30, v27
.text:822DB5E0                 vpermwi128 v50, v19, 0xB4
.text:822DB5E4                 vspltisw  v3, 0
.text:822DB5E8                 vnmsubfp  v13, v9, v2, v8
.text:822DB5EC                 vpermwi128 v48, v19, 0xC8
.text:822DB5F0                 vnmsubfp  v12, v7, v1, v6
.text:822DB5F4                 vpermwi128 v1, v19, 0xB0
.text:822DB5F8                 vmulfp128 v21, v31, v27
.text:822DB5FC                 vor       v6, v23, v23
.text:822DB600                 vmulfp128 v24, v82, v30
.text:822DB604                 vpermwi128 v49, v19, 0xC4
.text:822DB608                 vmulfp128 v20, v80, v25
.text:822DB60C                 vpermwi128 v47, v19, 0x70
.text:822DB610                 vpermwi128 v46, v19, 0x60
.text:822DB614                 vmulfp128 v26, v1, v58
.text:822DB618                 vpermwi128 v45, v19, 0x84
.text:822DB61C                 vmulfp128 v25, v25, v58
.text:822DB620                 vmsum3fp128 v44, v84, v4
.text:822DB624                 vor128    v2, v95, v63
.text:822DB628                 vmsum3fp128 v43, v85, v0
.text:822DB62C                 vmsum3fp128 v42, v83, v13
.text:822DB630                 vmsum3fp128 v41, v15, v12
.text:822DB634                 vmrghw128 v0, v75, v42
.text:822DB638                 vmrghw128 v13, v76, v41
.text:822DB63C                 vmrghw    v0, v0, v13
.text:822DB640                 vmsum4fp128 v40, v19, v0
.text:822DB644                 vrefp128  v0, v40
.text:822DB648                 vor128    v10, v72, v40
.text:822DB64C                 vor128    v9, v72, v40
.text:822DB650                 vcmpeqfp128 v30, v72, v3
.text:822DB654                 vor128    v3, v82, v50
.text:822DB658                 vnmsubfp  v8, v0, v5, v10
.text:822DB65C                 vor       v12, v0, v0
.text:822DB660                 vcmpeqfp  v27, v0, v14
.text:822DB664                 vor       v10, v28, v28
.text:822DB668                 vmaddfp   v0, v0, v0, v8
.text:822DB66C                 vnmsubfp  v8, v0, v5, v9
.text:822DB670                 vor       v9, v31, v31
.text:822DB674                 vor128    v5, v95, v63
.text:822DB678                 vor       v31, v29, v29
.text:822DB67C                 vnmsubfp  v23, v9, v24, v23
.text:822DB680                 vmaddfp   v4, v0, v0, v8
.text:822DB684                 vor       v8, v29, v29
.text:822DB688                 vnmsubfp  v22, v6, v22, v5
.text:822DB68C                 vor       v0, v28, v28
.text:822DB690                 vmulfp128 v28, v79, v57
.text:822DB694                 vor128    v13, v80, v48
.text:822DB698                 vmulfp128 v29, v89, v55
.text:822DB69C                 vnmsubfp  v21, v3, v21, v2
.text:822DB6A0                 vor128    v7, v94, v62
.text:822DB6A4                 vnmsubfp  v2, v8, v25, v10
.text:822DB6A8                 vor128    v6, v81, v49
.text:822DB6AC                 vnmsubfp  v24, v1, v20, v31
.text:822DB6B0                 vpermwi128 v63, v19, 0x6C
.text:822DB6B4                 vnmsubfp  v3, v13, v26, v0
.text:822DB6B8                 vor128    v9, v92, v60
.text:822DB6BC                 vor128    v8, v94, v62
.text:822DB6C0                 vpermwi128 v58, v19, 0x2C
.text:822DB6C4                 vsel      v5, v4, v14, v27
.text:822DB6C8                 vmsum3fp128 v27, v85, v23
.text:822DB6CC                 vpermwi128 v26, v19, 0x1C
.text:822DB6D0                 vandc128  v20, v72, v14
.text:822DB6D4                 vspltisw128 v57, -9
.text:822DB6D8                 vmulfp128 v31, v81, v55
.text:822DB6DC                 vmulfp128 v1, v77, v56
.text:822DB6E0                 vmsum3fp128 v25, v95, v22
.text:822DB6E4                 vnmsubfp  v4, v6, v28, v7
.text:822DB6E8                 vor128    v6, v78, v46
.text:822DB6EC                 vnmsubfp  v7, v8, v29, v9
.text:822DB6F0                 vsel      v29, v5, v12, v30
.text:822DB6F4                 vmsum3fp128 v23, v85, v21
.text:822DB6F8                 vslw128   v0, v16, v57
.text:822DB6FC                 vmsum3fp128 v30, v90, v2
.text:822DB700                 vmulfp128 v2, v88, v54
.text:822DB704                 vmsum3fp128 v12, v84, v24
.text:822DB708                 vor128    v5, v92, v60
.text:822DB70C                 vmsum3fp128 v8, v84, v3
.text:822DB710                 vmulfp128 v3, v78, v54
.text:822DB714                 vcmpgtfp  v0, v0, v20
.text:822DB718                 vmsum3fp128 v28, v83, v4
.text:822DB71C                 vor128    v4, v79, v47
.text:822DB720                 vmrghw    v9, v25, v27
.text:822DB724                 vmsum3fp128 v27, v26, v7
.text:822DB728                 vor128    v7, v93, v61
.text:822DB72C                 vnmsubfp  v31, v4, v31, v5
.text:822DB730                 vmrghw128 v26, v75, v23
.text:822DB734                 vmrghw    v12, v30, v12
.text:822DB738                 vnmsubfp  v5, v6, v1, v7
.text:822DB73C                 vmrghw128 v8, v76, v8
.text:822DB740                 vmrghw    v9, v26, v9
.text:822DB744                 vmrghw    v12, v8, v12
.text:822DB748                 vmulfp128 v9, v29, v9
.text:822DB74C                 vmsum3fp128 v6, v83, v31
.text:822DB750                 vmulfp128 v12, v29, v12
.text:822DB754                 vmrghw    v4, v27, v28
.text:822DB758                 vsel      v8, v9, v19, v0
.text:822DB75C                 vor128    v9, v91, v59
.text:822DB760                 vsel      v10, v12, v15, v0
.text:822DB764                 vor128    v92, v8, v8
.text:822DB768                 vor128    v8, v93, v61
.text:822DB76C                 vor128    v12, v91, v59
.text:822DB770                 vor128    v93, v10, v10
.text:822DB774                 vor128    v10, v77, v45
.text:822DB778                 vnmsubfp  v7, v8, v2, v9
.text:822DB77C                 vnmsubfp  v9, v10, v3, v12
.text:822DB780                 vmrghw128 v10, v74, v6
.text:822DB784                 vmrghw    v10, v10, v4
.text:822DB788                 vmulfp128 v10, v29, v10
.text:822DB78C                 vmsum3fp128 v8, v19, v7
.text:822DB790                 vmsum3fp128 v12, v15, v9
.text:822DB794                 vmsum3fp128 v9, v15, v5
.text:822DB798                 vmrghw128 v12, v73, v12
.text:822DB79C                 vmrghw    v8, v8, v9
.text:822DB7A0                 vsel      v9, v10, v18, v0
.text:822DB7A4                 vmrghw    v12, v12, v8
.text:822DB7A8                 vor128    v94, v9, v9
.text:822DB7AC                 vmulfp128 v12, v29, v12
.text:822DB7B0                 vsel      v0, v12, v17, v0
.text:822DB7B4                 vor128    v95, v0, v0
.text:822DB7B8                 blr
.text:822DB7B8 # End of function sub_822DB540
```

**Comment by DrChat** [comment]
Found the culprit. Going to test, and will release in a bit.

**Comment by DrChat** [comment]
Okay guys, can you confirm that this is fixed as of 3a8f8f2ecb2f28aaa82543ad8cf6ec3ff81bac94?

**Comment by SakataGintokiYT** [comment]
[3a8f8f2]
![desktop screenshot 2018 03 03 - 02 24 55 20](https://user-images.githubusercontent.com/13681488/36928881-31f6c62e-1e8a-11e8-8d2d-95bcd11a9309.png)

**Comment by Parovozik** [comment]
Its finee now
![bandicam 2018-03-03 04-24-46-587](https://user-images.githubusercontent.com/19775644/36928927-9d846976-1e9b-11e8-9cc0-11a7953a5f6d.jpg)
![bandicam 2018-03-03 04-26-30-311](https://user-images.githubusercontent.com/19775644/36928929-a0b8189a-1e9b-11e8-8741-ac2dc478b3b8.jpg)
![bandicam 2018-03-03 04-27-30-486](https://user-images.githubusercontent.com/19775644/36928932-a364c8c2-1e9b-11e8-924c-0f099c861a50.jpg)
![bandicam 2018-03-03 04-29-12-282](https://user-images.githubusercontent.com/19775644/36928937-a6f5d3b4-1e9b-11e8-8d41-1eb8814b4a70.jpg)

**Comment by DrChat** [comment]
Awesome! Appreciate the help guys.
