### ISSUE TITLE
Remove OpenGL

### ISSUE THREAD

**Issue by drillsar** [benvanik/xenia#769]
Since Vulkan is making progress, shouldn't OpenGL be removed completely? Not sure where to start removing this.

**Comment by shadowbrony33** [comment]
Everything under:
xenia-gpu-gl4,
xenia-gpu-gl4-trace-dump,
xenia-gpu-gl4-trace-viewer,
xenia-ui-gl,
etc.

**Comment by drillsar** [comment]
One file hid_demo.cc not working this is the change. Not sure why it's not working but probably not needed anyway.

original code in this file:
```
std::unique_ptr<xe::ui::GraphicsProvider> CreateDemoGraphicsProvider(
    xe::ui::Window* window) {
  return xe::ui::gl::GLProvider::Create(window);
}
```
I changed to:
```
std::unique_ptr<xe::ui::GraphicsProvider> CreateDemoGraphicsProvider(
    xe::ui::Window* window) {
  return xe::ui::vulkan::VulkanProvider::Create(window);
}
```
however, I get this error:
hid_demo.obj : error LNK2019: unresolved external symbol "public: static class std::unique_ptr<class xe::ui::GraphicsPr
ovider,struct std::default_delete<class xe::ui::GraphicsProvider> > __cdecl xe::ui::gl::GLProvider::Create(class xe::ui
::Window *)" (?Create@GLProvider@gl@ui@xe@@SA?AV?$unique_ptr@VGraphicsProvider@ui@xe@@U?$default_delete@VGraphicsProvid
er@ui@xe@@@std@@@std@@PEAVWindow@34@@Z) referenced in function "class std::unique_ptr<class xe::ui::GraphicsProvider,st
ruct std::default_delete<class xe::ui::GraphicsProvider> > __cdecl xe::hid::CreateDemoGraphicsProvider(class xe::ui::Wi
ndow *)" (?CreateDemoGraphicsProvider@hid@xe@@YA?AV?$unique_ptr@VGraphicsProvider@ui@xe@@U?$default_delete@VGraphicsPro
vider@ui@xe@@@std@@@std@@PEAVWindow@ui@2@@Z) [C:\Users\Tom\Documents\xenia\build\xenia-hid-demo.vcxproj]
bin\Windows\Debug\xenia-hid-demo.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\Tom\Documents\xenia\build\
xenia-hid-demo.vcxproj]

**Comment by shadowbrony33** [comment]
Just remove
`std::unique_ptr<xe::ui::GraphicsProvider> CreateDemoGraphicsProvider(
    xe::ui::Window* window) {
  return xe::ui::gl::GLProvider::Create(window);
}`
`#include "xenia/gpu/gl4/gl4_graphics_system.h"`
and change
`DEFINE_string(gpu, "any", "Graphics system. Use: [any, gl4, vulkan, null]");`
to
`DEFINE_string(gpu, "any", "Graphics system. Use: [any, vulkan, null]");`

**Comment by gibbed** [comment]
I appreciate the interest here, but you don't need to try and force this issue. @DrChat can do the removal when deemed acceptable.
