### ISSUE TITLE
Why remove OpenGL?

### ISSUE THREAD

**Issue by Parovozik** [benvanik/xenia#772]
![11111](https://user-images.githubusercontent.com/19775644/29006520-50880a46-7afa-11e7-97e1-32aeaa6ea824.jpg)

One question - why? :(

[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by drillsar** [comment]
It's deprecated and no longer supported. This project moved to Vulkan awhile ago.

**Comment by shadowbrony33** [comment]
Almost a year ago if I remember correctly

**Comment by drillsar** [comment]
On my copy of Xenia; I removed it completely.

**Comment by shadowbrony33** [comment]
same here when I remove the files from gl4

**Comment by Margen67** [comment]
Once all of Vulkan's regressions are fixed OpenGL will be removed.

I somehow doubt any system with a GPU that doesn't even support Vulkan would run the emulator that well.

**Comment by Parovozik** [comment]
On OpenGL some games works is fine, but on Vulkan even not start.

**Comment by Margen67** [comment]
Like I said before it will only be removed once Vulkan is better and has no regressions compared to OpenGL.

Having a deprecated backend bloats up the code/repo. It's open source so you're welcome to make your own fork with OpenGL support.

**Comment by Parovozik** [comment]
@Margen67  Thanks!
