### ISSUE TITLE
Appveyor failing to build due to a warning being handled as an error

### ISSUE THREAD

**Issue by shadowbrony33** [benvanik/xenia#773]
Appveyor refuses to compile any build since [cce5182](https://github.com/benvanik/xenia/commit/cce5182725465043f9ed913ef4c3941250cf7f6a)

`..\src\xenia\gpu\vulkan\vulkan_command_processor.cc(880): error C2220: warning treated as error - no object' file generated [C:\dev\xenia\build\xenia-gpu-vulkan.vcxproj]
..\src\xenia\gpu\vulkan\vulkan_command_processor.cc(880): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning) [C:\dev\xenia\build\xenia-gpu-vulkan.vcxproj]
..\src\xenia\gpu\vulkan\vulkan_command_processor.cc(881): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning) [C:\dev\xenia\build\xenia-gpu-vulkan.vcxproj]
..\src\xenia\gpu\vulkan\vulkan_command_processor.cc(1167): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning) [C:\dev\xenia\build\xenia-gpu-vulkan.vcxproj]`

However in Visual Studio it compiles just fine.

EDIT:
>"Fix the problems that cause warnings in your project.
>Compile at a lower warning level—for example, use /W3 instead of /W4.
>Use a warning pragma to disable or suppress a specific warning.
>Don't use /WX to compile." 
>  Microsoft Developer Network
 [C220](https://msdn.microsoft.com/en-us/library/ksk5k0ta.aspx)

**Comment by shadowbrony33** [comment]
Thankyou @gibbed

**Comment by gibbed** [comment]
Now it's fixed.
