### ISSUE TITLE
Xenia Crash After Launching A Game??

### ISSUE THREAD

**Issue by FartacusV2** [benvanik/xenia#774]
Everytime I try to launch a game it just says "xenia.exe has stopped working". Any ideas of what the problem might be? 

My specs are fine:
Intel Core I5 4670k
AMD Radeon 580
Windows 10

**Comment by raynebc** [comment]
I sometimes have to try to launch a game several times (because Xenia crashes) before it will emulate normally.  I haven't found a pattern for why it sometimes does this when I follow the same steps with similar timing during each attempt.  Do you find any difference if you launch Xenia with OpenGL instead of DirectX and vice-versa?

**Comment by FartacusV2** [comment]
I didn't know you could run it differently. Don't even know how to do it, explanation please? :)

**Comment by raynebc** [comment]
Sorry, I meant to say OpenGL instead of Vulkan.  You use the "--gpu=gl4" (without quotation marks) command line parameter.  You can add this parameter to the target field of a shortcut in Windows, just make sure there is white space between this parameter and the program's executable file name.

**Comment by Margen67** [comment]
#702 unless it only occurs with a certain game which in that case it doesn't belong here and should be posted to https://github.com/xenia-project/game-compatibility/

**Comment by FartacusV2** [comment]
Happens with all games, one of them being Red Dead Redemption which is tested and should work.

**Comment by Margen67** [comment]
Does it happen if you drag the game onto xenia.exe?

**Comment by FartacusV2** [comment]
Both when dragging and selecting through the "app"

**Comment by Margen67** [comment]
I mean in Windows explorer.

**Comment by FartacusV2** [comment]
Yeah I have done that, and it doesn't help

**Comment by FartacusV2** [comment]
I've tried dragging it to a shortcut too

**Comment by Gamedev1909** [comment]
amd is busted for xenia again seems we had one working build in ages then something changes and boom dead

**Comment by FartacusV2** [comment]
Hmmm too bad, i'll have to revisit again when you might have a fix at hand, or if you knew which build it was that worked..?

**Comment by shadowbrony33** [comment]
Try using my builds of xenia [(here)](https://ci.appveyor.com/project/shadowbrony33/xenia/history).
I'm using an AMD GPU and I made these as a hackish fix.

**Comment by FartacusV2** [comment]
Release or Checked?

**Comment by shadowbrony33** [comment]
Use release

**Comment by FartacusV2** [comment]
(Y)

**Comment by FartacusV2** [comment]
It works now, thank you very much for your help!

**Comment by FartacusV2** [comment]
Well, it launches games atleast. The games can't find a storage locations for profile saves though.

**Comment by shadowbrony33** [comment]
That's normal

**Comment by shadowbrony33** [comment]
@gibbed close this issue

**Comment by FartacusV2** [comment]
Should I just wait for newer updates until it get's fixed, or can I do something about it then?

**Comment by shadowbrony33** [comment]
All I've been able to do is change the 24-bit texture and depth formats to 32-bit.
Haven't noticed any issues on Nvidia hardware so far with this.

**Comment by FartacusV2** [comment]
Ah okay, seems like I have to be getting myself a 1080 ;)

**Comment by shadowbrony33** [comment]
That would be a waste of money

**Comment by shadowbrony33** [comment]
DrChat has already found a solution but he is in the process or refining it so expect the fix in the next month or so.

**Comment by FartacusV2** [comment]
A fix for AMD?

**Comment by shadowbrony33** [comment]
yes

**Comment by raynebc** [comment]
Inconsistent crashes (ie. sometimes Xenia crashes, sometimes it works) on game launch also occur with Nvidia hardware, it's not AMD specific.  I use a GTX 1060.

**Comment by Gamedev1909** [comment]
@shadowbrony33 may i love you??? please join the xenia team @DrChat please use his fix

**Comment by Gamedev1909** [comment]
![wowwww](https://user-images.githubusercontent.com/18043258/29095690-34f07e8e-7c68-11e7-9304-ab32c1c9ef52.PNG)

**Comment by shadowbrony33** [comment]
Gladly but I don't have any means of directly communicating with DrChat.

Also you're welcome! If you have any questions / requests just let me know.

**Comment by Gamedev1909** [comment]
@shadowbrony33 1 request can you make ODST menu render hehe i want in game

**Comment by shadowbrony33** [comment]
I wish I could fix that but for now I can't.

**Comment by Gamedev1909** [comment]
thats fine you have done so much already

**Comment by shadowbrony33** [comment]
@Gamedev1909 Waiting for my pull request that fixes the AMD issue to be merged.

**Comment by AD010** [comment]
please add support Intel HD GT1 and CPU without AVX to Xenia. Master and Canary only crash with all settings with Intel SDE

**Comment by Codexmsters** [comment]
My Xenia Keeps Crashing
