### ISSUE TITLE
xenia.exe not run

### ISSUE THREAD

**Issue by zjwkof** [benvanik/xenia#787]
lost:   api-ms-win-shcore-scaling-l1-1-1.dll

win8 x64

**Comment by zjwkof** [comment]
win10 x64  run ok

**Comment by Sarkie** [comment]
You'll probably need a Windows update and Visual C++ Libs.

**Comment by Razzile** [comment]
xenia only supports windows 8.1 or higher

**Comment by fatmaninhell** [comment]
hi guys i get the following error : MSVCP140.dll is missing, i did download c++ 2015,  what else do i need to run the program ?thanks

**Comment by cesarj238** [comment]
@fatmaninhell since you have it installed do you have Windows 8 or 10 if you do go to command prompt and have the administrator access then in there you type sfc /scannow (space in between that)

**Comment by fatmaninhell** [comment]
Hi i have windows 8.1 pro. Will try and let u knw later. I appreciate the response. Thanks

**Comment by Razzile** [comment]
@fatmaninhell build xenia in release mode and that error will go away
