### ISSUE TITLE
Feature Request: Higher internal resolution.

### ISSUE THREAD

**Issue by GoldWind** [benvanik/xenia#79]
Could you please add option to increase internal resolution without any hard limit. Many emulators can do this with great results.

**Comment by ADormant** [comment]
@benvanik This may be helpful https://www.reddit.com/r/emulation/comments/3y8d8k/how_would_internal_resolution_scaling_work_with/

**Comment by paulsapps** [comment]
@ADormant pretty sure @benvanik knows what he's doing, its a matter of having other higher priority things finished first.
