### ISSUE TITLE
could you try porting to windows 7?

### ISSUE THREAD

**Issue by minuteworld** [benvanik/xenia#790]
jus' wondering.

**Comment by shadowbrony33** [comment]
No, and don't open an issue for a question, use reddit.com/r/Xenia. @DrChat close this.

**Comment by Margen67** [comment]
Duplicate of https://github.com/benvanik/xenia/issues/677 & https://github.com/benvanik/xenia/issues/68

**Comment by DrChat** [comment]
Nope!
If you or anyone else wants to, it's potentially a simple fix that just hangs on the usage of one particular Windows API.
