### ISSUE TITLE
Faq states Haswell with AVX extension, instead of just AVX support

### ISSUE THREAD

**Issue by BenNewsome** [benvanik/xenia#793]
It would be good if the website documentation faq changed from Haswell with AVX to just say AVX extension support, to stop people being concerned or confused about being locked down to Intel.

**Comment by shadowbrony33** [comment]
Agreed

**Comment by maxton** [comment]
You can open a pull request on the `gh-pages` branch if you want to make that change.

**Comment by DrChat** [comment]
Updated the FAQ!
