### ISSUE TITLE
Scott Pilgrim vs the world game: Colours are off

### ISSUE THREAD

**Issue by MarkRMurphy** [benvanik/xenia#802]
Nothing especially game breaking just that the colours are off.
![spvstw](https://user-images.githubusercontent.com/32885370/31692674-a839d348-b392-11e7-8af9-955d7686e33a.PNG)
Just wondering how to fix it.

**Comment by robert-7** [comment]
Hi @MarkRMurphy , there's a section where issues are opened against specific games that can be found here: https://github.com/xenia-project/game-compatibility/issues . Specifically, you want this issue: https://github.com/xenia-project/game-compatibility/issues/114 . Please comment about this problem there

**Comment by MarkRMurphy** [comment]
thanks man
