### ISSUE TITLE
Recognize OpenGL 4.60

### ISSUE THREAD

**Issue by raynebc** [benvanik/xenia#804]
I know OpenGL is being deprecated in Xenia's source, but it might be nice to support a version newer than 4.50 in the meantime.

A suitably easy fix is to change line 289 of gl_context.cc to:

`if ((glsl_version.find("4.5") != 0) && (glsl_version.find("4.6") != 0))`

(or regex to allow 4. followed by any digit higher than 4).

**Comment by shadowbrony33** [comment]
Have it find 4.5 and above if you can do that instead of just adding 4.6 in case newer versions of GL release.

**Comment by raynebc** [comment]
I'm not good with C++, so I wasn't sure if it was worth a more complicated solution (parse the number into major and minor versions and formally compare against each to account for all future possible OpenGL versions) when it's quite possible the developers will remove OpenGL support entirely by the time OpenGL 4.70 or higher is implemented by the video card manufacturers.

**Comment by joaozin23** [comment]
![esboco](https://user-images.githubusercontent.com/17303493/33514070-b04daca6-d734-11e7-950e-5fe3430e0560.png)

**Comment by joaozin23** [comment]
NOT compatible with OpenGL 4.6 my:xenia: :rage:

**Comment by raynebc** [comment]
@joaozin23 You will have to edit the source code and build it if you want to launch the game with OpenGL 4.6.

**Comment by CodenameIridium** [comment]
Fix ![image](https://user-images.githubusercontent.com/34288869/33636671-17a8ac2e-da15-11e7-966c-61ed2a01fc3a.png)

**Comment by raynebc** [comment]
No desire to even change the version string check?  That's so little work.

**Comment by DrChat** [comment]
@raynebc I've closed this because we have PR #816 for this.

**Comment by raynebc** [comment]
OK, thank you for that information.
