### ISSUE TITLE
fix built correctly on systems with non-Latin codepages.

### ISSUE THREAD

**Issue by yxmline** [benvanik/xenia#812]
fix built correctly on systems with non-Latin codepages.fix error C2220
Add in the premake5.lua 122 line
"/utf-8", --'built correctly on systems with non-Latin codepages'.

**Comment by Razzile** [comment]
this would be better as a pull request than an issue

**Comment by LaLoLZ** [comment]
![image](https://user-images.githubusercontent.com/34289194/33637355-6de3e420-da18-11e7-9163-873a1befb61e.png)

**Comment by TheCubeMaster019** [comment]
Added a pull request with the update -- thanks a lot, @yxmline~
