### ISSUE TITLE
Proper ISO/STFS directory enumeration

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#96]
Only host filesystem currently does this; need to support it on ISO/STFS to make testing easier.

* Kameo
* Street Fighter
* Puzzle Bobble
* Catan

**Comment by benvanik** [comment]
Currently relying on FindFirstFile and other Win32 APIs - need to use custom enumerator with consistent ordering and wildcard support. That should then be used on the host fs to ensure consistency.

**Comment by benvanik** [comment]
HostPathEntry using Win32 APIs: https://github.com/benvanik/xenia/blob/master/src/xenia/kernel/fs/devices/host_path_entry.cc#L75

Instead, it should be listing all children on creation so that a generic Entry enumeration function can be used and shared between all implementations. Both DiscImage and StfsContainer already somewhat do this, but are missing the filter support.

DiscImageEntry (https://github.com/benvanik/xenia/blob/master/src/xenia/kernel/fs/devices/disc_image_entry.cc#L59) and StfsContainerEntry (https://github.com/benvanik/xenia/blob/master/src/xenia/kernel/fs/devices/stfs_container_entry.cc#L51) are both broken and only support '*'.

Moving the child enumeration code into Entry so that all 3 implementations can share it would be really nice. Only the code filling the XDirectoryInfo in the device-specific way should be unique across them.

**Comment by benvanik** [comment]
Space Giraffe does a *.png enumeration.

**Comment by benvanik** [comment]
From Dust does '*'

**Comment by benvanik** [comment]
Hexic 2 does *.jpg

**Comment by x1nixmzeng** [comment]
I still need to look at moving the routine into common code, and hooking this up with the host paths.

**Comment by benvanik** [comment]
Done.
